az: active-object.h File Reference
active-object.h File Reference
#include <az/classes/attrib-dict.h>
#include <az/object.h>
#include <az/packed-value.h>
Data Structures
struct AZObjectAttribute
struct AZObjectAttributeArray
struct AZObjectEventVector
struct AZObjectListener
struct AZObjectCallbackBlock
struct AZActiveObject
struct AZActiveObjectClass
Macros
#define AZ_TYPE_ACTIVE_OBJECT az_active_object_get_type ()
#define AZ_ACTIVE_OBJECT(o) (AZ_CHECK_INSTANCE_CAST ((o), AZ_TYPE_ACTIVE_OBJECT, AZActiveObject))
#define AZ_IS_ACTIVE_OBJECT(o) (AZ_CHECK_INSTANCE_TYPE ((o), AZ_TYPE_ACTIVE_OBJECT))
Functions
unsigned int az_active_object_get_type (void)
unsigned int az_active_object_get_attribute (AZActiveObject *aobj, AZString *key, const AZImplementation **impl, AZValue64 *val)
unsigned int az_active_object_set_attribute (AZActiveObject *aobj, AZString *key, const AZImplementation *impl, const AZValue *val)
unsigned int az_active_object_clear_attribute (AZActiveObject *aobj, AZString *key)
void az_active_object_add_listener (AZActiveObject *aobj, const AZObjectEventVector *vector, unsigned int size, void *data)
void az_active_object_remove_listener_by_data (AZActiveObject *aobj, void *data)
unsigned int az_active_object_set_attribute_i32 (AZActiveObject *aobj, const unsigned char *key, int value)
unsigned int az_active_object_set_attribute_object (AZActiveObject *aobj, const unsigned char *key, AZObject *value)
Macro Definition Documentation
AZ_ACTIVE_OBJECT
#define AZ_ACTIVE_OBJECT (o) (AZ_CHECK_INSTANCE_CAST ((o), AZ_TYPE_ACTIVE_OBJECT, AZActiveObject))
AZ_IS_ACTIVE_OBJECT
#define AZ_IS_ACTIVE_OBJECT (o) (AZ_CHECK_INSTANCE_TYPE ((o), AZ_TYPE_ACTIVE_OBJECT))
AZ_TYPE_ACTIVE_OBJECT
#define AZ_TYPE_ACTIVE_OBJECT az_active_object_get_type ()
Function Documentation
az_active_object_add_listener()
void az_active_object_add_listener (AZActiveObject * aobj, const AZObjectEventVector * vector, unsigned int size, void * data)
Referenced by az_object_list_append_object(), az_object_list_insert_object(), and az_weak_reference_set().
az_active_object_clear_attribute()
unsigned int az_active_object_clear_attribute (AZActiveObject * aobj, AZString * key)
References AZ_IS_ACTIVE_OBJECT, az_packed_value_clear(), and az_string_unref().
Referenced by aobj_attrd_set().
az_active_object_get_attribute()
unsigned int az_active_object_get_attribute (AZActiveObject * aobj, AZString * key, const AZImplementation ** impl, AZValue64 * val)
References az_attrib_dict_lookup(), and AZ_IS_ACTIVE_OBJECT.
Referenced by active_object_call_getAttribute().
az_active_object_get_type()
unsigned int az_active_object_get_type (void)
References az_active_object_class_init(), AZ_FLAG_ABSTRACT, az_register_type(), and AZ_TYPE_OBJECT.
az_active_object_remove_listener_by_data()
void az_active_object_remove_listener_by_data (AZActiveObject * aobj, void * data)
Referenced by az_object_list_clear(), az_object_list_remove_object(), az_object_list_remove_object_by_index(), az_weak_reference_clear(), object_list_finalize(), and weak_reference_finalize().
az_active_object_set_attribute()
unsigned int az_active_object_set_attribute (AZActiveObject * aobj, AZString * key, const AZImplementation * impl, const AZValue * val)
References az_attrib_dict_set(), and az_value_get_inst().
Referenced by active_object_call_setAttribute(), az_active_object_set_attribute_i32(), and az_active_object_set_attribute_object().
az_active_object_set_attribute_i32()
unsigned int az_active_object_set_attribute_i32 (AZActiveObject * aobj, const unsigned char * key, int value)
References az_active_object_set_attribute(), az_string_new(), az_string_unref(), az_type_get_impl, and AZ_TYPE_INT32.
az_active_object_set_attribute_object()
unsigned int az_active_object_set_attribute_object (AZActiveObject * aobj, const unsigned char * key, AZObject * value)
References az_active_object_set_attribute(), az_string_new(), and az_string_unref().