az: active-object.c File Reference
active-object.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/boxed-value.h>
#include <az/packed-value.h>
#include <az/extend.h>
#include <az/classes/active-object.h>
Macros
#define __AZ_ACTIVE_OBJECT_C__
Enumerations
enum { FUNC_SETATTRIBUTE , FUNC_GETATTRIBUTE , NUM_PROPERTIES }
Functions
static void az_active_object_class_init (AZActiveObjectClass *klass)
static void az_active_object_shutdown (AZObject *object)
static unsigned int aobj_aa_get_size (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int aobj_aa_contains (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * aobj_aa_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
static const AZImplementation * aobj_aa_map_lookup (const AZMapImplementation *map_impl, void *map_inst, const AZImplementation *key_impl, void *key_inst, AZValue *val, unsigned int size)
static unsigned int aobj_aa_keys_contains (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * aobj_aa_keys_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
const AZImplementation * aobj_attrd_lookup (const AZAttribDictImplementation *aa_impl, void *aa_inst, const AZString *key, AZValue *val, int size, unsigned int *flags)
unsigned int aobj_attrd_set (const AZAttribDictImplementation *aa_impl, void *aa_inst, AZString *key, const AZImplementation *impl, void *inst, unsigned int flags)
static unsigned int active_object_call_setAttribute (const AZImplementation **arg_impls, const AZValue **arg_vals, const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
static unsigned int active_object_call_getAttribute (const AZImplementation **arg_impls, const AZValue **arg_vals, const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_active_object_get_type (void)
static AZObjectAttribute * az_active_object_get_attribute_slot (AZActiveObject *aobj, AZString *key, unsigned int create)
unsigned int az_active_object_get_attribute (AZActiveObject *aobj, AZString *key, const AZImplementation **impl, AZValue64 *val)
unsigned int az_active_object_set_attribute (AZActiveObject *aobj, AZString *key, const AZImplementation *impl, const AZValue *val)
unsigned int az_active_object_clear_attribute (AZActiveObject *aobj, AZString *key)
void az_active_object_add_listener (AZActiveObject *aobj, const AZObjectEventVector *vector, unsigned int size, void *data)
void az_active_object_remove_listener_by_data (AZActiveObject *aobj, void *data)
unsigned int az_active_object_set_attribute_i32 (AZActiveObject *aobj, const unsigned char *key, int value)
unsigned int az_active_object_set_attribute_object (AZActiveObject *aobj, const unsigned char *key, AZObject *value)
Macro Definition Documentation
__AZ_ACTIVE_OBJECT_C__
#define __AZ_ACTIVE_OBJECT_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FUNC_SETATTRIBUTE
FUNC_GETATTRIBUTE
NUM_PROPERTIES
Function Documentation
active_object_call_getAttribute()
static unsigned int active_object_call_getAttribute (const AZImplementation ** arg_impls, const AZValue ** arg_vals, const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References az_active_object_get_attribute().
Referenced by az_active_object_class_init().
active_object_call_setAttribute()
static unsigned int active_object_call_setAttribute (const AZImplementation ** arg_impls, const AZValue ** arg_vals, const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References az_active_object_set_attribute().
Referenced by az_active_object_class_init().
aobj_aa_contains()
static unsigned int aobj_aa_contains (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZImplementation * impl, const void * inst) static
References az_value_equals_instance().
Referenced by az_active_object_class_init().
aobj_aa_get_element()
static const AZImplementation * aobj_aa_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_value_copy_autobox().
Referenced by az_active_object_class_init().
aobj_aa_get_size()
static unsigned int aobj_aa_get_size (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by az_active_object_class_init().
aobj_aa_keys_contains()
static unsigned int aobj_aa_keys_contains (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZImplementation * impl, const void * inst) static
References AZ_IMPL_TYPE, and AZ_TYPE_STRING.
Referenced by az_active_object_class_init().
aobj_aa_keys_get_element()
static const AZImplementation * aobj_aa_keys_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_value_set_reference(), and AZStringKlass.
Referenced by az_active_object_class_init().
aobj_aa_map_lookup()
static const AZImplementation * aobj_aa_map_lookup (const AZMapImplementation * map_impl, void * map_inst, const AZImplementation * key_impl, void * key_inst, AZValue * val, unsigned int size) static
References AZ_IMPL_TYPE, AZ_TYPE_STRING, and az_value_copy_autobox().
aobj_attrd_lookup()
const AZImplementation * aobj_attrd_lookup (const AZAttribDictImplementation * aa_impl, void * aa_inst, const AZString * key, AZValue * val, int size, unsigned int * flags)
References az_value_copy_autobox().
Referenced by az_active_object_class_init().
aobj_attrd_set()
unsigned int aobj_attrd_set (const AZAttribDictImplementation * aa_impl, void * aa_inst, AZString * key, const AZImplementation * impl, void * inst, unsigned int flags)
References az_active_object_clear_attribute(), az_active_object_get_attribute_slot(), and az_packed_value_set_from_impl_instance.
Referenced by az_active_object_class_init().
az_active_object_add_listener()
void az_active_object_add_listener (AZActiveObject * aobj, const AZObjectEventVector * vector, unsigned int size, void * data)
Referenced by az_object_list_append_object(), az_object_list_insert_object(), and az_weak_reference_set().
az_active_object_class_init()
static void az_active_object_class_init (AZActiveObjectClass * klass) static
References active_object_call_getAttribute(), active_object_call_setAttribute(), aobj_aa_contains(), aobj_aa_get_element(), aobj_aa_get_size(), aobj_aa_keys_contains(), aobj_aa_keys_get_element(), aobj_attrd_lookup(), aobj_attrd_set(), az_active_object_shutdown(), az_class_declare_interface(), az_class_set_num_interfaces(), AZ_TYPE_ANY, AZ_TYPE_ATTRIBUTE_DICT, AZ_TYPE_NONE, AZ_TYPE_STRING, FUNC_GETATTRIBUTE, FUNC_SETATTRIBUTE, and NUM_PROPERTIES.
Referenced by az_active_object_get_type().
az_active_object_clear_attribute()
unsigned int az_active_object_clear_attribute (AZActiveObject * aobj, AZString * key)
References AZ_IS_ACTIVE_OBJECT, az_packed_value_clear(), and az_string_unref().
Referenced by aobj_attrd_set().
az_active_object_get_attribute()
unsigned int az_active_object_get_attribute (AZActiveObject * aobj, AZString * key, const AZImplementation ** impl, AZValue64 * val)
References az_attrib_dict_lookup(), and AZ_IS_ACTIVE_OBJECT.
Referenced by active_object_call_getAttribute().
az_active_object_get_attribute_slot()
static AZObjectAttribute * az_active_object_get_attribute_slot (AZActiveObject * aobj, AZString * key, unsigned int create) static
References az_string_ref().
Referenced by aobj_attrd_set().
az_active_object_get_type()
unsigned int az_active_object_get_type (void)
References az_active_object_class_init(), AZ_FLAG_ABSTRACT, az_register_type(), and AZ_TYPE_OBJECT.
az_active_object_remove_listener_by_data()
void az_active_object_remove_listener_by_data (AZActiveObject * aobj, void * data)
Referenced by az_object_list_clear(), az_object_list_remove_object(), az_object_list_remove_object_by_index(), az_weak_reference_clear(), object_list_finalize(), and weak_reference_finalize().
az_active_object_set_attribute()
unsigned int az_active_object_set_attribute (AZActiveObject * aobj, AZString * key, const AZImplementation * impl, const AZValue * val)
References az_attrib_dict_set(), and az_value_get_inst().
Referenced by active_object_call_setAttribute(), az_active_object_set_attribute_i32(), and az_active_object_set_attribute_object().
az_active_object_set_attribute_i32()
unsigned int az_active_object_set_attribute_i32 (AZActiveObject * aobj, const unsigned char * key, int value)
References az_active_object_set_attribute(), az_string_new(), az_string_unref(), az_type_get_impl, and AZ_TYPE_INT32.
az_active_object_set_attribute_object()
unsigned int az_active_object_set_attribute_object (AZActiveObject * aobj, const unsigned char * key, AZObject * value)
References az_active_object_set_attribute(), az_string_new(), and az_string_unref().
az_active_object_shutdown()
static void az_active_object_shutdown (AZObject * object) static
References az_packed_value_clear(), and az_string_unref().
Referenced by az_active_object_class_init().