az: array.h File Reference
array.h File Reference
#include <az/collections/list.h>
#include <az/object.h>
Data Structures
struct AZArray
A ligthweight value type for interacting with C arrays.
struct AZArrayClass
struct AZArrayObject
a frontend object to array
struct AZArrayObjectClass
Macros
#define AZ_TYPE_ARRAY az_array_get_type()
#define AZ_TYPE_ARRAY_OBJECT az_array_object_get_type()
#define AZ_ARRAY_OBJ_FLAG_OWNED 0x2
Functions
unsigned int az_array_get_type ()
static AZValue * az_array_value_at (const AZArray *array, unsigned int idx)
unsigned int az_array_object_get_type ()
AZArrayObject * az_array_object_new (unsigned int elem_type, unsigned int size)
AZArrayObject * az_array_object_new_static (unsigned int elem_type, unsigned int size, void *values)
const AZListImplementation * az_array_object_get_list (AZArrayObject *obj, void **inst)
static AZValue * az_array_object_value_at (AZArrayObject *aobj, unsigned int idx)
Macro Definition Documentation
AZ_ARRAY_OBJ_FLAG_OWNED
#define AZ_ARRAY_OBJ_FLAG_OWNED 0x2
AZ_TYPE_ARRAY
#define AZ_TYPE_ARRAY az_array_get_type()
AZ_TYPE_ARRAY_OBJECT
#define AZ_TYPE_ARRAY_OBJECT az_array_object_get_type()
Function Documentation
az_array_get_type()
unsigned int az_array_get_type ()
References array_class, array_class_init(), array_type, az_register_type(), and AZ_TYPE_STRUCT.
az_array_object_get_list()
const AZListImplementation * az_array_object_get_list (AZArrayObject * obj, void ** inst)
References az_array_object_class.
az_array_object_get_type()
unsigned int az_array_object_get_type ()
References array_object_class_init(), array_object_instance_finalize(), array_object_instance_init(), az_array_object_class, az_array_object_type, AZ_FLAG_FINAL, az_register_type(), and AZ_TYPE_OBJECT.
az_array_object_new()
AZArrayObject * az_array_object_new (unsigned int elem_type, unsigned int size)
References AZ_ARRAY_OBJ_FLAG_OWNED, AZ_IMPL_FROM_TYPE, az_object_new(), az_object_set_flags(), AZ_TYPE_ARRAY_OBJECT, AZ_TYPE_IS_FINAL, AZ_TYPE_IS_INTERFACE, AZ_TYPE_IS_OBJECT, and az_value_new_array().
az_array_object_new_static()
AZArrayObject * az_array_object_new_static (unsigned int elem_type, unsigned int size, void * values)
References az_object_new(), AZ_TYPE_ARRAY_OBJECT, AZ_TYPE_IS_FINAL, and AZ_TYPE_IS_OBJECT.
az_array_object_value_at()
static AZValue * az_array_object_value_at (AZArrayObject * aobj, unsigned int idx) inline static
References AZ_CLASS_ELEMENT_SIZE, and AZ_CLASS_FROM_TYPE.
az_array_value_at()
static AZValue * az_array_value_at (const AZArray * array, unsigned int idx) inline static
References AZ_CLASS_ELEMENT_SIZE, and AZ_CLASS_FROM_TYPE.
Referenced by array_deserialize(), and array_serialize().