az: array-list.h File Reference
array-list.h File Reference
#include <az/collections/list.h>
#include <az/reference.h>
Data Structures
struct AZArrayListEntry
struct AZArrayList
struct AZArrayListClass
Macros
#define AZ_TYPE_ARRAY_LIST az_array_list_get_type ()
Functions
unsigned int az_array_list_get_type (void)
AZArrayList * az_array_list_new (unsigned int el_type, unsigned int val_size)
static void az_array_list_delete (AZArrayList *alist)
static const AZImplementation * az_array_list_get_element (AZArrayList *alist, unsigned int idx, AZValue *val, unsigned int size)
void az_array_list_clear (AZArrayList *alist)
unsigned int az_array_list_set_element (AZArrayList *alist, unsigned int idx, const AZImplementation *impl, void *inst)
unsigned int az_array_list_append (AZArrayList *alist, const AZImplementation *impl, void *inst)
unsigned int az_array_list_insert (AZArrayList *alist, unsigned int idx, const AZImplementation *impl, void *inst)
unsigned int az_array_list_remove (AZArrayList *alist, unsigned int idx)
static AZArrayListEntry * az_array_list_get_entry (AZArrayList *alist, unsigned int idx)
static unsigned int az_array_list_entry_size (AZArrayList *alist)
Variables
AZArrayListClass * AZArrayListKlass
Macro Definition Documentation
AZ_TYPE_ARRAY_LIST
#define AZ_TYPE_ARRAY_LIST az_array_list_get_type ()
Function Documentation
az_array_list_append()
unsigned int az_array_list_append (AZArrayList * alist, const AZImplementation * impl, void * inst)
References az_array_list_entry_size(), az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), and az_value_set_from_inst_autobox().
az_array_list_clear()
void az_array_list_clear (AZArrayList * alist)
References az_array_list_get_entry(), and az_value_clear().
az_array_list_delete()
static void az_array_list_delete (AZArrayList * alist) inline static
References az_instance_delete(), and AZ_TYPE_ARRAY_LIST.
az_array_list_entry_size()
static unsigned int az_array_list_entry_size (AZArrayList * alist) inline static
Referenced by az_array_list_append(), az_array_list_insert(), and az_array_list_remove().
az_array_list_get_element()
static const AZImplementation * az_array_list_get_element (AZArrayList * alist, unsigned int idx, AZValue * val, unsigned int size) inline static
References az_list_get_element(), and AZArrayListKlass.
az_array_list_get_entry()
static AZArrayListEntry * az_array_list_get_entry (AZArrayList * alist, unsigned int idx) inline static
Referenced by array_list_contains(), array_list_finalize(), array_list_get_element(), az_array_list_append(), az_array_list_clear(), az_array_list_insert(), az_array_list_remove(), and az_array_list_set_element().
az_array_list_get_type()
unsigned int az_array_list_get_type (void)
References array_list_class_init(), array_list_contains(), array_list_finalize(), array_list_get_element(), array_list_get_element_type(), array_list_get_size(), array_list_init(), az_register_type(), AZ_TYPE_BLOCK, and AZArrayListKlass.
az_array_list_insert()
unsigned int az_array_list_insert (AZArrayList * alist, unsigned int idx, const AZImplementation * impl, void * inst)
References az_array_list_entry_size(), az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), and az_value_set_from_inst_autobox().
az_array_list_new()
AZArrayList * az_array_list_new (unsigned int el_type, unsigned int val_size)
References az_instance_new(), and AZ_TYPE_ARRAY_LIST.
az_array_list_remove()
unsigned int az_array_list_remove (AZArrayList * alist, unsigned int idx)
References az_array_list_entry_size(), az_array_list_get_entry(), and az_value_clear().
az_array_list_set_element()
unsigned int az_array_list_set_element (AZArrayList * alist, unsigned int idx, const AZImplementation * impl, void * inst)
References az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), az_value_clear(), and az_value_set_from_inst_autobox().
Variable Documentation
AZArrayListKlass
AZArrayListClass* AZArrayListKlass extern
Referenced by az_array_list_get_element(), and az_array_list_get_type().