az: array-list.c File Reference
array-list.c File Reference
#include <stdlib.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/boxed-value.h>
#include <az/packed-value.h>
#include <az/private.h>
#include <az/extend.h>
#include "array-list.h"
Macros
#define __AZ_ARRAY_LIST_C__
Functions
static void array_list_class_init (AZArrayListClass *klass)
static void array_list_init (AZArrayListClass *klass, AZArrayList *alist)
static void array_list_finalize (AZArrayListClass *klass, AZArrayList *alist)
static unsigned int array_list_get_element_type (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int array_list_get_size (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int array_list_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * array_list_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_array_list_get_type (void)
AZArrayList * az_array_list_new (unsigned int el_type, unsigned int val_size)
void az_array_list_clear (AZArrayList *alist)
unsigned int az_array_list_set_element (AZArrayList *alist, unsigned int idx, const AZImplementation *impl, void *inst)
unsigned int az_array_list_append (AZArrayList *alist, const AZImplementation *impl, void *inst)
unsigned int az_array_list_insert (AZArrayList *alist, unsigned int idx, const AZImplementation *impl, void *inst)
unsigned int az_array_list_remove (AZArrayList *alist, unsigned int idx)
Variables
AZArrayListClass * AZArrayListKlass = NULL
Macro Definition Documentation
__AZ_ARRAY_LIST_C__
#define __AZ_ARRAY_LIST_C__
Function Documentation
array_list_class_init()
static void array_list_class_init (AZArrayListClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), and AZ_TYPE_LIST.
Referenced by az_array_list_get_type().
array_list_contains()
static unsigned int array_list_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
References az_array_list_get_entry(), and az_value_equals_instance_autobox().
Referenced by az_array_list_get_type().
array_list_finalize()
static void array_list_finalize (AZArrayListClass * klass, AZArrayList * alist) static
References az_array_list_get_entry(), and az_value_clear().
Referenced by az_array_list_get_type().
array_list_get_element()
static const AZImplementation * array_list_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_array_list_get_entry(), and az_value_copy_autobox().
Referenced by az_array_list_get_type().
array_list_get_element_type()
static unsigned int array_list_get_element_type (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by az_array_list_get_type().
array_list_get_size()
static unsigned int array_list_get_size (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by az_array_list_get_type().
array_list_init()
static void array_list_init (AZArrayListClass * klass, AZArrayList * alist) static
References AZ_TYPE_ANY.
Referenced by az_array_list_get_type().
az_array_list_append()
unsigned int az_array_list_append (AZArrayList * alist, const AZImplementation * impl, void * inst)
References az_array_list_entry_size(), az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), and az_value_set_from_inst_autobox().
az_array_list_clear()
void az_array_list_clear (AZArrayList * alist)
References az_array_list_get_entry(), and az_value_clear().
az_array_list_get_type()
unsigned int az_array_list_get_type (void)
References array_list_class_init(), array_list_contains(), array_list_finalize(), array_list_get_element(), array_list_get_element_type(), array_list_get_size(), array_list_init(), az_register_type(), AZ_TYPE_BLOCK, and AZArrayListKlass.
az_array_list_insert()
unsigned int az_array_list_insert (AZArrayList * alist, unsigned int idx, const AZImplementation * impl, void * inst)
References az_array_list_entry_size(), az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), and az_value_set_from_inst_autobox().
az_array_list_new()
AZArrayList * az_array_list_new (unsigned int el_type, unsigned int val_size)
References az_instance_new(), and AZ_TYPE_ARRAY_LIST.
az_array_list_remove()
unsigned int az_array_list_remove (AZArrayList * alist, unsigned int idx)
References az_array_list_entry_size(), az_array_list_get_entry(), and az_value_clear().
az_array_list_set_element()
unsigned int az_array_list_set_element (AZArrayList * alist, unsigned int idx, const AZImplementation * impl, void * inst)
References az_array_list_get_entry(), AZ_IMPL_TYPE, az_type_is_a(), az_value_clear(), and az_value_set_from_inst_autobox().
Variable Documentation
AZArrayListKlass
AZArrayListClass* AZArrayListKlass = NULL
Referenced by az_array_list_get_element(), and az_array_list_get_type().