az: array-of.c File Reference
array-of.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <az/array-of.h>
#include <az/extend.h>
Macros
#define __AZ_ARRAY_OF_C__
Functions
static void array_of_class_init (AZArrayOfClass *klass, AZClass *element_class)
static void array_of_instance_init (AZArrayOfClass *klass, AZArrayOf *array_of)
static void array_of_instance_finalize (AZArrayOfClass *klass, AZArrayOf *array_of)
unsigned int az_array_of_get_type (unsigned int element_type)
unsigned int az_array_of_get_instance_size (unsigned int element_type, unsigned int size)
void * az_array_of_get_element_instance (AZArrayOf *array_of, unsigned int element_type, unsigned int idx)
void az_array_of_init (AZArrayOf *array_of, unsigned int element_type, unsigned int size)
void az_array_of_finalize (AZArrayOf *array_of, unsigned int element_type)
AZArrayOf * az_array_of_new (unsigned int element_type, unsigned int size)
void az_array_of_free (AZArrayOf *array_of, unsigned int element_type)
Macro Definition Documentation
__AZ_ARRAY_OF_C__
#define __AZ_ARRAY_OF_C__
Function Documentation
array_of_class_init()
static void array_of_class_init (AZArrayOfClass * klass, AZClass * element_class) static
References AZ_CLASS_TYPE.
Referenced by az_array_of_get_type().
array_of_instance_finalize()
static void array_of_instance_finalize (AZArrayOfClass * klass, AZArrayOf * array_of) static
References az_array_of_get_element_instance(), and az_instance_finalize().
Referenced by az_array_of_get_type().
array_of_instance_init()
static void array_of_instance_init (AZArrayOfClass * klass, AZArrayOf * array_of) static
Referenced by az_array_of_get_type().
az_array_of_finalize()
void az_array_of_finalize (AZArrayOf * array_of, unsigned int element_type)
az_array_of_free()
void az_array_of_free (AZArrayOf * array_of, unsigned int element_type)
az_array_of_get_element_instance()
void * az_array_of_get_element_instance (AZArrayOf * array_of, unsigned int element_type, unsigned int idx)
Referenced by array_of_instance_finalize().
az_array_of_get_instance_size()
unsigned int az_array_of_get_instance_size (unsigned int element_type, unsigned int size)
az_array_of_get_type()
unsigned int az_array_of_get_type (unsigned int element_type)
References array_of_class_init(), array_of_instance_finalize(), array_of_instance_init(), AZ_FLAG_ABSTRACT, az_register_composite_type(), az_type_get_class, and AZ_TYPE_STRUCT.
az_array_of_init()
void az_array_of_init (AZArrayOf * array_of, unsigned int element_type, unsigned int size)
az_array_of_new()
AZArrayOf * az_array_of_new (unsigned int element_type, unsigned int size)