az: array.c File Reference
array.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <az/base.h>
#include <az/boxed-value.h>
#include <az/collections/array.h>
#include <az/extend.h>
Macros
#define __AZ_ARRAY_C__
Functions
static void array_class_init (AZArrayClass *klass)
static unsigned int array_serialize (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int array_deserialize (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static unsigned int array_get_element_type (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int array_get_size (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int array_contains (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * array_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_array_get_type ()
static void array_object_class_init (AZArrayObjectClass *klass)
static void array_object_instance_init (AZArrayObjectClass *klass, AZArrayObject *aobj)
static void array_object_instance_finalize (AZArrayObjectClass *klass, AZArrayObject *aobj)
static unsigned int array_object_element_type (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int array_object_size (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int array_object_contains (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * array_object_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_array_object_get_type ()
AZArrayObject * az_array_object_new (unsigned int elem_type, unsigned int length)
AZArrayObject * az_array_object_new_static (unsigned int elem_type, unsigned int length, void *values)
const AZListImplementation * az_array_object_get_list (AZArrayObject *obj, void **inst)
Variables
static unsigned int array_type = 0
static AZArrayClass * array_class
static unsigned int az_array_object_type = 0
static AZArrayObjectClass * az_array_object_class = NULL
Macro Definition Documentation
__AZ_ARRAY_C__
#define __AZ_ARRAY_C__
Function Documentation
array_class_init()
static void array_class_init (AZArrayClass * klass) static
References array_contains(), array_deserialize(), array_get_element(), array_get_element_type(), array_get_size(), array_serialize(), az_class_declare_interface(), az_class_set_num_interfaces(), and AZ_TYPE_LIST.
Referenced by az_array_get_type().
array_contains()
unsigned int array_contains (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZImplementation * impl, const void * inst) static
References AZ_CLASS_ELEMENT_SIZE, AZ_CLASS_FROM_TYPE, AZ_IMPL_FROM_TYPE, and az_value_equals_instance_autobox().
Referenced by array_class_init().
array_deserialize()
static unsigned int array_deserialize (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
References az_array_value_at(), AZ_IMPL_FROM_TYPE, az_value_deserialize(), az_value_new_array(), and AZUint32Klass.
Referenced by array_class_init().
array_get_element()
static const AZImplementation * array_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References AZ_CLASS_ELEMENT_SIZE, AZ_CLASS_FROM_TYPE, AZ_IMPL_FROM_TYPE, and az_value_copy_autobox().
Referenced by array_class_init().
array_get_element_type()
unsigned int array_get_element_type (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by array_class_init().
array_get_size()
unsigned int array_get_size (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by array_class_init().
array_object_class_init()
static void array_object_class_init (AZArrayObjectClass * klass) static
References array_object_contains(), array_object_element_type(), array_object_get_element(), array_object_size(), az_class_declare_interface(), az_class_set_num_interfaces(), and AZ_TYPE_LIST.
Referenced by az_array_object_get_type().
array_object_contains()
unsigned int array_object_contains (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZImplementation * impl, const void * inst) static
References AZ_CLASS_ELEMENT_SIZE, AZ_CLASS_FROM_TYPE, AZ_IMPL_FROM_TYPE, and az_value_equals_instance_autobox().
Referenced by array_object_class_init().
array_object_element_type()
unsigned int array_object_element_type (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by array_object_class_init().
array_object_get_element()
static const AZImplementation * array_object_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References AZ_CLASS_ELEMENT_SIZE, AZ_CLASS_FROM_TYPE, AZ_IMPL_FROM_TYPE, and az_value_copy_autobox().
Referenced by array_object_class_init().
array_object_instance_finalize()
static void array_object_instance_finalize (AZArrayObjectClass * klass, AZArrayObject * aobj) static
References AZ_ARRAY_OBJ_FLAG_OWNED, AZ_IMPL_FROM_TYPE, az_object_flags(), and az_value_delete_array().
Referenced by az_array_object_get_type().
array_object_instance_init()
static void array_object_instance_init (AZArrayObjectClass * klass, AZArrayObject * aobj) static
Referenced by az_array_object_get_type().
array_object_size()
unsigned int array_object_size (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by array_object_class_init().
array_serialize()
static unsigned int array_serialize (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_array_value_at(), AZ_IMPL_FROM_TYPE, az_instance_serialize(), and AZUint32Klass.
Referenced by array_class_init().
az_array_get_type()
unsigned int az_array_get_type ()
References array_class, array_class_init(), array_type, az_register_type(), and AZ_TYPE_STRUCT.
az_array_object_get_list()
const AZListImplementation * az_array_object_get_list (AZArrayObject * obj, void ** inst)
References az_array_object_class.
az_array_object_get_type()
unsigned int az_array_object_get_type ()
References array_object_class_init(), array_object_instance_finalize(), array_object_instance_init(), az_array_object_class, az_array_object_type, AZ_FLAG_FINAL, az_register_type(), and AZ_TYPE_OBJECT.
az_array_object_new()
AZArrayObject * az_array_object_new (unsigned int elem_type, unsigned int length)
References AZ_ARRAY_OBJ_FLAG_OWNED, AZ_IMPL_FROM_TYPE, az_object_new(), az_object_set_flags(), AZ_TYPE_ARRAY_OBJECT, AZ_TYPE_IS_FINAL, AZ_TYPE_IS_INTERFACE, AZ_TYPE_IS_OBJECT, and az_value_new_array().
az_array_object_new_static()
AZArrayObject * az_array_object_new_static (unsigned int elem_type, unsigned int length, void * values)
References az_object_new(), AZ_TYPE_ARRAY_OBJECT, AZ_TYPE_IS_FINAL, and AZ_TYPE_IS_OBJECT.
Variable Documentation
array_class
AZArrayClass* array_class static
Referenced by az_array_get_type().
array_type
unsigned int array_type = 0 static
Referenced by az_array_get_type().
az_array_object_class
AZArrayObjectClass* az_array_object_class = NULL static
Referenced by az_array_object_get_list(), and az_array_object_get_type().
az_array_object_type
unsigned int az_array_object_type = 0 static
Referenced by az_array_object_get_type().