az: attrib-dict.h File Reference
attrib-dict.h File Reference
#include <az/collections/list.h>
#include <az/classes/map.h>
Data Structures
struct AZAttribDictImplementation
struct AZAttribDictClass
Macros
#define AZ_TYPE_ATTRIBUTE_DICT (az_attrib_dict_get_type ())
#define AZ_ATTRIB_ARRAY_IS_FINAL 1
Functions
unsigned int az_attrib_dict_get_type (void)
const AZImplementation * az_attrib_dict_lookup (const AZAttribDictImplementation *aa_impl, void *aa_inst, const AZString *key, AZValue64 *val, unsigned int *flags)
unsigned int az_attrib_dict_set (const AZAttribDictImplementation *aa_impl, void *aa_inst, AZString *key, const AZImplementation *impl, void *inst, unsigned int flags)
Macro Definition Documentation
AZ_ATTRIB_ARRAY_IS_FINAL
#define AZ_ATTRIB_ARRAY_IS_FINAL 1
AZ_TYPE_ATTRIBUTE_DICT
#define AZ_TYPE_ATTRIBUTE_DICT (az_attrib_dict_get_type ())
Function Documentation
az_attrib_dict_get_type()
unsigned int az_attrib_dict_get_type (void)
References attrib_dict_class, attrib_dict_impl_init(), attrib_dict_type, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), and AZ_TYPE_LIST.
az_attrib_dict_lookup()
const AZImplementation * az_attrib_dict_lookup (const AZAttribDictImplementation * aa_impl, void * aa_inst, const AZString * key, AZValue64 * val, unsigned int * flags)
Referenced by az_active_object_get_attribute().
az_attrib_dict_set()
unsigned int az_attrib_dict_set (const AZAttribDictImplementation * aa_impl, void * aa_inst, AZString * key, const AZImplementation * impl, void * inst, unsigned int flags)
Referenced by az_active_object_set_attribute().