az: attrib-dict.c File Reference
attrib-dict.c File Reference
#include <arikkei/arikkei-utils.h>
#include <az/packed-value.h>
#include "attrib-dict.h"
Macros
#define __AZ_ATTRIB_DICT_C__
Functions
static void attrib_dict_class_init (AZAttribDictClass *klass)
static void attrib_dict_impl_init (AZAttribDictImplementation *impl)
static unsigned int attrd_get_element_type (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int attrd_get_iterator (const AZCollectionImplementation *coll_impl, void *coll_inst, AZPackedValue *iter)
static unsigned int attrd_iterator_next (const AZCollectionImplementation *coll_impl, void *coll_inst, AZPackedValue *iter)
const AZImplementation * attrd_get_element (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZPackedValue *iterator, AZValue *val, unsigned int size)
static unsigned int attrd_get_key_type (const AZMapImplementation *map_impl, void *map_inst)
static const AZImplementation * attrd_get_key (const AZMapImplementation *map_impl, void *map_inst, const AZPackedValue *iter, AZValue *val, unsigned int size)
const AZCollectionImplementation * attrd_get_keys (const AZMapImplementation *map_impl, void *map_inst, void **inst)
const AZImplementation * attrd_lookup (const AZMapImplementation *map_impl, void *map_inst, const AZImplementation *key_impl, void *key_inst, AZValue *val, unsigned int size)
static unsigned int attrd_val_element_type (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int attrd_val_get_size (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int attrd_val_contains (const AZCollectionImplementation *coll_impl, void *coll_inst, const AZImplementation *impl, const void *inst)
static unsigned int attrd_keys_get_element_type (const AZCollectionImplementation *coll_impl, void *coll_inst)
static unsigned int attrd_keys_get_size (const AZCollectionImplementation *coll_impl, void *coll_inst)
unsigned int az_attrib_dict_get_type (void)
const AZImplementation * az_attrib_dict_lookup (const AZAttribDictImplementation *attrd_impl, void *attrd_inst, const AZString *key, AZValue64 *val, unsigned int *flags)
unsigned int az_attrib_dict_set (const AZAttribDictImplementation *attrd_impl, void *attrd_inst, AZString *key, const AZImplementation *impl, void *inst, unsigned int flags)
Variables
static unsigned int attrib_dict_type = 0
static AZAttribDictClass * attrib_dict_class
Macro Definition Documentation
__AZ_ATTRIB_DICT_C__
#define __AZ_ATTRIB_DICT_C__
Function Documentation
attrd_get_element()
const AZImplementation * attrd_get_element (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZPackedValue * iterator, AZValue * val, unsigned int size)
References az_list_get_element().
Referenced by attrib_dict_impl_init().
attrd_get_element_type()
static unsigned int attrd_get_element_type (const AZCollectionImplementation * coll_impl, void * coll_inst) static
References AZ_TYPE_ANY.
Referenced by attrib_dict_impl_init().
attrd_get_iterator()
static unsigned int attrd_get_iterator (const AZCollectionImplementation * coll_impl, void * coll_inst, AZPackedValue * iter) static
References az_packed_value_set_unsigned_int(), and AZ_TYPE_UINT32.
Referenced by attrib_dict_impl_init().
attrd_get_key()
static const AZImplementation * attrd_get_key (const AZMapImplementation * map_impl, void * map_inst, const AZPackedValue * iter, AZValue * val, unsigned int size) static
References az_list_get_element().
Referenced by attrib_dict_impl_init().
attrd_get_key_type()
static unsigned int attrd_get_key_type (const AZMapImplementation * map_impl, void * map_inst) static
References AZ_TYPE_STRING.
Referenced by attrib_dict_impl_init().
attrd_get_keys()
const AZCollectionImplementation * attrd_get_keys (const AZMapImplementation * map_impl, void * map_inst, void ** inst)
Referenced by attrib_dict_impl_init().
attrd_iterator_next()
static unsigned int attrd_iterator_next (const AZCollectionImplementation * coll_impl, void * coll_inst, AZPackedValue * iter) static
References az_collection_get_size().
Referenced by attrib_dict_impl_init().
attrd_keys_get_element_type()
static unsigned int attrd_keys_get_element_type (const AZCollectionImplementation * coll_impl, void * coll_inst) static
References AZ_TYPE_STRING.
Referenced by attrib_dict_impl_init().
attrd_keys_get_size()
static unsigned int attrd_keys_get_size (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by attrib_dict_impl_init().
attrd_lookup()
const AZImplementation * attrd_lookup (const AZMapImplementation * map_impl, void * map_inst, const AZImplementation * key_impl, void * key_inst, AZValue * val, unsigned int size)
References AZ_IMPL_TYPE, and AZ_TYPE_STRING.
Referenced by attrib_dict_impl_init().
attrd_val_contains()
static unsigned int attrd_val_contains (const AZCollectionImplementation * coll_impl, void * coll_inst, const AZImplementation * impl, const void * inst) static
Referenced by attrib_dict_impl_init().
attrd_val_element_type()
static unsigned int attrd_val_element_type (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by attrib_dict_impl_init().
attrd_val_get_size()
static unsigned int attrd_val_get_size (const AZCollectionImplementation * coll_impl, void * coll_inst) static
Referenced by attrib_dict_impl_init().
attrib_dict_class_init()
static void attrib_dict_class_init (AZAttribDictClass * klass) static
attrib_dict_impl_init()
static void attrib_dict_impl_init (AZAttribDictImplementation * impl) static
References attrd_get_element(), attrd_get_element_type(), attrd_get_iterator(), attrd_get_key(), attrd_get_key_type(), attrd_get_keys(), attrd_iterator_next(), attrd_keys_get_element_type(), attrd_keys_get_size(), attrd_lookup(), attrd_val_contains(), attrd_val_element_type(), attrd_val_get_size(), az_implementation_init_by_type(), and AZ_TYPE_LIST.
Referenced by az_attrib_dict_get_type().
az_attrib_dict_get_type()
unsigned int az_attrib_dict_get_type (void)
References attrib_dict_class, attrib_dict_impl_init(), attrib_dict_type, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), and AZ_TYPE_LIST.
az_attrib_dict_lookup()
const AZImplementation * az_attrib_dict_lookup (const AZAttribDictImplementation * attrd_impl, void * attrd_inst, const AZString * key, AZValue64 * val, unsigned int * flags)
Referenced by az_active_object_get_attribute().
az_attrib_dict_set()
unsigned int az_attrib_dict_set (const AZAttribDictImplementation * attrd_impl, void * attrd_inst, AZString * key, const AZImplementation * impl, void * inst, unsigned int flags)
Referenced by az_active_object_set_attribute().
Variable Documentation
attrib_dict_class
AZAttribDictClass* attrib_dict_class static
Referenced by az_attrib_dict_get_type().
attrib_dict_type
unsigned int attrib_dict_type = 0 static
Referenced by az_attrib_dict_get_type().