az: az.h File Reference
az.h File Reference
#include <az/config.h>
Macros
#define AZ_NUM_FUNDAMENTAL_TYPES (AZ_TYPE_IDX_BLOCK + 1)
#define AZ_NUM_BASE_TYPES (AZ_TYPE_IDX_OBJECT + 1)
#define AZ_TYPE_IS_ARITHMETIC(t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_INT8) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_COMPLEX_DOUBLE))
#define AZ_TYPE_IS_INTEGRAL(t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_INT8) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_UINT64))
#define AZ_TYPE_IS_SIGNED(t) (((t) == AZ_TYPE_INT8) || ((t) == AZ_TYPE_INT16) || ((t) == AZ_TYPE_INT32) || ((t) == AZ_TYPE_INT64) || ((t) == AZ_TYPE_FLOAT) || ((t) == AZ_TYPE_DOUBLE) || ((t) == AZ_TYPE_COMPLEX_FLOAT) || ((t) == AZ_TYPE_COMPLEX_DOUBLE))
#define AZ_TYPE_IS_UNSIGNED(t) (((t) == AZ_TYPE_UINT8) || ((t) == AZ_TYPE_UINT16) || ((t) == AZ_TYPE_UINT32) || ((t) == AZ_TYPE_UINT64))
#define AZ_TYPE_IS_PRIMITIVE(t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_BOOLEAN) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_POINTER))
#define AZ_TYPE_IS_BASE(t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_ANY) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_OBJECT))
Typedefs
typedef struct _AZFunctionInstance AZFunctionInstance
typedef struct _AZOutputStream AZOutputStream
typedef struct _AZInputStream AZInputStream
typedef struct _AZContext AZContext
Enumerations
enum AZErrorCode { AZ_OK = 0 , AZ_NOT_IMPLEMENTED = -1 , AZ_OUT_OF_MEMORY = -2 , AZ_IO_ERROR = -3 }
Error codes.
enum AZTypeFlags {
AZ_FLAG_BLOCK = 0x01000000 , AZ_FLAG_INTERFACE = 0x02000000 , AZ_FLAG_REFERENCE = 0x04000000 , AZ_FLAG_BOXED = 0x08000000 ,
AZ_FLAG_OBJECT = 0x10000000 , AZ_FLAG_FINAL = 0x20000000 , AZ_FLAG_ABSTRACT = 0x40000000 , AZ_FLAG_CONSTRUCT = 0x80000000
}
Type flags.
enum AZImplementationFlags {
AZ_FLAG_IMPL_IS_CLASS = 0x01 , AZ_FLAG_ZERO_MEMORY = 0x04 , AZ_FLAG_ARITHMETIC = 0x100 , AZ_FLAG_INTEGRAL = 0x200 ,
AZ_FLAG_SIGNED = 0x400
}
Implementation/Class flags.
enum AZTypeIdx {
AZ_TYPE_IDX_NONE , AZ_TYPE_IDX_ANY , AZ_TYPE_IDX_BOOLEAN , AZ_TYPE_IDX_INT8 ,
AZ_TYPE_IDX_UINT8 , AZ_TYPE_IDX_INT16 , AZ_TYPE_IDX_UINT16 , AZ_TYPE_IDX_INT32 ,
AZ_TYPE_IDX_UINT32 , AZ_TYPE_IDX_INT64 , AZ_TYPE_IDX_UINT64 , AZ_TYPE_IDX_FLOAT ,
AZ_TYPE_IDX_DOUBLE , AZ_TYPE_IDX_COMPLEX_FLOAT , AZ_TYPE_IDX_COMPLEX_DOUBLE , AZ_TYPE_IDX_POINTER ,
AZ_TYPE_IDX_STRUCT , AZ_TYPE_IDX_BLOCK , AZ_TYPE_IDX_IMPLEMENTATION , AZ_TYPE_IDX_CLASS ,
AZ_TYPE_IDX_INTERFACE , AZ_TYPE_IDX_FIELD , AZ_TYPE_IDX_FUNCTION_SIGNATURE , AZ_TYPE_IDX_FUNCTION ,
AZ_TYPE_IDX_REFERENCE , AZ_TYPE_IDX_STRING , AZ_TYPE_IDX_BOXED_VALUE , AZ_TYPE_IDX_BOXED_INTERFACE ,
AZ_TYPE_IDX_PACKED_VALUE , AZ_TYPE_IDX_OBJECT , AZ_TYPE_IDX_INPUT_STREAM , AZ_TYPE_IDX_OUTPUT_STREAM
}
Predefined type indices.
enum AZType {
AZ_TYPE_NONE = AZ_TYPE_IDX_NONE , AZ_TYPE_ANY = AZ_TYPE_IDX_ANY | AZ_FLAG_ABSTRACT , AZ_TYPE_BOOLEAN = AZ_TYPE_IDX_BOOLEAN | AZ_FLAG_FINAL , AZ_TYPE_INT8 = AZ_TYPE_IDX_INT8 | AZ_FLAG_FINAL ,
AZ_TYPE_UINT8 = AZ_TYPE_IDX_UINT8 | AZ_FLAG_FINAL , AZ_TYPE_INT16 = AZ_TYPE_IDX_INT16 | AZ_FLAG_FINAL , AZ_TYPE_UINT16 = AZ_TYPE_IDX_UINT16 | AZ_FLAG_FINAL , AZ_TYPE_INT32 = AZ_TYPE_IDX_INT32 | AZ_FLAG_FINAL ,
AZ_TYPE_UINT32 = AZ_TYPE_IDX_UINT32 | AZ_FLAG_FINAL , AZ_TYPE_INT64 = AZ_TYPE_IDX_INT64 | AZ_FLAG_FINAL , AZ_TYPE_UINT64 = AZ_TYPE_IDX_UINT64 | AZ_FLAG_FINAL , AZ_TYPE_FLOAT = AZ_TYPE_IDX_FLOAT | AZ_FLAG_FINAL ,
AZ_TYPE_DOUBLE = AZ_TYPE_IDX_DOUBLE | AZ_FLAG_FINAL , AZ_TYPE_COMPLEX_FLOAT = AZ_TYPE_IDX_COMPLEX_FLOAT | AZ_FLAG_FINAL , AZ_TYPE_COMPLEX_DOUBLE = AZ_TYPE_IDX_COMPLEX_DOUBLE | AZ_FLAG_FINAL , AZ_TYPE_POINTER = AZ_TYPE_IDX_POINTER | AZ_FLAG_FINAL ,
AZ_TYPE_STRUCT = AZ_TYPE_IDX_STRUCT | AZ_FLAG_ABSTRACT , AZ_TYPE_BLOCK = AZ_TYPE_IDX_BLOCK | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT , AZ_TYPE_IMPLEMENTATION = AZ_TYPE_IDX_IMPLEMENTATION | AZ_FLAG_BLOCK , AZ_TYPE_CLASS = AZ_TYPE_IDX_CLASS | AZ_FLAG_BLOCK | AZ_FLAG_FINAL ,
AZ_TYPE_INTERFACE = AZ_TYPE_IDX_INTERFACE | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE , AZ_TYPE_FIELD = AZ_TYPE_IDX_FIELD | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_FUNCTION_SIGNATURE = AZ_TYPE_IDX_FUNCTION_SIGNATURE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_FUNCTION = AZ_TYPE_IDX_FUNCTION | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE ,
AZ_TYPE_REFERENCE = AZ_TYPE_IDX_REFERENCE | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_REFERENCE , AZ_TYPE_STRING = AZ_TYPE_IDX_STRING | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE , AZ_TYPE_BOXED_VALUE = AZ_TYPE_IDX_BOXED_VALUE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED , AZ_TYPE_BOXED_INTERFACE = AZ_TYPE_IDX_BOXED_INTERFACE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED ,
AZ_TYPE_PACKED_VALUE = AZ_TYPE_IDX_PACKED_VALUE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_OBJECT = AZ_TYPE_IDX_OBJECT | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_REFERENCE | AZ_FLAG_OBJECT , AZ_TYPE_INPUT_STREAM = AZ_TYPE_IDX_INPUT_STREAM | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE , AZ_TYPE_OUTPUT_STREAM = AZ_TYPE_IDX_OUTPUT_STREAM | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE
}
Predefined typecodes.
Functions
void az_init (void)
Initialize type system.
Macro Definition Documentation
AZ_NUM_BASE_TYPES
#define AZ_NUM_BASE_TYPES (AZ_TYPE_IDX_OBJECT + 1)
AZ_NUM_FUNDAMENTAL_TYPES
#define AZ_NUM_FUNDAMENTAL_TYPES (AZ_TYPE_IDX_BLOCK + 1)
AZ_TYPE_IS_ARITHMETIC
#define AZ_TYPE_IS_ARITHMETIC (t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_INT8) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_COMPLEX_DOUBLE))
AZ_TYPE_IS_BASE
#define AZ_TYPE_IS_BASE (t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_ANY) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_OBJECT))
AZ_TYPE_IS_INTEGRAL
#define AZ_TYPE_IS_INTEGRAL (t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_INT8) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_UINT64))
AZ_TYPE_IS_PRIMITIVE
#define AZ_TYPE_IS_PRIMITIVE (t) ((AZ_TYPE_INDEX(t) >= AZ_TYPE_IDX_BOOLEAN) && (AZ_TYPE_INDEX(t) <= AZ_TYPE_IDX_POINTER))
AZ_TYPE_IS_SIGNED
#define AZ_TYPE_IS_SIGNED (t) (((t) == AZ_TYPE_INT8) || ((t) == AZ_TYPE_INT16) || ((t) == AZ_TYPE_INT32) || ((t) == AZ_TYPE_INT64) || ((t) == AZ_TYPE_FLOAT) || ((t) == AZ_TYPE_DOUBLE) || ((t) == AZ_TYPE_COMPLEX_FLOAT) || ((t) == AZ_TYPE_COMPLEX_DOUBLE))
AZ_TYPE_IS_UNSIGNED
#define AZ_TYPE_IS_UNSIGNED (t) (((t) == AZ_TYPE_UINT8) || ((t) == AZ_TYPE_UINT16) || ((t) == AZ_TYPE_UINT32) || ((t) == AZ_TYPE_UINT64))
Typedef Documentation
AZContext
typedef struct _AZContext AZContext
AZFunctionInstance
typedef struct _AZFunctionInstance AZFunctionInstance
AZInputStream
typedef struct _AZInputStream AZInputStream
AZOutputStream
typedef struct _AZOutputStream AZOutputStream
Enumeration Type Documentation
AZErrorCode
enum AZErrorCode
Error codes.
Enumerator
AZ_OK
Success.
AZ_NOT_IMPLEMENTED
Function is not supported by given class.
AZ_OUT_OF_MEMORY
Memory allocation returned NULL.
AZ_IO_ERROR
Generic IO error.
Function Documentation
az_init()
void az_init (void)
Initialize type system.
If AZ_SAFETY_CHECKS is set during the compilation of the library, it is called automatically in AZ_GLOBALS_STATIC and AZ_GLOBALS_SINGLE_THREAD modes whenever any method involving types is called.
It is safe to call it more than once
References az_globals_init(), az_init_base_classes(), az_init_boxed_interface_class(), az_init_boxed_value_class(), az_init_field_class(), az_init_function_classes(), az_init_input_stream_class(), az_init_interface_class(), az_init_object_class(), az_init_output_stream_class(), az_init_packed_value_class(), az_init_primitive_classes(), az_init_reference_class(), az_init_string_class(), az_post_init_base_classes(), and az_post_init_primitive_classes().