az: boxed-value.h File Reference
boxed-value.h File Reference
#include <stdint.h>
#include <az/boxed-interface.h>
#include <az/reference.h>
#include <az/packed-value.h>
Data Structures
struct AZBoxedValue
Macros
#define AZ_BOXED_VALUE_CLASS (&AZBoxedValueKlass)
#define AZ_BOXED_VALUE_IMPL ((AZImplementation *) &AZBoxedValueKlass)
Functions
AZBoxedValue * az_boxed_value_new (const AZClass *klass, void *inst)
AZBoxedValue * az_boxed_value_new_from_val (const AZClass *klass, const AZValue *val)
static const AZImplementation * az_boxed_value_unbox (AZValue *dst, AZBoxedValue *boxed)
ARIKKEI_INLINE void az_boxed_value_ref (AZBoxedValue *boxed)
ARIKKEI_INLINE void az_boxed_value_unref (AZBoxedValue *boxed)
static const AZImplementation * az_value_transfer_autobox (const AZImplementation *impl, AZValue *dst, AZValue *src, unsigned int size)
tranfer a value from one handle to another, boxing/unboxing if needed
static const AZImplementation * az_value_copy_autobox (const AZImplementation *impl, AZValue *dst, const AZValue *src, unsigned int size)
copy a value from one handle to another, boxing/unboxing if needed
static const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation *impl, AZValue *dst, void *inst, unsigned int size)
set value from instance, boxing if needed
static const AZImplementation * az_value_get_inst_autobox (const AZImplementation *impl, const AZValue *val, void **inst)
get the instance from value, unboxing if needed
unsigned int az_value_equals_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const AZValue *rhs)
unsigned int az_value_equals_instance_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const void *rhs)
Variables
AZBoxedValueClass AZBoxedValueKlass
Macro Definition Documentation
AZ_BOXED_VALUE_CLASS
#define AZ_BOXED_VALUE_CLASS (&AZBoxedValueKlass)
AZ_BOXED_VALUE_IMPL
#define AZ_BOXED_VALUE_IMPL ((AZImplementation *) &AZBoxedValueKlass)
Function Documentation
az_boxed_value_new()
AZBoxedValue * az_boxed_value_new (const AZClass * klass, void * inst)
References AZ_CLASS_IS_VALUE, az_instance_init_by_type(), AZ_TYPE_BOXED_VALUE, and az_value_set_from_inst().
Referenced by az_value_set_from_inst_autobox().
az_boxed_value_new_from_val()
AZBoxedValue * az_boxed_value_new_from_val (const AZClass * klass, const AZValue * val)
References AZ_CLASS_IS_VALUE, az_instance_init_by_type(), AZ_TYPE_BOXED_VALUE, and az_value_copy().
Referenced by az_value_copy_autobox(), and az_value_transfer_autobox().
az_boxed_value_ref()
ARIKKEI_INLINE void az_boxed_value_ref (AZBoxedValue * boxed)
References az_reference_ref().
az_boxed_value_unbox()
static const AZImplementation * az_boxed_value_unbox (AZValue * dst, AZBoxedValue * boxed) inline static
References az_value_copy().
az_boxed_value_unref()
ARIKKEI_INLINE void az_boxed_value_unref (AZBoxedValue * boxed)
References az_reference_unref(), and AZBoxedValueKlass.
az_value_copy_autobox()
static const AZImplementation * az_value_copy_autobox (const AZImplementation * impl, AZValue * dst, const AZValue * src, unsigned int size) inline static
copy a value from one handle to another, boxing/unboxing if needed
If the source does not fit into size bytes AZBoxedValue is created in dst. If src is AZBoxedValue but the value fits into dst the actual value is copied.
Parameters
impl the src implemntation
dst the destination value
src the source value
size the size of destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_copy(), and AZBoxedValueKlass.
Referenced by aobj_aa_get_element(), aobj_aa_map_lookup(), aobj_attrd_lookup(), array_get_element(), array_list_get_element(), array_object_get_element(), packed_value_array_get_element(), and value_array_get_element().
az_value_equals_autobox()
unsigned int az_value_equals_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const AZValue * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
az_value_equals_instance_autobox()
unsigned int az_value_equals_instance_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const void * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
Referenced by array_contains(), array_list_contains(), and array_object_contains().
az_value_get_inst_autobox()
static const AZImplementation * az_value_get_inst_autobox (const AZImplementation * impl, const AZValue * val, void ** inst) inline static
get the instance from value, unboxing if needed
If the value is AZBoxedValue, return the actual implementation and instance inside it.
Parameters
impl the type implementation
val the source value
inst the destination instance
Returns
the actual implementation (may be changed by unboxing)
References AZ_IMPL_IS_BLOCK, and AZBoxedValueKlass.
az_value_set_from_inst_autobox()
static const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation * impl, AZValue * dst, void * inst, unsigned int size) inline static
set value from instance, boxing if needed
If the value does not fit into size bytes AZBoxedValue is created in dst. It does not unbox automatically.
Parameters
impl the type implemntation
dst the destination value
inst the source instance
size the size of destination value
Returns
the dst implementation (may be changed by boxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and az_value_set_from_inst().
Referenced by az_array_list_append(), az_array_list_insert(), and az_array_list_set_element().
az_value_transfer_autobox()
static const AZImplementation * az_value_transfer_autobox (const AZImplementation * impl, AZValue * dst, AZValue * src, unsigned int size) inline static
tranfer a value from one handle to another, boxing/unboxing if needed
If the source does not fit into size bytes AZBoxedValue is created in dst. If src is AZBoxedValue but the value fits into dst the actual value is copied. After the transfer src will be in uninitialized state.
Parameters
impl the src implemntation
dst the destination value
src the source value
size the size of destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_clear(), az_value_copy(), az_value_transfer(), and AZBoxedValueKlass.
Variable Documentation
AZBoxedValueKlass
AZBoxedValueClass AZBoxedValueKlass extern
Referenced by az_boxed_value_unref(), az_init_boxed_value_class(), az_value_copy_autobox(), az_value_equals_autobox(), az_value_equals_instance_autobox(), az_value_get_inst_autobox(), and az_value_transfer_autobox().