az: boxed-interface.c File Reference
boxed-interface.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <arikkei/arikkei-strlib.h>
#include <arikkei/arikkei-utils.h>
#include <az/boxed-interface.h>
#include <az/boxed-value.h>
#include <az/instance.h>
#include <az/class.h>
#include <az/object.h>
#include <az/private.h>
#include <az/serialization.h>
Macros
#define __AZ_BOXED_INTERFACE_C__
Functions
static unsigned int serialize_boxed_interface (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int boxed_interface_to_string (const AZImplementation *impl, void *inst, unsigned char *buf, unsigned int len)
void az_init_boxed_interface_class (void)
AZBoxedInterface * az_boxed_interface_new (const AZImplementation *impl, void *inst, const AZImplementation *if_impl, void *if_inst)
AZBoxedInterface * az_boxed_interface_new_from_impl_value (const AZImplementation *impl, const AZValue *val, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_impl_value_autobox (const AZImplementation *impl, const AZValue *val, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_impl_instance (const AZImplementation *impl, void *inst, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_object (AZObject *obj, unsigned int type)
Variables
AZBoxedInterfaceClass AZBoxedInterfaceKlass
Macro Definition Documentation
__AZ_BOXED_INTERFACE_C__
#define __AZ_BOXED_INTERFACE_C__
Function Documentation
az_boxed_interface_new()
AZBoxedInterface * az_boxed_interface_new (const AZImplementation * impl, void * inst, const AZImplementation * if_impl, void * if_inst)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_IMPL_TYPE, az_instance_init(), az_packed_value_set(), AZ_TYPE_IS_VALUE, and AZBoxedInterfaceKlass.
Referenced by az_boxed_interface_new_from_object().
az_boxed_interface_new_from_impl_instance()
AZBoxedInterface * az_boxed_interface_new_from_impl_instance (const AZImplementation * impl, void * inst, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set(), az_value_get_inst(), and AZBoxedInterfaceKlass.
Referenced by az_value_set_interface_autobox().
az_boxed_interface_new_from_impl_value()
AZBoxedInterface * az_boxed_interface_new_from_impl_value (const AZImplementation * impl, const AZValue * val, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set_from_val(), az_value_get_inst(), and AZBoxedInterfaceKlass.
Referenced by az_value_convert_auto(), and az_value_convert_in_place().
az_boxed_interface_new_from_impl_value_autobox()
AZBoxedInterface * az_boxed_interface_new_from_impl_value_autobox (const AZImplementation * impl, const AZValue * val, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set_from_val(), az_value_get_inst(), AZBoxedInterfaceKlass, and AZBoxedValueKlass.
az_boxed_interface_new_from_object()
AZBoxedInterface * az_boxed_interface_new_from_object (AZObject * obj, unsigned int type)
References az_boxed_interface_new(), and az_object_get_interface().
az_init_boxed_interface_class()
void az_init_boxed_interface_class (void)
References az_class_new_with_value(), and AZBoxedInterfaceKlass.
Referenced by az_init().
boxed_interface_to_string()
static unsigned int boxed_interface_to_string (const AZImplementation * impl, void * inst, unsigned char * buf, unsigned int len) static
References AZ_CLASS_FROM_IMPL.
serialize_boxed_interface()
static unsigned int serialize_boxed_interface (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_instance_serialize().
Variable Documentation
AZBoxedInterfaceKlass
AZBoxedInterfaceClass AZBoxedInterfaceKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_CONSTRUCT | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_BOXED_INTERFACE},
    &AZReferenceKlass.klass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "boxed interface",
    7, sizeof(AZBoxedInterfaceClass), 0,
    NULL,
    NULL, NULL,
    serialize_boxed_interface, NULL, boxed_interface_to_string,
    NULL, NULL},
    NULL, NULL
}
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_boxed_interface_unref(), and az_init_boxed_interface_class().