az: boxed-value.c File Reference
boxed-value.c File Reference
#include <arikkei/arikkei-strlib.h>
#include <az/boxed-value.h>
#include <az/instance.h>
#include <az/private.h>
Macros
#define __AZ_BOXED_VALUE_C__
#define DEBUG_BOXED_VALUE
Functions
static unsigned int serialize_boxed_value (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int boxed_value_to_string (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen)
static void boxed_value_init (AZBoxedValueClass *klass, AZBoxedValue *boxed)
static void boxed_value_finalize (AZBoxedValueClass *klass, AZBoxedValue *boxed)
void az_init_boxed_value_class (void)
AZBoxedValue * az_boxed_value_new (const AZClass *klass)
AZBoxedValue * az_boxed_value_new_from_inst (const AZClass *klass, void *inst)
AZBoxedValue * az_boxed_value_new_from_val (const AZClass *klass, const AZValue *val)
const AZImplementation * az_value_init_autobox (const AZImplementation *impl, AZValue *dst, unsigned int size)
const AZImplementation * az_value_transfer_autobox (const AZImplementation *impl, AZValue *dst, AZValue *src, unsigned int size)
tranfer a value to a new location, boxing/unboxing if needed
const AZImplementation * az_value_copy_autobox (const AZImplementation *impl, AZValue *dst, const AZValue *src, unsigned int size)
copy a value from one handle to another, boxing/unboxing if needed
const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation *impl, AZValue *dst, void *inst, unsigned int size)
set value from instance, boxing if needed
const AZImplementation * az_value_get_inst_autobox (const AZImplementation *impl, const AZValue *val, void **inst)
ereference instance from value, unboxing if needed
unsigned int az_value_equals_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const AZValue *rhs)
unsigned int az_value_equals_instance_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const void *rhs)
Variables
AZBoxedValueClass AZBoxedValueKlass
Macro Definition Documentation
__AZ_BOXED_VALUE_C__
#define __AZ_BOXED_VALUE_C__
DEBUG_BOXED_VALUE
#define DEBUG_BOXED_VALUE
Function Documentation
az_boxed_value_new()
AZBoxedValue * az_boxed_value_new (const AZClass * klass)
References AZ_CLASS_IS_VALUE, az_instance_init(), az_instance_init_by_type(), and AZ_TYPE_BOXED_VALUE.
az_boxed_value_new_from_inst()
AZBoxedValue * az_boxed_value_new_from_inst (const AZClass * klass, void * inst)
References AZ_CLASS_IS_VALUE, az_instance_init_by_type(), AZ_TYPE_BOXED_VALUE, and az_value_set_from_inst().
Referenced by az_value_set_from_inst_autobox().
az_boxed_value_new_from_val()
AZBoxedValue * az_boxed_value_new_from_val (const AZClass * klass, const AZValue * val)
References AZ_CLASS_IS_VALUE, az_instance_init_by_type(), AZ_TYPE_BOXED_VALUE, and az_value_copy().
Referenced by az_value_copy_autobox(), az_value_init_autobox(), and az_value_transfer_autobox().
az_init_boxed_value_class()
void az_init_boxed_value_class (void)
References az_class_new_with_value(), and AZBoxedValueKlass.
Referenced by az_init().
az_value_copy_autobox()
const AZImplementation * az_value_copy_autobox (const AZImplementation * impl, AZValue * dst, const AZValue * src, unsigned int size)
copy a value from one handle to another, boxing/unboxing if needed
Copy data from initialized src to uninitialized dst. After the operation src will reamin intact. If the source does not fit into size bytes AZBoxedValue is created in dst. If src is AZBoxedValue but the value fits into dst the actual value is copied.
Parameters
impl the src implemntation
dst the destination (uninitialized)
src the source value
size the size of the destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_copy(), and AZBoxedValueKlass.
Referenced by aobj_aa_get_element(), aobj_aa_map_lookup(), aobj_attrd_lookup(), array_get_element(), array_list_get_element(), array_object_get_element(), az_value_set_from_packed_value_autobox(), packed_value_array_get_element(), and value_array_get_element().
az_value_equals_autobox()
unsigned int az_value_equals_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const AZValue * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
az_value_equals_instance_autobox()
unsigned int az_value_equals_instance_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const void * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
Referenced by array_contains(), array_list_contains(), and array_object_contains().
az_value_get_inst_autobox()
const AZImplementation * az_value_get_inst_autobox (const AZImplementation * impl, const AZValue * val, void ** inst)
ereference instance from value, unboxing if needed
If the value is AZBoxedValue, return the actual implementation and instance inside it.
Parameters
impl the type implementation
val the source value
inst the result instance
Returns
the actual implementation (may be changed by unboxing)
References AZ_IMPL_IS_BLOCK, and AZBoxedValueKlass.
Referenced by az_packed_value_get_inst_autobox().
az_value_init_autobox()
const AZImplementation * az_value_init_autobox (const AZImplementation * impl, AZValue * dst, unsigned int size)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and az_instance_init().
Referenced by az_packed_value_64_init_autobox(), and az_packed_value_init_autobox().
az_value_set_from_inst_autobox()
const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation * impl, AZValue * dst, void * inst, unsigned int size)
set value from instance, boxing if needed
If the value does not fit into size bytes, AZBoxedValue is created at dst. It does not unbox automatically.
Parameters
impl the type implemntation
dst the destination (uninitialized)
inst the source instance
size the size of the destination value
Returns
the dst implementation (may be changed by boxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_inst(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and az_value_set_from_inst().
Referenced by az_array_list_append(), az_array_list_insert(), az_array_list_set_element(), az_packed_value_64_set_autobox(), and az_packed_value_set_autobox().
az_value_transfer_autobox()
const AZImplementation * az_value_transfer_autobox (const AZImplementation * impl, AZValue * dst, AZValue * src, unsigned int size)
tranfer a value to a new location, boxing/unboxing if needed
If the src value does not fit into size bytes, AZBoxedValue is created at dst. If the src is an AZBoxedValue but the value fits into dst, the actual value is unboxed to dst. After the transfer src will be in uninitialized state.
Parameters
impl the src implemntation
dst the destination (uninitialized)
src the source value
size the size of the destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_clear(), az_value_copy(), az_value_transfer(), and AZBoxedValueKlass.
boxed_value_finalize()
static void boxed_value_finalize (AZBoxedValueClass * klass, AZBoxedValue * boxed) static
boxed_value_init()
static void boxed_value_init (AZBoxedValueClass * klass, AZBoxedValue * boxed) static
boxed_value_to_string()
static unsigned int boxed_value_to_string (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen) static
References az_instance_to_string().
serialize_boxed_value()
static unsigned int serialize_boxed_value (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_instance_serialize().
Variable Documentation
AZBoxedValueKlass
AZBoxedValueClass AZBoxedValueKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_CONSTRUCT | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_BOXED_VALUE},
    &AZReferenceKlass.klass,
    0, 0, 0, 0,
    {0},
    NULL,
    (const uint8_t *) "boxed value",
    7, sizeof(AZBoxedValueClass), 0,
    NULL,
    (void (*) (const AZImplementation *, void *)) boxed_value_init, (void (*) (const AZImplementation *, void *)) boxed_value_finalize,
    serialize_boxed_value, NULL, boxed_value_to_string,
    NULL, NULL},
    NULL, NULL
}
Referenced by az_boxed_interface_new_from_impl_value_autobox(), az_boxed_value_unref(), az_init_boxed_value_class(), az_value_copy_autobox(), az_value_equals_autobox(), az_value_equals_instance_autobox(), az_value_get_inst_autobox(), and az_value_transfer_autobox().