az: boxed-interface.h File Reference
boxed-interface.h File Reference
#include <stdint.h>
#include <az/reference.h>
#include <az/packed-value.h>
Data Structures
struct AZBoxedInterface
Macros
#define AZ_BOXED_INTERFACE_CLASS (&AZBoxedInterfaceKlass)
#define AZ_BOXED_INTERFACE_IMPL ((AZImplementation *) &AZBoxedInterfaceKlass)
Functions
AZBoxedInterface * az_boxed_interface_new (const AZImplementation *impl, void *inst, const AZImplementation *if_impl, void *if_inst)
AZBoxedInterface * az_boxed_interface_new_from_impl_value (const AZImplementation *impl, const AZValue *val, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_impl_value_autobox (const AZImplementation *impl, const AZValue *val, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_impl_instance (const AZImplementation *impl, void *inst, unsigned int type)
AZBoxedInterface * az_boxed_interface_new_from_object (AZObject *obj, unsigned int type)
ARIKKEI_INLINE void az_boxed_interface_ref (AZBoxedInterface *astr)
ARIKKEI_INLINE void az_boxed_interface_unref (AZBoxedInterface *astr)
static const AZImplementation * az_value_set_interface_autobox (const AZImplementation *impl, AZValue *dst, void *inst, unsigned int type)
ARIKKEI_INLINE void az_boxed_interface_unbox (const AZImplementation **impl, void **inst)
Variables
AZBoxedInterfaceClass AZBoxedInterfaceKlass
Macro Definition Documentation
AZ_BOXED_INTERFACE_CLASS
#define AZ_BOXED_INTERFACE_CLASS (&AZBoxedInterfaceKlass)
AZ_BOXED_INTERFACE_IMPL
#define AZ_BOXED_INTERFACE_IMPL ((AZImplementation *) &AZBoxedInterfaceKlass)
Function Documentation
az_boxed_interface_new()
AZBoxedInterface * az_boxed_interface_new (const AZImplementation * impl, void * inst, const AZImplementation * if_impl, void * if_inst)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_IMPL_TYPE, az_instance_init(), az_packed_value_set(), AZ_TYPE_IS_VALUE, and AZBoxedInterfaceKlass.
Referenced by az_boxed_interface_new_from_object().
az_boxed_interface_new_from_impl_instance()
AZBoxedInterface * az_boxed_interface_new_from_impl_instance (const AZImplementation * impl, void * inst, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set(), az_value_get_inst(), and AZBoxedInterfaceKlass.
Referenced by az_value_set_interface_autobox().
az_boxed_interface_new_from_impl_value()
AZBoxedInterface * az_boxed_interface_new_from_impl_value (const AZImplementation * impl, const AZValue * val, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set_from_val(), az_value_get_inst(), and AZBoxedInterfaceKlass.
Referenced by az_value_convert_auto(), and az_value_convert_in_place().
az_boxed_interface_new_from_impl_value_autobox()
AZBoxedInterface * az_boxed_interface_new_from_impl_value_autobox (const AZImplementation * impl, const AZValue * val, unsigned int type)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), az_instance_get_interface(), az_instance_init(), az_packed_value_set_from_val(), az_value_get_inst(), AZBoxedInterfaceKlass, and AZBoxedValueKlass.
az_boxed_interface_new_from_object()
AZBoxedInterface * az_boxed_interface_new_from_object (AZObject * obj, unsigned int type)
References az_boxed_interface_new(), and az_object_get_interface().
az_boxed_interface_ref()
ARIKKEI_INLINE void az_boxed_interface_ref (AZBoxedInterface * astr)
References az_reference_ref().
az_boxed_interface_unbox()
ARIKKEI_INLINE void az_boxed_interface_unbox (const AZImplementation ** impl, void ** inst)
az_boxed_interface_unref()
ARIKKEI_INLINE void az_boxed_interface_unref (AZBoxedInterface * astr)
References az_reference_unref(), and AZBoxedInterfaceKlass.
az_value_set_interface_autobox()
static const AZImplementation * az_value_set_interface_autobox (const AZImplementation * impl, AZValue * dst, void * inst, unsigned int type) inline static
References AZ_BOXED_INTERFACE_IMPL, az_boxed_interface_new_from_impl_instance(), and az_value_transfer_reference().
Variable Documentation
AZBoxedInterfaceKlass
AZBoxedInterfaceClass AZBoxedInterfaceKlass extern
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_boxed_interface_unref(), and az_init_boxed_interface_class().