az: buffer-output-stream.c File Reference
buffer-output-stream.c File Reference
#include <stdlib.h>
#include <az/extend.h>
#include <az/types.h>
#include <az/io/buffer-output-stream.h>
Macros
#define __AZ_BUFFER_OUTPUT_STREAM_C__
Functions
static void bostream_class_init (AZBufferOutputStreamClass *klass)
static int64_t bostream_write (const AZOutputStreamImplementation *impl, AZOutputStream *inst, const void *data, uint64_t size)
static int64_t bostream_close (const AZOutputStreamImplementation *impl, AZOutputStream *inst)
unsigned int az_buffer_output_stream_get_type (void)
Variables
unsigned int bostream_type = 0
AZBufferOutputStreamClass * bostream_class = NULL
Macro Definition Documentation
__AZ_BUFFER_OUTPUT_STREAM_C__
#define __AZ_BUFFER_OUTPUT_STREAM_C__
Function Documentation
az_buffer_output_stream_get_type()
unsigned int az_buffer_output_stream_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_STRUCT, bostream_class, bostream_class_init(), and bostream_type.
bostream_class_init()
static void bostream_class_init (AZBufferOutputStreamClass * klass) static
References az_class_declare_interface(), AZ_TYPE_OUTPUT_STREAM, bostream_close(), and bostream_write().
Referenced by az_buffer_output_stream_get_type().
bostream_close()
static int64_t bostream_close (const AZOutputStreamImplementation * impl, AZOutputStream * inst) static
References AZ_OK.
Referenced by bostream_class_init().
bostream_write()
static int64_t bostream_write (const AZOutputStreamImplementation * impl, AZOutputStream * inst, const void * data, uint64_t size) static
Referenced by bostream_class_init().
Variable Documentation
bostream_class
AZBufferOutputStreamClass* bostream_class = NULL
Referenced by az_buffer_output_stream_get_type().
bostream_type
unsigned int bostream_type = 0
Referenced by az_buffer_output_stream_get_type().