az: buffer-input-stream.c File Reference
buffer-input-stream.c File Reference
#include <stdlib.h>
#include <string.h>
#include <az/extend.h>
#include <az/types.h>
#include <az/io/buffer-input-stream.h>
Macros
#define __AZ_BUFFER_INPUT_STREAM_C__
Functions
static void bistream_class_init (AZBufferInputStreamClass *klass)
static int64_t bistream_read (const AZInputStreamImplementation *impl, AZInputStream *inst, void *data, uint64_t size)
static int64_t bistream_seek (const AZInputStreamImplementation *impl, AZInputStream *inst, uint64_t offset)
static int64_t bistream_skip (const AZInputStreamImplementation *impl, AZInputStream *inst, uint64_t n_bytes)
static int bistream_is_eof (const AZInputStreamImplementation *impl, AZInputStream *inst)
static int bistream_is_error (const AZInputStreamImplementation *impl, AZInputStream *inst)
unsigned int az_buffer_input_stream_get_type (void)
Variables
unsigned int bistream_type = 0
AZBufferInputStreamClass * bistream_class = NULL
Macro Definition Documentation
__AZ_BUFFER_INPUT_STREAM_C__
#define __AZ_BUFFER_INPUT_STREAM_C__
Function Documentation
az_buffer_input_stream_get_type()
unsigned int az_buffer_input_stream_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_STRUCT, bistream_class, bistream_class_init(), and bistream_type.
bistream_class_init()
static void bistream_class_init (AZBufferInputStreamClass * klass) static
References az_class_declare_interface(), AZ_TYPE_INPUT_STREAM, bistream_is_eof(), bistream_is_error(), bistream_read(), bistream_seek(), and bistream_skip().
Referenced by az_buffer_input_stream_get_type().
bistream_is_eof()
static int bistream_is_eof (const AZInputStreamImplementation * impl, AZInputStream * inst) static
Referenced by bistream_class_init().
bistream_is_error()
static int bistream_is_error (const AZInputStreamImplementation * impl, AZInputStream * inst) static
Referenced by bistream_class_init().
bistream_read()
static int64_t bistream_read (const AZInputStreamImplementation * impl, AZInputStream * inst, void * data, uint64_t size) static
Referenced by bistream_class_init().
bistream_seek()
static int64_t bistream_seek (const AZInputStreamImplementation * impl, AZInputStream * inst, uint64_t offset) static
Referenced by bistream_class_init().
bistream_skip()
static int64_t bistream_skip (const AZInputStreamImplementation * impl, AZInputStream * inst, uint64_t n_bytes) static
Referenced by bistream_class_init().
Variable Documentation
bistream_class
AZBufferInputStreamClass* bistream_class = NULL
Referenced by az_buffer_input_stream_get_type().
bistream_type
unsigned int bistream_type = 0
Referenced by az_buffer_input_stream_get_type().