az: class.c File Reference
class.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arikkei/arikkei-strlib.h>
#include <az/base.h>
#include <az/class.h>
#include <az/extend.h>
#include <az/function-value.h>
#include <az/packed-value.h>
#include <az/private.h>
Macros
#define __AZ_CLASS_C__
Enumerations
enum { FUNC_SETSTATICPROPERTY , FUNC_GETSTATICPROPERTY , NUM_PROPERTIES }
Functions
static unsigned int impl_call_setStaticProperty (const AZImplementation **arg_impls, const AZValue **arg_vals, const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
static unsigned int impl_call_getstaticProperty (const AZImplementation **arg_impls, const AZValue **arg_vals, const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
void az_impl_class_post_init (void)
void az_class_class_post_init (void)
AZClass * az_class_new (const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
void az_class_new_with_value (AZClass *klass)
void az_class_set_num_interfaces (AZClass *klass, unsigned int n_ifaces)
void az_class_declare_interface (AZClass *klass, unsigned int idx, unsigned int type, unsigned int impl_offset, unsigned int inst_offset)
void az_class_post_init (AZClass *klass)
void az_class_set_num_properties (AZClass *klass, unsigned int nproperties)
void az_class_define_property_value (AZClass *klass, unsigned int idx, const uint8_t *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
void az_class_define_property_packed (AZClass *klass, unsigned int idx, const uint8_t *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
void az_class_define_property (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZImplementation *impl, void *inst)
void az_class_define_property_function_val (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, const AZImplementation *impl, void *inst)
void az_class_define_property_function_packed (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZFunctionSignature *sig)
void az_class_define_method (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *))
void az_class_define_method_va (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *), unsigned int ret_type, unsigned int n_args,...)
void az_class_define_static_method (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *))
void az_class_define_static_method_va (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *), unsigned int ret_type, unsigned int n_args,...)
int az_class_lookup_property (const AZClass *klass, const AZImplementation *impl, void *inst, const AZString *key, const AZClass **def_class, const AZImplementation **sub_impl, void **sub_inst)
get the index, the containing class and corresponding implementation and instance of a property
int az_class_lookup_function (const AZClass *klass, const AZImplementation *impl, void *inst, const AZString *key, AZFunctionSignature *sig, const AZClass **def_class, const AZImplementation **sub_impl, void **sub_inst)
Variables
static unsigned char zero_val [16] = { 0 }
Macro Definition Documentation
__AZ_CLASS_C__
#define __AZ_CLASS_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FUNC_SETSTATICPROPERTY
FUNC_GETSTATICPROPERTY
NUM_PROPERTIES
Function Documentation
az_class_class_post_init()
void az_class_class_post_init (void)
References az_class_define_property(), az_class_set_num_properties(), AZ_FIELD_INSTANCE, AZ_FIELD_READ_VALUE, AZ_TYPE_CLASS, and AZClassKlass.
az_class_declare_interface()
void az_class_declare_interface (AZClass * klass, unsigned int idx, unsigned int type, unsigned int impl_offset, unsigned int inst_offset)
References AZ_CLASS_IS_INTERFACE, az_implementation_init_by_type(), and AZ_TYPE_IS_INTERFACE.
Referenced by array_class_init(), array_list_class_init(), array_object_class_init(), az_active_object_class_init(), bistream_class_init(), bostream_class_init(), function_value_class_init(), interface_list_class_init(), mostream_class_init(), object_interface_list_class_init(), object_list_class_init(), osostream_class_init(), packed_value_array_class_init(), value_array_class_init(), and value_array_ref_class_init().
az_class_define_method()
void az_class_define_method (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke)
References az_class_define_property_function_val(), AZ_CLASS_TYPE, AZ_FIELD_INSTANCE, AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, az_function_signature_new(), az_function_value_setup(), and AZ_TYPE_FUNCTION_VALUE.
Referenced by az_class_define_method_va().
az_class_define_method_va()
void az_class_define_method_va (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke, unsigned int ret_type, unsigned int n_args, ...)
References az_class_define_method().
Referenced by az_active_object_class_init(), az_impl_class_post_init(), collection_class_init(), and object_list_class_init().
az_class_define_property()
void az_class_define_property (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZImplementation * impl, void * inst)
References AZ_FIELD_READ_INSTANCE, AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), AZ_FIELD_WRITE_NONE, AZ_IMPL_TYPE, az_type_is_assignable_to(), and AZ_TYPE_NONE.
Referenced by az_class_class_post_init(), az_post_init_primitive_classes(), collection_class_init(), list_class_init(), object_list_class_init(), packed_value_array_class_init(), and value_array_ref_class_init().
az_class_define_property_function_packed()
void az_class_define_property_function_packed (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZFunctionSignature * sig)
References az_field_setup_function_packed(), and AZ_FIELD_WRITE_NONE.
az_class_define_property_function_val()
void az_class_define_property_function_val (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, const AZImplementation * impl, void * inst)
References az_field_setup_function(), and AZ_FIELD_WRITE_NONE.
Referenced by az_class_define_method(), and az_class_define_static_method().
az_class_define_property_packed()
void az_class_define_property_packed (AZClass * klass, unsigned int idx, const uint8_t * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_PACKED, az_field_setup_value(), AZ_FIELD_WRITE_NONE, and AZ_TYPE_NONE.
az_class_define_property_value()
void az_class_define_property_value (AZClass * klass, unsigned int idx, const uint8_t * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_VALUE, az_field_setup_value(), AZ_FIELD_WRITE_NONE, and AZ_TYPE_NONE.
Referenced by az_init_object_class(), and az_post_init_primitive_classes().
az_class_define_static_method()
void az_class_define_static_method (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke)
References az_class_define_property_function_val(), AZ_FIELD_CLASS, AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, az_function_signature_new(), az_function_value_setup(), AZ_TYPE_FUNCTION_VALUE, and AZ_TYPE_NONE.
Referenced by az_class_define_static_method_va().
az_class_define_static_method_va()
void az_class_define_static_method_va (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke, unsigned int ret_type, unsigned int n_args, ...)
References az_class_define_static_method().
az_class_lookup_function()
int az_class_lookup_function (const AZClass * klass, const AZImplementation * impl, void * inst, const AZString * key, AZFunctionSignature * sig, const AZClass ** def_class, const AZImplementation ** sub_impl, void ** sub_inst)
References az_class_iface_self(), az_class_lookup_function(), az_function_signature_is_assignable_to(), and az_string_equals().
Referenced by az_class_lookup_function(), and az_instance_get_function_by_key().
az_class_lookup_property()
int az_class_lookup_property (const AZClass * klass, const AZImplementation * impl, void * inst, const AZString * key, const AZClass ** def_class, const AZImplementation ** sub_impl, void ** sub_inst)
get the index, the containing class and corresponding implementation and instance of a property
Searches class and interface definitions recursively for a property. The order is class->interface[0]->superinterfaces->interface[1]...->superclasses If the index is >= 0, the property definition is def_class->props_self[index]
Parameters
klass current class (either the same as implementation or a superclass)
impl type implementation (can be null for static properties)
inst type instance (can be null for static or implementation properties)
key the property key
def_class result for the class where the property is defined
sub_impl result for the actual implementation (either impl or sub-implementation, can be null)
sub_inst result for the actual instance (either inst or sub-interface, can be null)
Returns
the property index in def_class
References az_class_iface_self(), az_class_lookup_property(), and az_string_equals().
Referenced by az_class_lookup_property(), az_instance_get_property_by_key(), az_instance_set_property_by_key(), impl_call_getstaticProperty(), and impl_call_setStaticProperty().
az_class_new()
AZClass * az_class_new (const unsigned char * name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize)
References az_register_class(), AZ_TYPE_IS_FINAL, and AZ_TYPE_NONE.
Referenced by az_register_composite_type(), and az_register_type().
az_class_new_with_value()
void az_class_new_with_value (AZClass * klass)
References az_register_class().
Referenced by az_init_base_classes(), az_init_boxed_interface_class(), az_init_boxed_value_class(), az_init_field_class(), az_init_function_classes(), az_init_input_stream_class(), az_init_interface_class(), az_init_object_class(), az_init_output_stream_class(), az_init_packed_value_class(), az_init_primitive_classes(), az_init_reference_class(), and az_init_string_class().
az_class_post_init()
void az_class_post_init (AZClass * klass)
References az_class_iface_all(), and az_class_iface_self().
Referenced by az_post_init_base_classes(), az_post_init_primitive_classes(), az_register_composite_type(), and az_register_type().
az_class_set_num_interfaces()
void az_class_set_num_interfaces (AZClass * klass, unsigned int n_ifaces)
Referenced by az_register_composite_type(), and az_register_type().
az_class_set_num_properties()
void az_class_set_num_properties (AZClass * klass, unsigned int nproperties)
Referenced by az_class_class_post_init(), az_impl_class_post_init(), az_init_object_class(), az_post_init_primitive_classes(), az_register_composite_type(), and az_register_type().
az_impl_class_post_init()
void az_impl_class_post_init (void)
References az_class_define_method_va(), az_class_set_num_properties(), AZ_TYPE_ANY, AZ_TYPE_NONE, AZ_TYPE_STRING, AZImplKlass, FUNC_GETSTATICPROPERTY, FUNC_SETSTATICPROPERTY, impl_call_getstaticProperty(), impl_call_setStaticProperty(), and NUM_PROPERTIES.
Referenced by az_post_init_base_classes().
impl_call_getstaticProperty()
static unsigned int impl_call_getstaticProperty (const AZImplementation ** arg_impls, const AZValue ** arg_vals, const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References AZ_CLASS_FROM_IMPL, az_class_lookup_property(), AZ_FIELD_CLASS, AZ_FIELD_READ_NONE, and az_instance_get_property_by_id().
Referenced by az_impl_class_post_init().
impl_call_setStaticProperty()
static unsigned int impl_call_setStaticProperty (const AZImplementation ** arg_impls, const AZValue ** arg_vals, const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References AZ_CLASS_FROM_IMPL, az_class_lookup_property(), AZ_FIELD_CLASS, AZ_FIELD_WRITE_NONE, az_instance_set_property_by_id(), and az_value_get_inst().
Referenced by az_impl_class_post_init().
Variable Documentation
zero_val
unsigned char zero_val[16] = { 0 } static