az: class.h File Reference
class.h File Reference
#include <stdint.h>
#include <az/az.h>
Data Structures
struct AZImplementation
Superclass of all implementations and classes.
struct AZIFEntry
struct AZInstanceAllocator
struct AZClass
Semantics of a type.
Macros
#define AZ_IMPL_IS_CLASS(i) ((i)->flags & AZ_FLAG_IMPL_IS_CLASS)
true if AZImplementation is standalone AZClass
#define AZ_CLASS_FROM_IMPL(i) (AZ_IMPL_IS_CLASS(i) ? (AZClass *) (i) : (i)->klass)
#define AZ_IMPL_TYPE(i) (AZ_IMPL_IS_CLASS(i) ? (i)->type : (i)->klass->impl.type)
#define AZ_IMPL_FLAGS(i) (AZ_IMPL_IS_CLASS(i) ? (i)->flags : (i)->klass->impl.flags)
#define AZ_IMPL_IS_BLOCK(i) (!AZ_IMPL_IS_CLASS(i) || ((i)->flags & AZ_FLAG_BLOCK))
#define AZ_IMPL_IS_VALUE(i) (AZ_IMPL_IS_CLASS(i) && !((i)->flags & AZ_FLAG_BLOCK))
#define AZ_IMPL_IS_REFERENCE(i) (AZ_IMPL_IS_CLASS(i) && ((i)->flags & AZ_FLAG_REFERENCE))
#define AZ_IMPL_IS_BOXED_VALUE(i) ((i) == &AZBoxedValueKlass.klass.impl))
#define AZ_IMPL_IS_BOXED_INTERFACE(i) ((i) == &AZBoxedInterfaceKlass.klass.impl))
#define AZ_CLASS_TYPE(c) ((c)->impl.type)
#define AZ_CLASS_FLAGS(c) ((c)->impl.flags)
#define AZ_CLASS_IS_ABSTRACT(c) ((c)->impl.flags & AZ_FLAG_ABSTRACT)
#define AZ_CLASS_IS_BLOCK(c) !((c)->impl.flags & AZ_FLAG_BLOCK)
#define AZ_CLASS_IS_VALUE(c) !((c)->impl.flags & AZ_FLAG_BLOCK)
#define AZ_CLASS_IS_REFERENCE(c) !((c)->impl.flags & AZ_FLAG_REFERENCE)
#define AZ_CLASS_IS_BOXED_VALUE(c) ((c) == &AZBoxedValueKlass))
#define AZ_CLASS_IS_BOXED_INTERFACE(c) ((c) == &AZBoxedInterfaceKlass))
#define AZ_CLASS_IS_INTERFACE(c) ((c)->impl.flags & AZ_FLAG_INTERFACE)
#define AZ_CLASS_IS_FINAL(c) ((c)->impl.flags & AZ_FLAG_FINAL)
#define AZ_CLASS_VALUE_SIZE(c) (((c)->impl.flags & AZ_FLAG_BLOCK) ? sizeof(void *) : (c)->instance_size)
#define AZ_CLASS_ELEMENT_SIZE(c) (((c)->impl.flags & AZ_FLAG_BLOCK) ? sizeof(void *) : ((c)->instance_size + (c)->alignment) & ~(c)->alignment)
Functions
static const AZIFEntry * az_class_ifaces_self (const AZClass *klass)
static const AZIFEntry * az_class_iface_self (const AZClass *klass, uint16_t idx)
static const AZIFEntry * az_class_ifaces_all (const AZClass *klass)
static const AZIFEntry * az_class_iface_all (const AZClass *klass, uint16_t idx)
static unsigned int az_class_value_size (const AZClass *klass)
static AZClass * az_class_parent (const AZClass *klass)
int az_class_lookup_property (const AZClass *klass, const AZImplementation *impl, void *inst, const AZString *key, const AZClass **def_class, const AZImplementation **sub_impl, void **sub_inst)
get the index, the containing class and corresponding implementation and instance of a property
int az_class_lookup_function (const AZClass *klass, const AZImplementation *impl, void *inst, const AZString *key, AZFunctionSignature *sig, const AZClass **def_class, const AZImplementation **sub_impl, void **sub_inst)
Macro Definition Documentation
AZ_CLASS_ELEMENT_SIZE
#define AZ_CLASS_ELEMENT_SIZE (c) (((c)->impl.flags & AZ_FLAG_BLOCK) ? sizeof(void *) : ((c)->instance_size + (c)->alignment) & ~(c)->alignment)
AZ_CLASS_FLAGS
#define AZ_CLASS_FLAGS (c) ((c)->impl.flags)
AZ_CLASS_FROM_IMPL
#define AZ_CLASS_FROM_IMPL (i) (AZ_IMPL_IS_CLASS(i) ? (AZClass *) (i) : (i)->klass)
AZ_CLASS_IS_ABSTRACT
#define AZ_CLASS_IS_ABSTRACT (c) ((c)->impl.flags & AZ_FLAG_ABSTRACT)
AZ_CLASS_IS_BLOCK
#define AZ_CLASS_IS_BLOCK (c) !((c)->impl.flags & AZ_FLAG_BLOCK)
AZ_CLASS_IS_BOXED_INTERFACE
#define AZ_CLASS_IS_BOXED_INTERFACE (c) ((c) == &AZBoxedInterfaceKlass))
AZ_CLASS_IS_BOXED_VALUE
#define AZ_CLASS_IS_BOXED_VALUE (c) ((c) == &AZBoxedValueKlass))
AZ_CLASS_IS_FINAL
#define AZ_CLASS_IS_FINAL (c) ((c)->impl.flags & AZ_FLAG_FINAL)
AZ_CLASS_IS_INTERFACE
#define AZ_CLASS_IS_INTERFACE (c) ((c)->impl.flags & AZ_FLAG_INTERFACE)
AZ_CLASS_IS_REFERENCE
#define AZ_CLASS_IS_REFERENCE (c) !((c)->impl.flags & AZ_FLAG_REFERENCE)
AZ_CLASS_IS_VALUE
#define AZ_CLASS_IS_VALUE (c) !((c)->impl.flags & AZ_FLAG_BLOCK)
AZ_CLASS_TYPE
#define AZ_CLASS_TYPE (c) ((c)->impl.type)
AZ_CLASS_VALUE_SIZE
#define AZ_CLASS_VALUE_SIZE (c) (((c)->impl.flags & AZ_FLAG_BLOCK) ? sizeof(void *) : (c)->instance_size)
AZ_IMPL_FLAGS
#define AZ_IMPL_FLAGS (i) (AZ_IMPL_IS_CLASS(i) ? (i)->flags : (i)->klass->impl.flags)
AZ_IMPL_IS_BLOCK
#define AZ_IMPL_IS_BLOCK (i) (!AZ_IMPL_IS_CLASS(i) || ((i)->flags & AZ_FLAG_BLOCK))
AZ_IMPL_IS_BOXED_INTERFACE
#define AZ_IMPL_IS_BOXED_INTERFACE (i) ((i) == &AZBoxedInterfaceKlass.klass.impl))
AZ_IMPL_IS_BOXED_VALUE
#define AZ_IMPL_IS_BOXED_VALUE (i) ((i) == &AZBoxedValueKlass.klass.impl))
AZ_IMPL_IS_CLASS
#define AZ_IMPL_IS_CLASS (i) ((i)->flags & AZ_FLAG_IMPL_IS_CLASS)
true if AZImplementation is standalone AZClass
AZ_IMPL_IS_REFERENCE
#define AZ_IMPL_IS_REFERENCE (i) (AZ_IMPL_IS_CLASS(i) && ((i)->flags & AZ_FLAG_REFERENCE))
AZ_IMPL_IS_VALUE
#define AZ_IMPL_IS_VALUE (i) (AZ_IMPL_IS_CLASS(i) && !((i)->flags & AZ_FLAG_BLOCK))
AZ_IMPL_TYPE
#define AZ_IMPL_TYPE (i) (AZ_IMPL_IS_CLASS(i) ? (i)->type : (i)->klass->impl.type)
Function Documentation
az_class_iface_all()
static const AZIFEntry * az_class_iface_all (const AZClass * klass, uint16_t idx) inline static
References az_class_ifaces_all().
Referenced by az_class_post_init(), and az_instance_get_interface().
az_class_iface_self()
static const AZIFEntry * az_class_iface_self (const AZClass * klass, uint16_t idx) inline static
References az_class_ifaces_self().
Referenced by az_class_post_init(), az_instance_finalize_recursive(), and az_instance_init_recursive().
az_class_ifaces_all()
static const AZIFEntry * az_class_ifaces_all (const AZClass * klass) inline static
Referenced by az_class_iface_all().
az_class_ifaces_self()
static const AZIFEntry * az_class_ifaces_self (const AZClass * klass) inline static
Referenced by az_class_iface_self(), and implementation_init_recursive().
az_class_lookup_function()
int az_class_lookup_function (const AZClass * klass, const AZImplementation * impl, void * inst, const AZString * key, AZFunctionSignature * sig, const AZClass ** def_class, const AZImplementation ** sub_impl, void ** sub_inst)
Referenced by az_instance_get_function_by_key().
az_class_lookup_property()
int az_class_lookup_property (const AZClass * klass, const AZImplementation * impl, void * inst, const AZString * key, const AZClass ** def_class, const AZImplementation ** sub_impl, void ** sub_inst)
get the index, the containing class and corresponding implementation and instance of a property
Searches class and interface definitions recursively for a property. The order is class->interface[0]->superinterfaces->interface[1]...->superclasses If the index is >= 0, the property definition is def_class->props_self[index]
Parameters
klass current class (either the same as implementation or a superclass)
impl type implementation (can be null for static properties)
inst type instance (can be null for static or implementation properties)
key the property key
def_class result for the class where the property is defined
sub_impl result for the actual implementation (either impl or sub-implementation, can be null)
sub_inst result for the actual instance (either inst or sub-interface, can be null)
Returns
the property index in def_class
Referenced by az_instance_get_property_by_key(), az_instance_set_property_by_key(), impl_call_getstaticProperty(), and impl_call_setStaticProperty().
az_class_parent()
static AZClass * az_class_parent (const AZClass * klass) inline static
az_class_value_size()
static unsigned int az_class_value_size (const AZClass * klass) inline static
References AZ_FLAG_BLOCK.
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_field_setup_stored(), az_value_copy(), az_value_delete_array(), az_value_new_array(), and az_value_transfer().