az: collection.c File Reference
collection.c File Reference
#include <stdlib.h>
#include <az/boxed-interface.h>
#include <az/private.h>
#include <az/extend.h>
#include "collection.h"
Macros
#define __AZ_COLLECTION_C__
Enumerations
enum { FUNC_CONTAINS , PROP_SIZE , NUM_PROPERTIES }
Functions
static void collection_class_init (AZCollectionClass *klass)
static unsigned int collection_get_property (const AZImplementation *impl, void *inst, unsigned int idx, const AZImplementation **prop_impl, AZValue *prop_val, AZContext *ctx)
static unsigned int collection_call_contains (const AZImplementation *arg_impls[], const AZValue *arg_vals[], const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_collection_get_type (void)
Variables
static unsigned int collection_type = 0
static AZCollectionClass * collection_class
Macro Definition Documentation
__AZ_COLLECTION_C__
#define __AZ_COLLECTION_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FUNC_CONTAINS
PROP_SIZE
NUM_PROPERTIES
Function Documentation
az_collection_get_type()
unsigned int az_collection_get_type (void)
References az_register_interface_type(), AZ_TYPE_INTERFACE, collection_class, collection_class_init(), and collection_type.
collection_call_contains()
static unsigned int collection_call_contains (const AZImplementation * arg_impls[], const AZValue * arg_vals[], const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References az_collection_contains(), AZ_IMPL_FROM_TYPE, AZ_IMPL_TYPE, AZ_TYPE_BOOLEAN, AZ_TYPE_BOXED_INTERFACE, and az_value_get_inst().
Referenced by collection_class_init().
collection_class_init()
static void collection_class_init (AZCollectionClass * klass) static
References AZ_FIELD_INSTANCE, AZ_FIELD_READ_METHOD, AZ_TYPE_ANY, AZ_TYPE_BOOLEAN, AZ_TYPE_UINT32, collection_call_contains(), collection_get_property(), FUNC_CONTAINS, NUM_PROPERTIES, and PROP_SIZE.
Referenced by az_collection_get_type().
collection_get_property()
static unsigned int collection_get_property (const AZImplementation * impl, void * inst, unsigned int idx, const AZImplementation ** prop_impl, AZValue * prop_val, AZContext * ctx) static
References az_collection_get_size(), az_type_get_class, and AZ_TYPE_UINT32.
Referenced by collection_class_init().
Variable Documentation
collection_class
AZCollectionClass* collection_class static
Referenced by az_collection_get_type().
collection_type
unsigned int collection_type = 0 static
Referenced by az_collection_get_type().