az: collection.h File Reference
collection.h File Reference
#include <az/interface.h>
Data Structures
struct AZCollection
struct AZCollectionImplementation
struct AZCollectionClass
Macros
#define AZ_TYPE_COLLECTION (az_collection_get_type ())
Functions
unsigned int az_collection_get_type (void)
static unsigned int az_collection_get_element_type (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
static unsigned int az_collection_get_size (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
static unsigned int az_collection_contains (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZImplementation *val_impl, const void *val_inst)
static const AZImplementation * az_collection_get_iterator (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
static const AZImplementation * az_collection_iterator_next (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
static const AZImplementation * az_collection_get_element (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZValue *iter, AZValue *val, unsigned int size)
Macro Definition Documentation
AZ_TYPE_COLLECTION
#define AZ_TYPE_COLLECTION (az_collection_get_type ())
Function Documentation
az_collection_contains()
static unsigned int az_collection_contains (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZImplementation * val_impl, const void * val_inst) inline static
References val_inst().
Referenced by collection_call_contains(), and value_array_ref_contains().
az_collection_get_element()
static const AZImplementation * az_collection_get_element (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZValue * iter, AZValue * val, unsigned int size) inline static
az_collection_get_element_type()
static unsigned int az_collection_get_element_type (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) inline static
az_collection_get_iterator()
static const AZImplementation * az_collection_get_iterator (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) inline static
Referenced by collection_call_get_iterator().
az_collection_get_size()
static unsigned int az_collection_get_size (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) inline static
Referenced by attrd_get_iterator(), attrd_iterator_next(), list_get_iterator(), list_get_property(), and list_iterator_next().
az_collection_get_type()
unsigned int az_collection_get_type (void)
References AZ_FLAG_ABSTRACT, az_register_interface_type(), AZ_TYPE_INTERFACE, collection_class, collection_class_init(), collection_type, and NUM_PROPERTIES.
az_collection_iterator_next()
static const AZImplementation * az_collection_iterator_next (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) inline static