az: convert.c File Reference
convert.c File Reference
#include <stdio.h>
#include <az/class.h>
#include <az/convert.h>
#include <az/primitives.h>
#include <az/types.h>
Macros
#define __AZ_CONVERT_H__
Functions
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
Macro Definition Documentation
__AZ_CONVERT_H__
#define __AZ_CONVERT_H__
Function Documentation
az_type_is_convertible_to()
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
True if: type is test both type and test are arithmetic and have automatic conversion rule
Parameters
type the query
test the type to be tested against
Returns
1 if type can be converted
References AZ_CLASS_FROM_TYPE, AZ_CONVERT_AUTO, az_init(), az_num_types, az_primitive_can_convert(), AZ_TYPE_INDEX, AZ_TYPE_IS_ARITHMETIC, and az_type_is_assignable_to().
Referenced by az_function_signature_is_assignable_to().