az: extend.h File Reference
extend.h File Reference
#include <az/class.h>
#include <az/field.h>
Functions
AZClass * az_register_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*class_init)(AZClass *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
Get new typecode, allocate and initialize a class structure.
AZClass * az_register_composite_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*class_init)(AZClass *, void *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *), void *data)
Get new typecode, allocate and initialize a class structure.
void az_class_set_num_interfaces (AZClass *klass, unsigned int ninterfaces)
void az_class_declare_interface (AZClass *klass, unsigned int idx, unsigned int type, unsigned int impl_offset, unsigned int inst_offset)
void az_class_set_num_properties (AZClass *klass, unsigned int nproperties)
void az_class_define_property_value (AZClass *klass, unsigned int idx, const uint8_t *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
void az_class_define_property_packed (AZClass *klass, unsigned int idx, const uint8_t *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
void az_class_define_property (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZImplementation *impl, void *inst)
void az_class_define_property_function_val (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, const AZImplementation *impl, void *inst)
void az_class_define_property_function_packed (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZFunctionSignature *sig)
void az_class_define_method (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *))
void az_class_define_method_va (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *), unsigned int ret_type, unsigned int n_args,...)
void az_class_define_static_method (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *))
void az_class_define_static_method_va (AZClass *klass, unsigned int idx, const unsigned char *key, unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *), unsigned int ret_type, unsigned int n_args,...)
Function Documentation
az_class_declare_interface()
void az_class_declare_interface (AZClass * klass, unsigned int idx, unsigned int type, unsigned int impl_offset, unsigned int inst_offset)
References AZ_CLASS_IS_INTERFACE, az_implementation_init_by_type(), and AZ_TYPE_IS_INTERFACE.
Referenced by array_class_init(), array_list_class_init(), array_object_class_init(), az_active_object_class_init(), bistream_class_init(), bostream_class_init(), function_value_class_init(), interface_list_class_init(), mostream_class_init(), object_interface_list_class_init(), object_list_class_init(), osostream_class_init(), packed_value_array_class_init(), value_array_class_init(), and value_array_ref_class_init().
az_class_define_method()
void az_class_define_method (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke)
References az_class_define_property_function_val(), AZ_CLASS_TYPE, AZ_FIELD_INSTANCE, AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, az_function_signature_new(), az_function_value_setup(), and AZ_TYPE_FUNCTION_VALUE.
Referenced by az_class_define_method_va().
az_class_define_method_va()
void az_class_define_method_va (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke, unsigned int ret_type, unsigned int n_args, ...)
References az_class_define_method().
Referenced by az_active_object_class_init(), az_impl_class_post_init(), collection_class_init(), and object_list_class_init().
az_class_define_property()
void az_class_define_property (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZImplementation * impl, void * inst)
References AZ_FIELD_READ_INSTANCE, AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), AZ_FIELD_WRITE_NONE, AZ_IMPL_TYPE, az_type_is_assignable_to(), and AZ_TYPE_NONE.
Referenced by az_class_class_post_init(), az_post_init_primitive_classes(), collection_class_init(), list_class_init(), object_list_class_init(), packed_value_array_class_init(), and value_array_ref_class_init().
az_class_define_property_function_packed()
void az_class_define_property_function_packed (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset, const AZFunctionSignature * sig)
References az_field_setup_function_packed(), and AZ_FIELD_WRITE_NONE.
az_class_define_property_function_val()
void az_class_define_property_function_val (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, const AZImplementation * impl, void * inst)
References az_field_setup_function(), and AZ_FIELD_WRITE_NONE.
Referenced by az_class_define_method(), and az_class_define_static_method().
az_class_define_property_packed()
void az_class_define_property_packed (AZClass * klass, unsigned int idx, const uint8_t * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_PACKED, az_field_setup_value(), AZ_FIELD_WRITE_NONE, and AZ_TYPE_NONE.
az_class_define_property_value()
void az_class_define_property_value (AZClass * klass, unsigned int idx, const uint8_t * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_VALUE, az_field_setup_value(), AZ_FIELD_WRITE_NONE, and AZ_TYPE_NONE.
Referenced by az_init_object_class(), and az_post_init_primitive_classes().
az_class_define_static_method()
void az_class_define_static_method (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[], unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke)
References az_class_define_property_function_val(), AZ_FIELD_CLASS, AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, az_function_signature_new(), az_function_value_setup(), AZ_TYPE_FUNCTION_VALUE, and AZ_TYPE_NONE.
Referenced by az_class_define_static_method_va().
az_class_define_static_method_va()
void az_class_define_static_method_va (AZClass * klass, unsigned int idx, const unsigned char * key, unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke, unsigned int ret_type, unsigned int n_args, ...)
References az_class_define_static_method().
az_class_set_num_interfaces()
void az_class_set_num_interfaces (AZClass * klass, unsigned int ninterfaces)
Referenced by az_register_composite_type(), and az_register_type().
az_class_set_num_properties()
void az_class_set_num_properties (AZClass * klass, unsigned int nproperties)
Referenced by az_class_class_post_init(), az_impl_class_post_init(), az_init_object_class(), az_post_init_primitive_classes(), az_register_composite_type(), and az_register_type().