az: field.h File Reference
field.h File Reference
#include <az/packed-value.h>
Data Structures
struct AZField
Macros
#define AZ_FIELD_INSTANCE 0
#define AZ_FIELD_IMPLEMENTATION 1
#define AZ_FIELD_CLASS 2
#define AZ_FIELD_READ_NONE 0
#define AZ_FIELD_READ_VALUE 1
#define AZ_FIELD_READ_PACKED 2
#define AZ_FIELD_READ_METHOD 3
#define AZ_FIELD_READ_STORED_STATIC 4
#define AZ_FIELD_WRITE_NONE 0
#define AZ_FIELD_WRITE_VALUE 1
#define AZ_FIELD_WRITE_PACKED 2
#define AZ_FIELD_WRITE_METHOD 3
Typedefs
typedef struct _AZFieldFunction AZFieldFUnction
Functions
void az_field_setup_value (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset)
void az_field_setup_stored (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZImplementation *impl, void *inst)
void az_field_setup_method (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write)
void az_field_setup_function (AZField *prop, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, const AZImplementation *impl, void *inst)
void az_field_setup_function_packed (AZField *prop, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, unsigned int offset)
Variables
AZClass AZFieldKlass
Macro Definition Documentation
AZ_FIELD_CLASS
#define AZ_FIELD_CLASS 2
AZ_FIELD_IMPLEMENTATION
#define AZ_FIELD_IMPLEMENTATION 1
AZ_FIELD_INSTANCE
#define AZ_FIELD_INSTANCE 0
AZ_FIELD_READ_METHOD
#define AZ_FIELD_READ_METHOD 3
AZ_FIELD_READ_NONE
#define AZ_FIELD_READ_NONE 0
AZ_FIELD_READ_PACKED
#define AZ_FIELD_READ_PACKED 2
AZ_FIELD_READ_STORED_STATIC
#define AZ_FIELD_READ_STORED_STATIC 4
AZ_FIELD_READ_VALUE
#define AZ_FIELD_READ_VALUE 1
AZ_FIELD_WRITE_METHOD
#define AZ_FIELD_WRITE_METHOD 3
AZ_FIELD_WRITE_NONE
#define AZ_FIELD_WRITE_NONE 0
AZ_FIELD_WRITE_PACKED
#define AZ_FIELD_WRITE_PACKED 2
AZ_FIELD_WRITE_VALUE
#define AZ_FIELD_WRITE_VALUE 1
Typedef Documentation
AZFieldFUnction
typedef struct _AZFieldFunction AZFieldFUnction
Function Documentation
az_field_setup_function()
void az_field_setup_function (AZField * prop, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, const AZImplementation * impl, void * inst)
References AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), and AZ_TYPE_FUNCTION.
az_field_setup_function_packed()
void az_field_setup_function_packed (AZField * prop, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, unsigned int offset)
References AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), and AZ_TYPE_FUNCTION.
az_field_setup_method()
void az_field_setup_method (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write)
References AZ_FIELD_READ_METHOD, AZ_FIELD_WRITE_METHOD, AZ_FIELD_WRITE_NONE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_NONE, and AZ_TYPE_REFERENCE.
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
az_field_setup_stored()
void az_field_setup_stored (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, AZ_IMPL_TYPE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), az_type_is_assignable_to(), AZ_TYPE_NONE, AZ_TYPE_REFERENCE, and az_value_set_from_inst().
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
az_field_setup_value()
void az_field_setup_value (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, AZ_FIELD_WRITE_METHOD, AZ_FIELD_WRITE_NONE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_NONE, and AZ_TYPE_REFERENCE.
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
Variable Documentation
AZFieldKlass
AZClass AZFieldKlass extern
Referenced by az_init_field_class().