az: field.c File Reference
field.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <arikkei/arikkei-utils.h>
#include <az/base.h>
#include <az/string.h>
#include <az/field.h>
#include <az/packed-value.h>
#include <az/private.h>
Macros
#define __AZ_FIELD_C__
Functions
void az_init_field_class (void)
void az_field_setup_value (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset)
void az_field_setup_stored (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZImplementation *impl, void *inst)
void az_field_setup_method (AZField *prop, const unsigned char *key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write)
void az_field_setup_function (AZField *field, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, const AZImplementation *impl, void *inst)
void az_field_setup_function_packed (AZField *field, const unsigned char *key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature *sig, unsigned int offset)
Variables
AZClass AZFieldKlass
Macro Definition Documentation
__AZ_FIELD_C__
#define __AZ_FIELD_C__
Function Documentation
az_field_setup_function()
void az_field_setup_function (AZField * field, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, const AZImplementation * impl, void * inst)
References AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), and AZ_TYPE_FUNCTION.
az_field_setup_function_packed()
void az_field_setup_function_packed (AZField * field, const unsigned char * key, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZFunctionSignature * sig, unsigned int offset)
References AZ_FIELD_READ_METHOD, AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), and AZ_TYPE_FUNCTION.
az_field_setup_method()
void az_field_setup_method (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write)
References AZ_FIELD_READ_METHOD, AZ_FIELD_WRITE_METHOD, AZ_FIELD_WRITE_NONE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_NONE, and AZ_TYPE_REFERENCE.
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
az_field_setup_stored()
void az_field_setup_stored (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_FIELD_READ_STORED_STATIC, AZ_FIELD_WRITE_NONE, AZ_IMPL_TYPE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), az_type_is_assignable_to(), AZ_TYPE_NONE, AZ_TYPE_REFERENCE, and az_value_set_from_inst().
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
az_field_setup_value()
void az_field_setup_value (AZField * prop, const unsigned char * key, unsigned int type, unsigned int is_final, unsigned int spec, unsigned int read, unsigned int write, unsigned int offset)
References AZ_FIELD_READ_PACKED, AZ_FIELD_READ_VALUE, AZ_FIELD_WRITE_METHOD, AZ_FIELD_WRITE_NONE, az_string_new(), AZ_TYPE_FUNCTION, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_NONE, and AZ_TYPE_REFERENCE.
Referenced by az_field_setup_function(), and az_field_setup_function_packed().
az_init_field_class()
void az_init_field_class (void)
References az_class_new_with_value(), and AZFieldKlass.
Referenced by az_init().
Variable Documentation
AZFieldKlass
AZClass AZFieldKlass
Initial value:
= {
    {AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_FIELD},
    &AZBlockKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "field",
    7, sizeof(AZClass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL
}
Referenced by az_init_field_class().