az: function-value.c File Reference
function-value.c File Reference
#include <stdlib.h>
#include <az/function-value.h>
#include <az/extend.h>
Macros
#define __AZ_FUNCTION_VALUE_C__
Functions
static void function_value_class_init (AZFunctionValueClass *klass)
const AZFunctionSignature * fval_signature (const AZFunctionImplementation *impl, AZFunctionInstance *inst)
static unsigned int function_value_invoke (const AZFunctionImplementation *impl, AZFunctionInstance *inst, const AZImplementation *arg_impls[], const AZValue *arg_vals[], const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_function_value_get_type (void)
void az_function_value_setup (AZFunctionValue *fval, AZFunctionSignature *sig, unsigned int(*invoke)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *))
Variables
static unsigned int function_value_type = 0
Macro Definition Documentation
__AZ_FUNCTION_VALUE_C__
#define __AZ_FUNCTION_VALUE_C__
Function Documentation
az_function_value_get_type()
unsigned int az_function_value_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_STRUCT, function_value_class_init(), and function_value_type.
az_function_value_setup()
void az_function_value_setup (AZFunctionValue * fval, AZFunctionSignature * sig, unsigned int(*)(const AZImplementation **, const AZValue **, const AZImplementation **, AZValue64 *, AZContext *) invoke)
function_value_class_init()
static void function_value_class_init (AZFunctionValueClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_TYPE_FUNCTION, function_value_invoke(), and fval_signature().
Referenced by az_function_value_get_type().
function_value_invoke()
static unsigned int function_value_invoke (const AZFunctionImplementation * impl, AZFunctionInstance * inst, const AZImplementation * arg_impls[], const AZValue * arg_vals[], const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
Referenced by function_value_class_init().
fval_signature()
const AZFunctionSignature * fval_signature (const AZFunctionImplementation * impl, AZFunctionInstance * inst)
Referenced by function_value_class_init().
Variable Documentation
function_value_type
unsigned int function_value_type = 0 static
Referenced by az_function_value_get_type().