az: function.c File Reference
function.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <az/base.h>
#include <az/convert.h>
#include <az/instance.h>
#include <az/object.h>
#include <az/packed-value.h>
#include <az/private.h>
#include <az/function.h>
Macros
#define __AZ_FUNCTION_C__
Functions
void az_init_function_classes (void)
AZFunctionSignature * az_function_signature_new (unsigned int this_type, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[])
AZFunctionSignature * az_function_signature_new_any (unsigned int this_type, unsigned int ret_type, unsigned int n_args)
AZFunctionSignature * az_function_signature_new_va (unsigned int ret_type, unsigned int n_args,...)
void az_function_signature_delete (AZFunctionSignature *sig)
unsigned int az_function_signature_is_assignable_to (const AZFunctionSignature *sig, const AZFunctionSignature *other, unsigned int test_ret_val)
const AZFunctionSignature * az_function_get_signature (const AZFunctionImplementation *impl, void *inst)
unsigned int az_function_invoke (const AZFunctionImplementation *impl, void *inst, const AZImplementation *arg_impls[], const AZValue *arg_vals[], const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_function_convert_args_in_place (const AZFunctionImplementation *impl, void *inst, const AZImplementation *arg_impls[], AZValue *arg_vals[])
unsigned int az_function_invoke_packed (const AZFunctionImplementation *impl, void *inst, AZPackedValue *thisval, AZPackedValue64 *retval, AZPackedValue *args, unsigned int checktypes)
Invoke function using packed arguments.
unsigned int az_function_invoke_by_type_instance (unsigned int type, void *instance, AZPackedValue *thisval, AZPackedValue64 *retval, AZPackedValue *args, unsigned int checktypes)
unsigned int az_instance_invoke_function (const AZImplementation *impl, void *inst, AZPackedValue *this_val, AZPackedValue64 *ret_val, AZPackedValue *args, unsigned int check_types)
unsigned int az_function_invoke_va (const AZFunctionImplementation *impl, void *inst, const AZImplementation **ret_impl, AZValue64 *ret_val,...)
Invoke function interface.
unsigned int az_function_invoke_by_signature_va (const AZFunctionImplementation *impl, void *inst, const AZFunctionSignature *sig, const AZImplementation **ret_impl, AZValue64 *ret_val,...)
unsigned int az_function_invoke_by_value_signature_va (const AZImplementation *impl, const AZValue *val, const AZFunctionSignature *sig, const AZImplementation **ret_impl, AZValue64 *ret_val,...)
Variables
AZClass AZFunctionSignatureKlass
AZInterfaceClass AZFunctionKlass
Macro Definition Documentation
__AZ_FUNCTION_C__
#define __AZ_FUNCTION_C__
Function Documentation
az_function_convert_args_in_place()
unsigned int az_function_convert_args_in_place (const AZFunctionImplementation * impl, void * inst, const AZImplementation * arg_impls[], AZValue * arg_vals[])
References az_function_get_signature(), AZ_IMPL_TYPE, AZ_TYPE_FUNCTION, az_type_is_a(), and az_value_convert_in_place().
az_function_get_signature()
const AZFunctionSignature * az_function_get_signature (const AZFunctionImplementation * impl, void * inst)
Referenced by az_function_convert_args_in_place(), az_function_invoke_packed(), and az_function_invoke_va().
az_function_invoke_by_signature_va()
unsigned int az_function_invoke_by_signature_va (const AZFunctionImplementation * impl, void * inst, const AZFunctionSignature * sig, const AZImplementation ** ret_impl, AZValue64 * ret_val, ...)
References az_function_invoke().
az_function_invoke_by_type_instance()
unsigned int az_function_invoke_by_type_instance (unsigned int type, void * instance, AZPackedValue * thisval, AZPackedValue64 * retval, AZPackedValue * args, unsigned int checktypes)
References az_function_invoke_packed(), az_instance_get_interface(), AZ_TYPE_FUNCTION, az_type_get_class, and az_type_implements().
az_function_invoke_by_value_signature_va()
unsigned int az_function_invoke_by_value_signature_va (const AZImplementation * impl, const AZValue * val, const AZFunctionSignature * sig, const AZImplementation ** ret_impl, AZValue64 * ret_val, ...)
References az_instance_get_interface(), AZ_TYPE_FUNCTION, and az_value_get_inst().
az_function_signature_delete()
void az_function_signature_delete (AZFunctionSignature * sig)
References az_instance_delete(), and AZ_TYPE_FUNCTION_SIGNATURE.
az_function_signature_is_assignable_to()
unsigned int az_function_signature_is_assignable_to (const AZFunctionSignature * sig, const AZFunctionSignature * other, unsigned int test_ret_val)
References az_type_is_a(), and az_type_is_convertible_to().
az_function_signature_new()
AZFunctionSignature * az_function_signature_new (unsigned int this_type, unsigned int ret_type, unsigned int n_args, const unsigned int arg_types[])
References az_instance_init_by_type(), and AZ_TYPE_FUNCTION_SIGNATURE.
az_function_signature_new_any()
AZFunctionSignature * az_function_signature_new_any (unsigned int this_type, unsigned int ret_type, unsigned int n_args)
References az_instance_init_by_type(), AZ_TYPE_ANY, and AZ_TYPE_FUNCTION_SIGNATURE.
az_function_signature_new_va()
AZFunctionSignature * az_function_signature_new_va (unsigned int ret_type, unsigned int n_args, ...)
References az_instance_init_by_type(), and AZ_TYPE_FUNCTION_SIGNATURE.
az_init_function_classes()
void az_init_function_classes (void)
References az_class_new_with_value(), AZFunctionKlass, and AZFunctionSignatureKlass.
Referenced by az_init().
az_instance_invoke_function()
unsigned int az_instance_invoke_function (const AZImplementation * impl, void * inst, AZPackedValue * this_val, AZPackedValue64 * ret_val, AZPackedValue * args, unsigned int check_types)
References az_function_invoke_packed(), AZ_IMPL_TYPE, az_instance_get_interface(), AZ_TYPE_FUNCTION, and az_type_implements().
Variable Documentation
AZFunctionKlass
AZInterfaceClass AZFunctionKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_FUNCTION},
    &AZInterfaceKlass.klass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "function",
    3, sizeof(AZInterfaceKlass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL},
    sizeof(AZFunctionImplementation), NULL
}
Referenced by az_init_function_classes().
AZFunctionSignatureKlass
AZClass AZFunctionSignatureKlass
Initial value:
= {
    {AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_FUNCTION_SIGNATURE},
    &AZBlockKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "signature",
    7, sizeof(AZClass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL
}
Referenced by az_init_function_classes().