az: Function interface
Function interface
Classes
struct AZFunctionInstance
Abtract interface.
struct AZFunctionClass
Implementation superclass.
Functions
unsigned int az_function_invoke (const AZFunctionImplementation *impl, AZFunctionInstance *inst, const AZImplementation *arg_impls[], const AZValue *arg_vals[], const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_function_invoke_packed (const AZFunctionImplementation *impl, AZFunctionInstance *inst, AZPackedValue *this_val, AZPackedValue64 *ret_val, AZPackedValue *args, unsigned int check_types)
Invoke function using packed arguments.
unsigned int az_function_invoke_va (const AZFunctionImplementation *impl, AZFunctionInstance *inst, const AZImplementation **ret_impl, AZValue64 *ret_val,...)
Invoke function interface.
Detailed Description
A callable interface
Function Documentation
az_function_invoke()
unsigned int az_function_invoke (const AZFunctionImplementation * impl, AZFunctionInstance * inst, const AZImplementation * arg_impls[], const AZValue * arg_vals[], const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx)
First value is this (if applicable)
References ARIKKEI_CHECK_INTEGRITY, AZ_IMPL_TYPE, AZ_TYPE_FUNCTION, and az_type_is_a().
Referenced by az_function_invoke_by_signature_va(), and az_function_invoke_va().
az_function_invoke_packed()
unsigned int az_function_invoke_packed (const AZFunctionImplementation * impl, AZFunctionInstance * inst, AZPackedValue * this_val, AZPackedValue64 * ret_val, AZPackedValue * args, unsigned int check_types)
Invoke function using packed arguments.
Parameters
impl
inst
this_val
ret_val
args
check_types
Returns
unsigned int
References AZ_IMPL_TYPE, az_packed_value_clear(), AZ_PACKED_VALUE_TYPE, AZ_TYPE_BLOCK, AZ_TYPE_FUNCTION, and az_type_is_a().
Referenced by az_function_invoke_by_type_instance(), and az_instance_invoke_function().
az_function_invoke_va()
unsigned int az_function_invoke_va (const AZFunctionImplementation * impl, AZFunctionInstance * inst, const AZImplementation ** ret_impl, AZValue64 * ret_val, ...)
Invoke function interface.
Parameters
impl
inst
ret_impl
ret_val
...
Returns
unsigned int
References az_function_invoke().