az: AZ types
AZ types
Enumerations
enum AZTypeFlags {
AZ_FLAG_BLOCK = 0x01000000 , AZ_FLAG_INTERFACE = 0x02000000 , AZ_FLAG_REFERENCE = 0x04000000 , AZ_FLAG_BOXED = 0x08000000 ,
AZ_FLAG_OBJECT = 0x10000000 , AZ_FLAG_FINAL = 0x20000000 , AZ_FLAG_ABSTRACT = 0x40000000 , AZ_FLAG_CONSTRUCT = 0x80000000
}
Type flags.
enum AZImplementationFlags {
AZ_FLAG_IMPL_IS_CLASS = 0x01 , AZ_FLAG_ZERO_MEMORY = 0x04 , AZ_FLAG_ARITHMETIC = 0x100 , AZ_FLAG_INTEGRAL = 0x200 ,
AZ_FLAG_SIGNED = 0x400
}
Implementation/Class flags.
enum AZTypeIdx {
AZ_TYPE_IDX_NONE , AZ_TYPE_IDX_ANY , AZ_TYPE_IDX_BOOLEAN , AZ_TYPE_IDX_INT8 ,
AZ_TYPE_IDX_UINT8 , AZ_TYPE_IDX_INT16 , AZ_TYPE_IDX_UINT16 , AZ_TYPE_IDX_INT32 ,
AZ_TYPE_IDX_UINT32 , AZ_TYPE_IDX_INT64 , AZ_TYPE_IDX_UINT64 , AZ_TYPE_IDX_FLOAT ,
AZ_TYPE_IDX_DOUBLE , AZ_TYPE_IDX_COMPLEX_FLOAT , AZ_TYPE_IDX_COMPLEX_DOUBLE , AZ_TYPE_IDX_POINTER ,
AZ_TYPE_IDX_STRUCT , AZ_TYPE_IDX_BLOCK , AZ_TYPE_IDX_IMPLEMENTATION , AZ_TYPE_IDX_CLASS ,
AZ_TYPE_IDX_INTERFACE , AZ_TYPE_IDX_FIELD , AZ_TYPE_IDX_FUNCTION_SIGNATURE , AZ_TYPE_IDX_FUNCTION ,
AZ_TYPE_IDX_REFERENCE , AZ_TYPE_IDX_STRING , AZ_TYPE_IDX_BOXED_VALUE , AZ_TYPE_IDX_BOXED_INTERFACE ,
AZ_TYPE_IDX_PACKED_VALUE , AZ_TYPE_IDX_OBJECT , AZ_TYPE_IDX_INPUT_STREAM , AZ_TYPE_IDX_OUTPUT_STREAM
}
Predefined type indices.
enum AZType {
AZ_TYPE_NONE = AZ_TYPE_IDX_NONE , AZ_TYPE_ANY = AZ_TYPE_IDX_ANY | AZ_FLAG_ABSTRACT , AZ_TYPE_BOOLEAN = AZ_TYPE_IDX_BOOLEAN | AZ_FLAG_FINAL , AZ_TYPE_INT8 = AZ_TYPE_IDX_INT8 | AZ_FLAG_FINAL ,
AZ_TYPE_UINT8 = AZ_TYPE_IDX_UINT8 | AZ_FLAG_FINAL , AZ_TYPE_INT16 = AZ_TYPE_IDX_INT16 | AZ_FLAG_FINAL , AZ_TYPE_UINT16 = AZ_TYPE_IDX_UINT16 | AZ_FLAG_FINAL , AZ_TYPE_INT32 = AZ_TYPE_IDX_INT32 | AZ_FLAG_FINAL ,
AZ_TYPE_UINT32 = AZ_TYPE_IDX_UINT32 | AZ_FLAG_FINAL , AZ_TYPE_INT64 = AZ_TYPE_IDX_INT64 | AZ_FLAG_FINAL , AZ_TYPE_UINT64 = AZ_TYPE_IDX_UINT64 | AZ_FLAG_FINAL , AZ_TYPE_FLOAT = AZ_TYPE_IDX_FLOAT | AZ_FLAG_FINAL ,
AZ_TYPE_DOUBLE = AZ_TYPE_IDX_DOUBLE | AZ_FLAG_FINAL , AZ_TYPE_COMPLEX_FLOAT = AZ_TYPE_IDX_COMPLEX_FLOAT | AZ_FLAG_FINAL , AZ_TYPE_COMPLEX_DOUBLE = AZ_TYPE_IDX_COMPLEX_DOUBLE | AZ_FLAG_FINAL , AZ_TYPE_POINTER = AZ_TYPE_IDX_POINTER | AZ_FLAG_FINAL ,
AZ_TYPE_STRUCT = AZ_TYPE_IDX_STRUCT | AZ_FLAG_ABSTRACT , AZ_TYPE_BLOCK = AZ_TYPE_IDX_BLOCK | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT , AZ_TYPE_IMPLEMENTATION = AZ_TYPE_IDX_IMPLEMENTATION | AZ_FLAG_BLOCK , AZ_TYPE_CLASS = AZ_TYPE_IDX_CLASS | AZ_FLAG_BLOCK | AZ_FLAG_FINAL ,
AZ_TYPE_INTERFACE = AZ_TYPE_IDX_INTERFACE | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE , AZ_TYPE_FIELD = AZ_TYPE_IDX_FIELD | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_FUNCTION_SIGNATURE = AZ_TYPE_IDX_FUNCTION_SIGNATURE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_FUNCTION = AZ_TYPE_IDX_FUNCTION | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE ,
AZ_TYPE_REFERENCE = AZ_TYPE_IDX_REFERENCE | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_REFERENCE , AZ_TYPE_STRING = AZ_TYPE_IDX_STRING | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE , AZ_TYPE_BOXED_VALUE = AZ_TYPE_IDX_BOXED_VALUE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED , AZ_TYPE_BOXED_INTERFACE = AZ_TYPE_IDX_BOXED_INTERFACE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_REFERENCE | AZ_FLAG_BOXED ,
AZ_TYPE_PACKED_VALUE = AZ_TYPE_IDX_PACKED_VALUE | AZ_FLAG_BLOCK | AZ_FLAG_FINAL , AZ_TYPE_OBJECT = AZ_TYPE_IDX_OBJECT | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_REFERENCE | AZ_FLAG_OBJECT , AZ_TYPE_INPUT_STREAM = AZ_TYPE_IDX_INPUT_STREAM | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE , AZ_TYPE_OUTPUT_STREAM = AZ_TYPE_IDX_OUTPUT_STREAM | AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE
}
Predefined typecodes.
Functions
AZClass * az_register_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*class_init)(AZClass *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
Get new typecode, allocate and initialize a class structure.
AZClass * az_register_composite_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*class_init)(AZClass *, void *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *), void *data)
Get new typecode, allocate and initialize a class structure.
unsigned int az_type_get_parent_primitive (unsigned int type)
Get parent primitive type.
unsigned int az_type_is_a (unsigned int type, unsigned int test)
Checks whether the given type is a subtype of another.
unsigned int az_type_implements (unsigned int type, unsigned int test)
Checks whether the given type implements an interface type.
unsigned int az_type_is_assignable_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can be assigned to a variable of given type.
Detailed Description
The basic type access
An AZ type ia a 32-bit unsigned integer, composed of two parts:
24-bit type index (bits 23-0), used to access type info array
8-bit flags (bits 31-24), used to store type flags
Types are used throughout the api as a more compact type identifier than class pointer.
Semantically types are synonymous to a class, NOT an implementation - the interfaces have to be accessed through an Implementation/Instance pointer pair because typecode only gives access to the class of the interface, not to it's actual implementation.
Enumeration Type Documentation
AZImplementationFlags
enum AZImplementationFlags
Implementation/Class flags.
These are stored in lower-order bits (bits 23-0) and either describe the implementation behaviour or less-used type hierarchy information and are stored only in the class (implementation) flags field.
The AZ_FLAG_IMPL_IS_CLASS flag is a special case: it is stored in the implementation flags and marks whether the implementation is a class (containing flags field) or a standalone implementation of an interface (containing pointer to the class instead).
Enumerator
AZ_FLAG_IMPL_IS_CLASS
Marks that an implementation is a standalone class.
It exploits the feature that classes are aligned to 8 bytes. Thus, if any of the 3 lowest bits is set, the AZImplementation union contains flags and type, not a pointer to the AZClass
AZ_FLAG_ZERO_MEMORY
Instance construction should be preceded by filling memory by zeroes.
Subclasses should not clear this flag if set set by parent. If set the type can still implement constructor - which can then rely on the instance being zero-filled.
AZ_FLAG_ARITHMETIC
AZ_FLAG_INTEGRAL
AZ_FLAG_SIGNED
AZType
enum AZType
Predefined typecodes.
The actual typecodes (index plus flags).
These are used througout the api as a more compact type identifier than class pointer. Semantically they are synonymous to a class, NOT an implementation - the interfaces have to be accessed through an Implementation/Instance pointer pair because typecode only gives access to the class of the interface, not to it's actual implementation.
Enumerator
AZ_TYPE_NONE
Invalid or missing type, typecode 0.
AZ_TYPE_ANY
The abstract base class of all types.
AZ_TYPE_BOOLEAN
AZ_TYPE_INT8
AZ_TYPE_UINT8
AZ_TYPE_INT16
AZ_TYPE_UINT16
AZ_TYPE_INT32
AZ_TYPE_UINT32
AZ_TYPE_INT64
AZ_TYPE_UINT64
AZ_TYPE_FLOAT
AZ_TYPE_DOUBLE
AZ_TYPE_COMPLEX_FLOAT
AZ_TYPE_COMPLEX_DOUBLE
AZ_TYPE_POINTER
AZ_TYPE_STRUCT
The abstract base class of all composite value types.
AZ_TYPE_BLOCK
The abstract base class of all block types.
AZ_TYPE_IMPLEMENTATION
The abstract base class of the semantics of a type.
An instance of _AZImplementation. Specialized for interface types, _AZClass for standalone types
AZ_TYPE_CLASS
The semantics of a type.
An instance of _AZClass, a subclass of _AZImplementation
AZ_TYPE_INTERFACE
An abstract base class of an instance of interface type.
AZ_TYPE_FIELD
AZ_TYPE_FUNCTION_SIGNATURE
AZ_TYPE_FUNCTION
AZ_TYPE_REFERENCE
A block type that implements reference counting.
AZ_TYPE_STRING
An immutable reference-counted utf8 string type.
The strings having the same textual value are collated using an hash table. Thus string equality can be checked by comparing the pointers.
AZ_TYPE_BOXED_VALUE
A reference that can contain an arbitrary value-type.
These are mostly used to fit any value type into predefined storage space
AZ_TYPE_BOXED_INTERFACE
A reference that contain a value and resolved interface of it.
These are used to store interfaces by guaranteeing that the containing instance remains alive (and in case of value types at the same place) during the interface lifecycle.
AZ_TYPE_PACKED_VALUE
A convenience container that stores both a value and a pointer to it's implementation.
AZ_TYPE_OBJECT
A special reference type that contains a pointer to it's own class.
Objects can be used without specifying their implementations.
AZ_TYPE_INPUT_STREAM
An abstract interface for reading serialized data.
AZ_TYPE_OUTPUT_STREAM
An abstract interface for writing serialized data.
AZTypeFlags
enum AZTypeFlags
Type flags.
These are high-level flags that describe the most important type/class attributes.
They are stored in the typecode (bits 31-24), so they are available directly from typecode without accessing the class array (saving pointer dereference and potential thread synchronization).
Enumerator
AZ_FLAG_BLOCK
Type is a block, value is a pointer to the instance (not the instance itself)
AZ_FLAG_INTERFACE
Type is an interface, implementation is not class.
AZ_FLAG_REFERENCE
Type is a reference, value creation/destruction involves reference counting.
AZ_FLAG_BOXED
Instance is a container of another value (_AZBoxedValue) or interface (_AZBoxedInterface) type.
AZ_FLAG_OBJECT
A special reference type that contains a pointer to it's class.
AZ_FLAG_FINAL
Type is final, no further subclassing is allowed.
AZ_FLAG_ABSTRACT
Type is abstract, no instancing is allowed.
This flag is NOT propagated to subclasses.
AZ_FLAG_CONSTRUCT
The type instances have constructor or destructor.
Subclasses should not clear this flag if set set by parent. This flags is automatically set during type registration if:
the type has constructor (init) or destructor (finalize)
AZ_FLAGS_ZERO_MEMORY is set
class implements interfaces or has properties
AZTypeIdx
enum AZTypeIdx
Predefined type indices.
These are stored in the upper-order bits (bits 31-24) of the typecode. The index is used to access the type information (class) in the single global array.
Enumerator
AZ_TYPE_IDX_NONE
AZ_TYPE_IDX_ANY
AZ_TYPE_IDX_BOOLEAN
AZ_TYPE_IDX_INT8
AZ_TYPE_IDX_UINT8
AZ_TYPE_IDX_INT16
AZ_TYPE_IDX_UINT16
AZ_TYPE_IDX_INT32
AZ_TYPE_IDX_UINT32
AZ_TYPE_IDX_INT64
AZ_TYPE_IDX_UINT64
AZ_TYPE_IDX_FLOAT
AZ_TYPE_IDX_DOUBLE
AZ_TYPE_IDX_COMPLEX_FLOAT
AZ_TYPE_IDX_COMPLEX_DOUBLE
AZ_TYPE_IDX_POINTER
AZ_TYPE_IDX_STRUCT
AZ_TYPE_IDX_BLOCK
AZ_TYPE_IDX_IMPLEMENTATION
AZ_TYPE_IDX_CLASS
AZ_TYPE_IDX_INTERFACE
AZ_TYPE_IDX_FIELD
AZ_TYPE_IDX_FUNCTION_SIGNATURE
AZ_TYPE_IDX_FUNCTION
AZ_TYPE_IDX_REFERENCE
AZ_TYPE_IDX_STRING
AZ_TYPE_IDX_BOXED_VALUE
AZ_TYPE_IDX_BOXED_INTERFACE
AZ_TYPE_IDX_PACKED_VALUE
AZ_TYPE_IDX_OBJECT
AZ_TYPE_IDX_INPUT_STREAM
AZ_TYPE_IDX_OUTPUT_STREAM
Function Documentation
az_register_composite_type()
AZClass * az_register_composite_type (unsigned int * type, const unsigned char * name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*)(AZClass *, void *) class_init, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize, void * data)
Get new typecode, allocate and initialize a class structure.
Gets a new typecode, initializes its class to the minimal functional state and then calls class_init, where a more specialized setup (e.g. registering interfaces and fields) should be done. The final setup is performed only after class_init returns (and thus the interfaces and fields are known). Unlike az_register_type this method allows passing extra parameter to the class_init method. It is used to build composite classes (e.g. reference of another type).
Parameters
type pointer where the typecode will be written
name the name of the new type
parent_type the parent typecode
class_size the size of the class
instance_size the size of the instance
flags type flags
n_interfaces_self number of interfaces implemented by this type
n_properties_self number of properties defined for this type
class_init the class constructor
instance_init a the instance constructor
instance_finalize the instance destructor
data extra parameter to the class constructor
Returns
allocated and initialized class
References az_class_new(), az_class_post_init(), az_class_set_num_interfaces(), az_class_set_num_properties(), AZ_FLAG_CONSTRUCT, and AZ_FLAG_ZERO_MEMORY.
Referenced by az_reference_of_get_type().
az_register_type()
AZClass * az_register_type (unsigned int * type, const unsigned char * name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, unsigned int n_interfaces_self, unsigned int n_properties_self, void(*)(AZClass *) class_init, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize)
Get new typecode, allocate and initialize a class structure.
Gets a new typecode, initializes its class to the minimal functional state and then calls class_init, where a more specialized setup (e.g. registering interfaces and fields) should be done. The final setup is performed only after class_init returns (and thus the interfaces and fields are known).
Parameters
type pointer where the typecode will be written
name the name of the new type
parent_type the parent typecode
class_size the size of the class
instance_size the size of the instance
flags type flags
n_interfaces_self number of interfaces implemented by this type
n_properties_self number of properties defined for this type
class_init the class constructor
instance_init the instance constructor
instance_finalize the instance destructor
Returns
allocated and initialized class
References az_class_new(), az_class_post_init(), az_class_set_num_interfaces(), az_class_set_num_properties(), AZ_FLAG_CONSTRUCT, and AZ_FLAG_ZERO_MEMORY.
Referenced by az_abstract_reference_of_get_type(), az_active_object_get_type(), az_array_get_type(), az_array_list_get_type(), az_array_object_get_type(), az_buffer_input_stream_get_type(), az_buffer_output_stream_get_type(), az_function_value_get_type(), az_interface_list_get_type(), az_memory_output_stream_get_type(), az_object_interface_list_get_type(), az_object_list_get_type(), az_os_output_stream_get_type(), az_packed_value_array_get_type(), az_register_interface_type(), az_value_array_get_type(), az_value_array_ref_get_type(), and az_weak_reference_get_type().
az_type_get_parent_primitive()
unsigned int az_type_get_parent_primitive (unsigned int type)
Get parent primitive type.
Parameters
type the query type
Returns
the parent primitive (AZ_TYPE_BOOLEAN - AZ_TYPE_BLOCK) or AZ_TYPE_NONE for invalid type
References AZ_CLASS_TYPE, AZ_NUM_FUNDAMENTAL_TYPES, and AZ_TYPE_INDEX.
az_type_implements()
unsigned int az_type_implements (unsigned int type, unsigned int test)
Checks whether the given type implements an interface type.
Parameters
type the type that is checked
test the interface type tested against
Returns
1 if type implements test, 0 if not or if either type is invalid
References az_instance_get_interface(), and AZ_TYPE_IS_INTERFACE.
Referenced by az_function_invoke_by_type_instance(), az_instance_invoke_function(), az_instance_set_property_by_id(), az_object_implements(), az_type_is_assignable_to(), az_value_convert_auto(), and az_value_convert_in_place().
az_type_is_a()
unsigned int az_type_is_a (unsigned int type, unsigned int test)
Checks whether the given type is a subtype of another.
Parameters
type the type that is checked
test the type tested against
Returns
1 if type is a subtype of test, 0 if not or if either type is invalid
References AZ_TYPE_INDEX.
Referenced by az_array_list_append(), az_array_list_insert(), az_array_list_set_element(), az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), az_function_convert_args_in_place(), az_function_invoke(), az_function_invoke_packed(), az_function_signature_is_assignable_to(), az_instance_get_interface(), az_instance_set_property_by_id(), az_interface_list_append(), az_interface_list_new(), az_interface_list_setup(), az_object_check_instance_cast(), az_object_check_instance_type(), az_object_interface_list_new(), az_object_interface_list_setup(), az_object_list_new(), az_object_list_setup(), az_object_new(), az_packed_value_can_convert(), az_packed_value_convert(), az_register_interface_type(), az_type_is_a_reference_of(), az_type_is_assignable_to(), az_value_convert_auto(), and az_value_convert_in_place().
az_type_is_assignable_to()
unsigned int az_type_is_assignable_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can be assigned to a variable of given type.
True if:
type is test
type implements test
type is NONE and test is ANY or BLOCK
Parameters
type the type that is checked
test the type of variable to be tested against
Returns
1 if type can be assigned, 0 if not or if either type is invalid
References AZ_TYPE_ANY, az_type_implements(), az_type_is_a(), AZ_TYPE_IS_BLOCK, and AZ_TYPE_IS_INTERFACE.
Referenced by az_class_define_property(), az_field_setup_stored(), and az_type_is_convertible_to().