az: hash-map.h File Reference
hash-map.h File Reference
#include <az/collections/map.h>
Data Structures
struct AZHashMap
A map implementation based on a hash table.
struct AZHashMapImplementation
struct AZHashMapClass
Macros
#define AZ_TYPE_HASH_MAP (az_hash_map_get_type ())
Functions
unsigned int az_hash_map_get_type (void)
void az_hash_map_insert (const AZHashMapImplementation *impl, AZHashMap *hmap, void *key, void *val)
unsigned int az_hash_map_remove (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
void az_hash_map_clear (const AZHashMapImplementation *impl, AZHashMap *hmap)
unsigned int az_hash_map_exists (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
unsigned int az_hash_map_exists_val (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *val)
const void * az_hash_map_lookup (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
unsigned int az_hash_map_forall (const AZHashMapImplementation *impl, AZHashMap *hmap, unsigned int(*forall)(const void *, const void *, void *), void *data)
unsigned int az_hash_map_remove_all (const AZHashMapImplementation *impl, AZHashMap *hmap, unsigned int(*remove)(const void *, const void *, void *), void *data)
Macro Definition Documentation
AZ_TYPE_HASH_MAP
#define AZ_TYPE_HASH_MAP (az_hash_map_get_type ())
Function Documentation
az_hash_map_clear()
void az_hash_map_clear (const AZHashMapImplementation * impl, AZHashMap * hmap)
References clear_entry(), EMPTY, END, and entry_ptr().
az_hash_map_exists()
unsigned int az_hash_map_exists (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References az_hash_map_lookup().
Referenced by hmap_contains_key().
az_hash_map_exists_val()
unsigned int az_hash_map_exists_val (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * val)
References az_value_equals_instance_autobox(), EMPTY, END, entry_ptr(), and val_ptr().
Referenced by hmap_contains().
az_hash_map_forall()
unsigned int az_hash_map_forall (const AZHashMapImplementation * impl, AZHashMap * hmap, unsigned int(*)(const void *, const void *, void *) forall, void * data)
References EMPTY, END, entry_ptr(), key_inst(), and val_inst().
az_hash_map_get_type()
unsigned int az_hash_map_get_type (void)
References AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_MAP, hmap_class, hmap_implementation_init(), hmap_instance_finalize(), hmap_instance_init(), and hmap_type.
az_hash_map_insert()
void az_hash_map_insert (const AZHashMapImplementation * impl, AZHashMap * hmap, void * key, void * val)
References az_hash_map_insert(), EMPTY, END, entry_ptr(), key_inst(), reallocate(), and set_entry().
Referenced by az_hash_map_insert().
az_hash_map_lookup()
const void * az_hash_map_lookup (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References EMPTY, END, entry_ptr(), key_inst(), and val_inst().
Referenced by az_hash_map_exists(), and hmap_map_lookup().
az_hash_map_remove()
unsigned int az_hash_map_remove (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References clear_entry(), EMPTY, END, entry_ptr(), and key_inst().
az_hash_map_remove_all()
unsigned int az_hash_map_remove_all (const AZHashMapImplementation * impl, AZHashMap * hmap, unsigned int(*)(const void *, const void *, void *) remove, void * data)
References clear_entry(), EMPTY, END, entry_ptr(), key_inst(), and val_inst().