az: hash-set.h File Reference
hash-set.h File Reference
#include <az/collections/set.h>
Data Structures
struct AZHashSet
A set implementation based on a hash table.
struct AZHashSetImplementation
struct AZHashSetClass
Macros
#define AZ_TYPE_HASH_SET (az_hash_set_get_type ())
Functions
unsigned int az_hash_set_get_type (void)
void az_hash_set_insert (const AZHashSetImplementation *impl, AZHashSet *hset, void *elem)
unsigned int az_hash_set_remove (const AZHashSetImplementation *impl, AZHashSet *hset, const void *elem)
void az_hash_set_clear (const AZHashSetImplementation *impl, AZHashSet *hset)
unsigned int az_hash_set_contains (const AZHashSetImplementation *impl, AZHashSet *hset, const void *elem)
unsigned int az_hash_set_forall (const AZHashSetImplementation *impl, AZHashSet *hset, unsigned int(*forall)(const void *, void *), void *data)
unsigned int az_hash_set_remove_all (const AZHashSetImplementation *impl, AZHashSet *hset, unsigned int(*remove)(const void *, void *), void *data)
Macro Definition Documentation
AZ_TYPE_HASH_SET
#define AZ_TYPE_HASH_SET (az_hash_set_get_type ())
Function Documentation
az_hash_set_clear()
void az_hash_set_clear (const AZHashSetImplementation * impl, AZHashSet * hset)
References clear_entry(), EMPTY, END, and entry_ptr().
az_hash_set_contains()
unsigned int az_hash_set_contains (const AZHashSetImplementation * impl, AZHashSet * hset, const void * elem)
References elem_inst(), EMPTY, END, and entry_ptr().
Referenced by hset_contains().
az_hash_set_forall()
unsigned int az_hash_set_forall (const AZHashSetImplementation * impl, AZHashSet * hset, unsigned int(*)(const void *, void *) forall, void * data)
References elem_inst(), EMPTY, END, and entry_ptr().
az_hash_set_get_type()
unsigned int az_hash_set_get_type (void)
References AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_SET, hset_class, hset_implementation_init(), hset_instance_finalize(), hset_instance_init(), and hset_type.
az_hash_set_insert()
void az_hash_set_insert (const AZHashSetImplementation * impl, AZHashSet * hset, void * elem)
References az_hash_set_insert(), elem_inst(), EMPTY, END, entry_ptr(), reallocate(), and set_entry().
Referenced by az_hash_set_insert().
az_hash_set_remove()
unsigned int az_hash_set_remove (const AZHashSetImplementation * impl, AZHashSet * hset, const void * elem)
References clear_entry(), elem_inst(), EMPTY, END, and entry_ptr().
az_hash_set_remove_all()
unsigned int az_hash_set_remove_all (const AZHashSetImplementation * impl, AZHashSet * hset, unsigned int(*)(const void *, void *) remove, void * data)
References clear_entry(), elem_inst(), EMPTY, END, and entry_ptr().