az: hash-map.c File Reference
hash-map.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <az/base.h>
#include <az/value.h>
#include <az/packed-value.h>
#include "hash-map.h"
Macros
#define __AZ_HASH_MAP_C__
#define aligned_free(p) free(p)
#define EMPTY 0
#define END 1
Functions
static AZHashMapEntry * entry_ptr (const AZHashMapImplementation *impl, AZHashMapEntry *entries, unsigned int pos)
static AZValue * key_ptr (const AZHashMapImplementation *impl, AZHashMapEntry *entry)
static void * key_inst (const AZHashMapImplementation *impl, AZHashMapEntry *entry)
static AZValue * val_ptr (const AZHashMapImplementation *impl, AZHashMapEntry *entry)
static void * val_inst (const AZHashMapImplementation *impl, AZHashMapEntry *entry)
static void clear_entry (const AZHashMapImplementation *impl, AZHashMapEntry *entry)
static void set_entry (const AZHashMapImplementation *impl, AZHashMapEntry *entry, unsigned int next, void *key, void *val, unsigned int replace)
static AZHashMapEntry * allocate_entries (const AZHashMapImplementation *impl, unsigned int size, unsigned int root_size)
static void reallocate (const AZHashMapImplementation *impl, AZHashMap *hmap, unsigned int new_root_size)
static void hmap_implementation_init (AZHashMapImplementation *impl)
static void hmap_instance_init (const AZHashMapImplementation *impl, AZHashMap *hmap)
static void hmap_instance_finalize (const AZHashMapImplementation *impl, AZHashMap *hmap)
static unsigned int hmap_get_element_type (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
static unsigned int hmap_get_size (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
unsigned int hmap_contains (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * hmap_get_iter (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
static const AZImplementation * hmap_iter_next (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
const AZImplementation * hmap_get_element (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZValue *iter, AZValue *val, unsigned int size)
static unsigned int hmap_get_key_type (const AZMapImplementation *map_impl, AZMap *map_inst)
static const AZImplementation * hmap_get_key (const AZMapImplementation *map_impl, AZMap *map_inst, const AZValue *iter, AZValue *val, unsigned int size)
static unsigned int hmap_contains_key (const AZMapImplementation *map_impl, AZMap *map_inst, const AZImplementation *key_impl, const void *key_inst)
static const AZImplementation * hmap_map_lookup (const AZMapImplementation *map_impl, AZMap *map_inst, const AZImplementation *key_impl, void *key_inst, AZValue *val, unsigned int size)
static unsigned int hmap_keyset_get_element_type (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
static unsigned int hmap_keyset_contains (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZImplementation *val_impl, const void *val_inst)
static const AZImplementation * hmap_keyset_get_element (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZValue *iter, AZValue *val, unsigned int size)
unsigned int az_hash_map_get_type (void)
void az_hash_map_insert (const AZHashMapImplementation *impl, AZHashMap *hmap, void *key, void *val)
unsigned int az_hash_map_remove (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
void az_hash_map_clear (const AZHashMapImplementation *impl, AZHashMap *hmap)
unsigned int az_hash_map_exists (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
unsigned int az_hash_map_exists_val (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *val)
const void * az_hash_map_lookup (const AZHashMapImplementation *impl, AZHashMap *hmap, const void *key)
unsigned int az_hash_map_forall (const AZHashMapImplementation *impl, AZHashMap *hmap, unsigned int(*forall)(const void *, const void *, void *), void *data)
unsigned int az_hash_map_remove_all (const AZHashMapImplementation *impl, AZHashMap *hmap, unsigned int(*remove)(const void *, const void *, void *), void *data)
Variables
static unsigned int hmap_type = 0
static AZHashMapClass * hmap_class
Macro Definition Documentation
__AZ_HASH_MAP_C__
#define __AZ_HASH_MAP_C__
aligned_free
#define aligned_free (p) free(p)
EMPTY
#define EMPTY 0
END
#define END 1
Function Documentation
allocate_entries()
static AZHashMapEntry * allocate_entries (const AZHashMapImplementation * impl, unsigned int size, unsigned int root_size) static
References END.
Referenced by hmap_instance_init(), and reallocate().
az_hash_map_clear()
void az_hash_map_clear (const AZHashMapImplementation * impl, AZHashMap * hmap)
References clear_entry(), EMPTY, END, and entry_ptr().
az_hash_map_exists()
unsigned int az_hash_map_exists (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References az_hash_map_lookup().
Referenced by hmap_contains_key().
az_hash_map_exists_val()
unsigned int az_hash_map_exists_val (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * val)
References az_value_equals_instance_autobox(), EMPTY, END, entry_ptr(), and val_ptr().
Referenced by hmap_contains().
az_hash_map_forall()
unsigned int az_hash_map_forall (const AZHashMapImplementation * impl, AZHashMap * hmap, unsigned int(*)(const void *, const void *, void *) forall, void * data)
References EMPTY, END, entry_ptr(), key_inst(), and val_inst().
az_hash_map_get_type()
unsigned int az_hash_map_get_type (void)
References AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_MAP, hmap_class, hmap_implementation_init(), hmap_instance_finalize(), hmap_instance_init(), and hmap_type.
az_hash_map_insert()
void az_hash_map_insert (const AZHashMapImplementation * impl, AZHashMap * hmap, void * key, void * val)
References az_hash_map_insert(), EMPTY, END, entry_ptr(), key_inst(), reallocate(), and set_entry().
Referenced by az_hash_map_insert().
az_hash_map_lookup()
const void * az_hash_map_lookup (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References EMPTY, END, entry_ptr(), key_inst(), and val_inst().
Referenced by az_hash_map_exists(), and hmap_map_lookup().
az_hash_map_remove()
unsigned int az_hash_map_remove (const AZHashMapImplementation * impl, AZHashMap * hmap, const void * key)
References clear_entry(), EMPTY, END, entry_ptr(), and key_inst().
az_hash_map_remove_all()
unsigned int az_hash_map_remove_all (const AZHashMapImplementation * impl, AZHashMap * hmap, unsigned int(*)(const void *, const void *, void *) remove, void * data)
References clear_entry(), EMPTY, END, entry_ptr(), key_inst(), and val_inst().
clear_entry()
static void clear_entry (const AZHashMapImplementation * impl, AZHashMapEntry * entry) inline static
References az_value_clear(), key_ptr(), and val_ptr().
Referenced by az_hash_map_clear(), az_hash_map_remove(), az_hash_map_remove_all(), and hmap_instance_finalize().
entry_ptr()
static AZHashMapEntry * entry_ptr (const AZHashMapImplementation * impl, AZHashMapEntry * entries, unsigned int pos) static
Referenced by az_hash_map_clear(), az_hash_map_exists_val(), az_hash_map_forall(), az_hash_map_insert(), az_hash_map_lookup(), az_hash_map_remove(), az_hash_map_remove_all(), hmap_get_element(), hmap_get_iter(), hmap_get_key(), hmap_instance_finalize(), hmap_iter_next(), and reallocate().
hmap_contains()
unsigned int hmap_contains (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZImplementation * impl, const void * inst)
References az_hash_map_exists_val().
Referenced by hmap_implementation_init().
hmap_contains_key()
static unsigned int hmap_contains_key (const AZMapImplementation * map_impl, AZMap * map_inst, const AZImplementation * key_impl, const void * key_inst) static
References az_hash_map_exists(), and key_inst().
Referenced by hmap_implementation_init().
hmap_get_element()
const AZImplementation * hmap_get_element (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZValue * iter, AZValue * val, unsigned int size)
References az_value_copy_autobox(), entry_ptr(), and val_ptr().
Referenced by hmap_implementation_init().
hmap_get_element_type()
static unsigned int hmap_get_element_type (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) static
Referenced by hmap_implementation_init().
hmap_get_iter()
static const AZImplementation * hmap_get_iter (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) static
References AZUint64Klass, EMPTY, and entry_ptr().
Referenced by hmap_implementation_init().
hmap_get_key()
static const AZImplementation * hmap_get_key (const AZMapImplementation * map_impl, AZMap * map_inst, const AZValue * iter, AZValue * val, unsigned int size) static
References az_value_copy_autobox(), entry_ptr(), and key_ptr().
Referenced by hmap_implementation_init().
hmap_get_key_type()
static unsigned int hmap_get_key_type (const AZMapImplementation * map_impl, AZMap * map_inst) static
References AZ_IMPL_TYPE.
Referenced by hmap_implementation_init().
hmap_get_size()
unsigned int hmap_get_size (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) static
hmap_implementation_init()
static void hmap_implementation_init (AZHashMapImplementation * impl) static
References hmap_contains(), hmap_contains_key(), hmap_get_element(), hmap_get_element_type(), hmap_get_iter(), hmap_get_key(), hmap_get_key_type(), hmap_iter_next(), and hmap_map_lookup().
Referenced by az_hash_map_get_type().
hmap_instance_finalize()
static void hmap_instance_finalize (const AZHashMapImplementation * impl, AZHashMap * hmap) static
References aligned_free, clear_entry(), EMPTY, END, and entry_ptr().
Referenced by az_hash_map_get_type().
hmap_instance_init()
static void hmap_instance_init (const AZHashMapImplementation * impl, AZHashMap * hmap) static
References allocate_entries().
Referenced by az_hash_map_get_type().
hmap_iter_next()
static const AZImplementation * hmap_iter_next (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) static
References AZUint64Klass, EMPTY, END, and entry_ptr().
Referenced by hmap_implementation_init().
hmap_keyset_contains()
static unsigned int hmap_keyset_contains (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZImplementation * val_impl, const void * val_inst) static
References val_inst().
hmap_keyset_get_element()
static const AZImplementation * hmap_keyset_get_element (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZValue * iter, AZValue * val, unsigned int size) static
hmap_keyset_get_element_type()
static unsigned int hmap_keyset_get_element_type (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) static
hmap_map_lookup()
static const AZImplementation * hmap_map_lookup (const AZMapImplementation * map_impl, AZMap * map_inst, const AZImplementation * key_impl, void * key_inst, AZValue * val, unsigned int size) static
References az_hash_map_lookup(), az_value_set_from_inst_autobox(), and key_inst().
Referenced by hmap_implementation_init().
key_inst()
static void * key_inst (const AZHashMapImplementation * impl, AZHashMapEntry * entry) static
References az_value_get_inst(), and key_ptr().
Referenced by aobj_aa_contains_key(), aobj_aa_map_lookup(), attrd_lookup(), az_hash_map_forall(), az_hash_map_insert(), az_hash_map_lookup(), az_hash_map_remove(), az_hash_map_remove_all(), az_map_contains_key(), az_map_lookup(), hmap_contains_key(), hmap_map_lookup(), and reallocate().
key_ptr()
static AZValue * key_ptr (const AZHashMapImplementation * impl, AZHashMapEntry * entry) static
Referenced by clear_entry(), hmap_get_key(), key_inst(), and set_entry().
reallocate()
static void reallocate (const AZHashMapImplementation * impl, AZHashMap * hmap, unsigned int new_root_size) static
References aligned_free, allocate_entries(), EMPTY, END, entry_ptr(), and key_inst().
Referenced by az_hash_map_insert().
set_entry()
static void set_entry (const AZHashMapImplementation * impl, AZHashMapEntry * entry, unsigned int next, void * key, void * val, unsigned int replace) static
References az_value_clear(), az_value_set_from_inst(), key_ptr(), and val_ptr().
Referenced by az_hash_map_insert().
val_inst()
static void * val_inst (const AZHashMapImplementation * impl, AZHashMapEntry * entry) static
References az_value_get_inst(), and val_ptr().
Referenced by az_collection_contains(), az_hash_map_forall(), az_hash_map_lookup(), az_hash_map_remove_all(), hmap_keyset_contains(), and keyset_contains().
val_ptr()
static AZValue * val_ptr (const AZHashMapImplementation * impl, AZHashMapEntry * entry) static
Referenced by az_hash_map_exists_val(), clear_entry(), hmap_get_element(), set_entry(), and val_inst().
Variable Documentation
hmap_class
AZHashMapClass* hmap_class static
Referenced by az_hash_map_get_type().
hmap_type
unsigned int hmap_type = 0 static
Referenced by az_hash_map_get_type().