az: hash-set.c File Reference
hash-set.c File Reference
#include <stdlib.h>
#include <string.h>
#include <az/base.h>
#include <az/value.h>
#include <az/packed-value.h>
#include "hash-set.h"
Macros
#define __AZ_HASH_SET_C__
#define aligned_free(p) free(p)
#define EMPTY 0
#define END 1
Functions
static AZHashSetEntry * entry_ptr (const AZHashSetImplementation *impl, AZHashSetEntry *entries, unsigned int pos)
static AZValue * elem_ptr (const AZHashSetImplementation *impl, AZHashSetEntry *entry)
static void * elem_inst (const AZHashSetImplementation *impl, AZHashSetEntry *entry)
static void clear_entry (const AZHashSetImplementation *impl, AZHashSetEntry *entry)
static void set_entry (const AZHashSetImplementation *impl, AZHashSetEntry *entry, unsigned int next, void *elem)
static AZHashSetEntry * allocate_entries (const AZHashSetImplementation *impl, unsigned int size, unsigned int root_size)
static void reallocate (const AZHashSetImplementation *impl, AZHashSet *hset, unsigned int new_root_size)
static void hset_implementation_init (AZHashSetImplementation *impl)
static void hset_instance_init (const AZHashSetImplementation *impl, AZHashSet *hset)
static void hset_instance_finalize (const AZHashSetImplementation *impl, AZHashSet *hset)
static unsigned int hset_get_element_type (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
static unsigned int hset_contains (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * hset_get_iter (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
static const AZImplementation * hset_iter_next (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
static const AZImplementation * hset_get_element (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZValue *iter, AZValue *val, unsigned int size)
unsigned int az_hash_set_get_type (void)
void az_hash_set_insert (const AZHashSetImplementation *impl, AZHashSet *hset, void *elem)
unsigned int az_hash_set_remove (const AZHashSetImplementation *impl, AZHashSet *hset, const void *elem)
void az_hash_set_clear (const AZHashSetImplementation *impl, AZHashSet *hset)
unsigned int az_hash_set_contains (const AZHashSetImplementation *impl, AZHashSet *hset, const void *elem)
unsigned int az_hash_set_forall (const AZHashSetImplementation *impl, AZHashSet *hset, unsigned int(*forall)(const void *, void *), void *data)
unsigned int az_hash_set_remove_all (const AZHashSetImplementation *impl, AZHashSet *hset, unsigned int(*remove)(const void *, void *), void *data)
Variables
static unsigned int hset_type = 0
static AZHashSetClass * hset_class
Macro Definition Documentation
__AZ_HASH_SET_C__
#define __AZ_HASH_SET_C__
aligned_free
#define aligned_free (p) free(p)
EMPTY
#define EMPTY 0
END
#define END 1
Function Documentation
allocate_entries()
static AZHashSetEntry * allocate_entries (const AZHashSetImplementation * impl, unsigned int size, unsigned int root_size) static
References END.
Referenced by hset_instance_init(), and reallocate().
az_hash_set_clear()
void az_hash_set_clear (const AZHashSetImplementation * impl, AZHashSet * hset)
References clear_entry(), EMPTY, END, and entry_ptr().
az_hash_set_contains()
unsigned int az_hash_set_contains (const AZHashSetImplementation * impl, AZHashSet * hset, const void * elem)
References elem_inst(), EMPTY, END, and entry_ptr().
Referenced by hset_contains().
az_hash_set_forall()
unsigned int az_hash_set_forall (const AZHashSetImplementation * impl, AZHashSet * hset, unsigned int(*)(const void *, void *) forall, void * data)
References elem_inst(), EMPTY, END, and entry_ptr().
az_hash_set_get_type()
unsigned int az_hash_set_get_type (void)
References AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_SET, hset_class, hset_implementation_init(), hset_instance_finalize(), hset_instance_init(), and hset_type.
az_hash_set_insert()
void az_hash_set_insert (const AZHashSetImplementation * impl, AZHashSet * hset, void * elem)
References az_hash_set_insert(), elem_inst(), EMPTY, END, entry_ptr(), reallocate(), and set_entry().
Referenced by az_hash_set_insert().
az_hash_set_remove()
unsigned int az_hash_set_remove (const AZHashSetImplementation * impl, AZHashSet * hset, const void * elem)
References clear_entry(), elem_inst(), EMPTY, END, and entry_ptr().
az_hash_set_remove_all()
unsigned int az_hash_set_remove_all (const AZHashSetImplementation * impl, AZHashSet * hset, unsigned int(*)(const void *, void *) remove, void * data)
References clear_entry(), elem_inst(), EMPTY, END, and entry_ptr().
clear_entry()
static void clear_entry (const AZHashSetImplementation * impl, AZHashSetEntry * entry) inline static
References az_value_clear(), and elem_ptr().
Referenced by az_hash_set_clear(), az_hash_set_remove(), az_hash_set_remove_all(), and hset_instance_finalize().
elem_inst()
static void * elem_inst (const AZHashSetImplementation * impl, AZHashSetEntry * entry) static
References az_value_get_inst(), and elem_ptr().
Referenced by az_hash_set_contains(), az_hash_set_forall(), az_hash_set_insert(), az_hash_set_remove(), az_hash_set_remove_all(), and reallocate().
elem_ptr()
static AZValue * elem_ptr (const AZHashSetImplementation * impl, AZHashSetEntry * entry) static
Referenced by clear_entry(), elem_inst(), hset_get_element(), and set_entry().
entry_ptr()
static AZHashSetEntry * entry_ptr (const AZHashSetImplementation * impl, AZHashSetEntry * entries, unsigned int pos) static
Referenced by az_hash_set_clear(), az_hash_set_contains(), az_hash_set_forall(), az_hash_set_insert(), az_hash_set_remove(), az_hash_set_remove_all(), hset_get_element(), hset_get_iter(), hset_instance_finalize(), hset_iter_next(), and reallocate().
hset_contains()
static unsigned int hset_contains (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZImplementation * impl, const void * inst) static
References az_hash_set_contains().
Referenced by hset_implementation_init().
hset_get_element()
static const AZImplementation * hset_get_element (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZValue * iter, AZValue * val, unsigned int size) static
References az_value_copy_autobox(), elem_ptr(), and entry_ptr().
Referenced by hset_implementation_init().
hset_get_element_type()
static unsigned int hset_get_element_type (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst) static
References AZ_IMPL_TYPE.
Referenced by hset_implementation_init().
hset_get_iter()
static const AZImplementation * hset_get_iter (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) static
References AZUint64Klass, EMPTY, and entry_ptr().
Referenced by hset_implementation_init().
hset_implementation_init()
static void hset_implementation_init (AZHashSetImplementation * impl) static
References hset_contains(), hset_get_element(), hset_get_element_type(), hset_get_iter(), and hset_iter_next().
Referenced by az_hash_set_get_type().
hset_instance_finalize()
static void hset_instance_finalize (const AZHashSetImplementation * impl, AZHashSet * hset) static
References aligned_free, clear_entry(), EMPTY, END, and entry_ptr().
Referenced by az_hash_set_get_type().
hset_instance_init()
static void hset_instance_init (const AZHashSetImplementation * impl, AZHashSet * hset) static
References allocate_entries().
Referenced by az_hash_set_get_type().
hset_iter_next()
static const AZImplementation * hset_iter_next (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter) static
References AZUint64Klass, EMPTY, END, and entry_ptr().
Referenced by hset_implementation_init().
reallocate()
static void reallocate (const AZHashSetImplementation * impl, AZHashSet * hset, unsigned int new_root_size) static
References aligned_free, allocate_entries(), elem_inst(), EMPTY, END, and entry_ptr().
Referenced by az_hash_set_insert().
set_entry()
static void set_entry (const AZHashSetImplementation * impl, AZHashSetEntry * entry, unsigned int next, void * elem) static
References az_value_set_from_inst(), and elem_ptr().
Referenced by az_hash_set_insert().
Variable Documentation
hset_class
AZHashSetClass* hset_class static
Referenced by az_hash_set_get_type().
hset_type
unsigned int hset_type = 0 static
Referenced by az_hash_set_get_type().