az: input-stream.c File Reference
input-stream.c File Reference
#include <stdlib.h>
#include <az/base.h>
#include <az/types.h>
#include <az/private.h>
#include <az/io/input-stream.h>
Macros
#define __AZ_INPUT_STREAM_C__
#define COPY_BUFFER_SIZE 4096
Functions
void az_init_input_stream_class (void)
int64_t az_input_stream_skip (const AZInputStreamImplementation *impl, AZInputStream *inst, uint64_t n_bytes)
int64_t az_input_stream_read_all (const AZInputStreamImplementation *impl, AZInputStream *inst, uint8_t **data)
Variables
AZInterfaceClass AZInputStreamKlass
Macro Definition Documentation
__AZ_INPUT_STREAM_C__
#define __AZ_INPUT_STREAM_C__
COPY_BUFFER_SIZE
#define COPY_BUFFER_SIZE 4096
Function Documentation
az_init_input_stream_class()
void az_init_input_stream_class (void)
References az_class_new_with_value(), and AZInputStreamKlass.
Referenced by az_init().
az_input_stream_read_all()
int64_t az_input_stream_read_all (const AZInputStreamImplementation * impl, AZInputStream * inst, uint8_t ** data)
References az_input_stream_read(), AZ_OUT_OF_MEMORY, and COPY_BUFFER_SIZE.
az_input_stream_skip()
int64_t az_input_stream_skip (const AZInputStreamImplementation * impl, AZInputStream * inst, uint64_t n_bytes)
References az_input_stream_read(), and AZ_OK.
Variable Documentation
AZInputStreamKlass
AZInterfaceClass AZInputStreamKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_IDX_OUTPUT_STREAM},
    &AZInterfaceKlass.klass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "input stream",
    3, sizeof(AZInterfaceKlass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL},
    sizeof(AZInputStreamImplementation), NULL
}
Referenced by az_init_input_stream_class().