az: input-stream.h File Reference
input-stream.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <az/interface.h>
Data Structures
struct AZInputStreamImplementation
Functions
static int64_t az_input_stream_read (const AZInputStreamImplementation *impl, AZInputStream *inst, void *data, uint64_t size)
static int64_t az_input_stream_seek (const AZInputStreamImplementation *impl, AZInputStream *inst, uint64_t offset)
int64_t az_input_stream_skip (const AZInputStreamImplementation *impl, AZInputStream *inst, uint64_t n_bytes)
static int az_input_stream_is_eof (const AZInputStreamImplementation *impl, AZInputStream *inst)
static int az_input_stream_is_error (const AZInputStreamImplementation *impl, AZInputStream *inst)
int64_t az_input_stream_read_all (const AZInputStreamImplementation *impl, AZInputStream *inst, uint8_t **data)
Function Documentation
az_input_stream_is_eof()
static int az_input_stream_is_eof (const AZInputStreamImplementation * impl, AZInputStream * inst) inline static
az_input_stream_is_error()
static int az_input_stream_is_error (const AZInputStreamImplementation * impl, AZInputStream * inst) inline static
az_input_stream_read()
static int64_t az_input_stream_read (const AZInputStreamImplementation * impl, AZInputStream * inst, void * data, uint64_t size) inline static
Referenced by az_input_stream_read_all(), az_input_stream_skip(), az_stream_copy(), and az_stream_copy_all().
az_input_stream_read_all()
int64_t az_input_stream_read_all (const AZInputStreamImplementation * impl, AZInputStream * inst, uint8_t ** data)
References az_input_stream_read(), AZ_OUT_OF_MEMORY, and COPY_BUFFER_SIZE.
az_input_stream_seek()
static int64_t az_input_stream_seek (const AZInputStreamImplementation * impl, AZInputStream * inst, uint64_t offset) inline static
References AZ_NOT_IMPLEMENTED.
az_input_stream_skip()
int64_t az_input_stream_skip (const AZInputStreamImplementation * impl, AZInputStream * inst, uint64_t n_bytes)
References az_input_stream_read(), and AZ_OK.