az: instance.c File Reference
instance.c File Reference
#include <stdlib.h>
#include <string.h>
#include <az/base.h>
#include <az/boxed-interface.h>
#include <az/boxed-value.h>
#include <az/class.h>
#include <az/field.h>
#include <az/function.h>
#include <az/instance.h>
#include <az/object.h>
#include <az/types.h>
Macros
#define __AZ_INSTANCE_C__
Functions
void az_instance_init_recursive (const AZClass *klass, const AZImplementation *impl, void *inst, unsigned int zeroed)
void az_instance_finalize_recursive (const AZClass *klass, const AZImplementation *impl, void *inst)
void az_instance_init (const AZImplementation *impl, void *inst)
initialize a new instance
void az_instance_finalize (const AZImplementation *impl, void *inst)
destroy an instance
void * az_instance_new (unsigned int type)
void * az_instance_new_array (unsigned int type, unsigned int nelements)
void az_instance_delete (unsigned int type, void *instance)
void az_instance_delete_array (unsigned int type, void *elements, unsigned int nelements)
unsigned int az_instance_serialize (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
unsigned int az_instance_to_string (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen)
writes a string representation of instance to the buffer
const AZImplementation * az_instance_get_interface (const AZImplementation *impl, void *inst, unsigned int if_type, void **if_inst)
unsigned int az_instance_get_property_by_key (const AZImplementation *impl, void *inst, const unsigned char *key, const AZImplementation **dst_impl, AZValue64 *dst_val)
Get property from instance.
unsigned int az_instance_get_function_by_key (const AZImplementation *impl, void *inst, const unsigned char *key, AZFunctionSignature *sig, const AZImplementation **dst_impl, AZValue *dst_val)
unsigned int az_instance_set_property_by_key (const AZImplementation *impl, void *inst, const unsigned char *key, const AZImplementation *prop_impl, void *prop_inst, AZContext *ctx)
Macro Definition Documentation
__AZ_INSTANCE_C__
#define __AZ_INSTANCE_C__
Function Documentation
az_instance_delete()
void az_instance_delete (unsigned int type, void * instance)
References az_instance_finalize_recursive(), az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, and az_type_is_a().
Referenced by az_array_list_delete(), az_function_signature_delete(), az_reference_dispose(), and az_reference_drop().
az_instance_delete_array()
void az_instance_delete_array (unsigned int type, void * elements, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, az_instance_finalize_recursive(), az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, and az_type_is_a().
az_instance_finalize()
void az_instance_finalize (const AZImplementation * impl, void * inst)
destroy an instance
Destroys an type instance. The order of operations is: If AZ_FLAG CONSTRUCT is set, call:
instance_finalize virtual method
destructos of all interfaces
the superclass destructor
Parameters
impl type implementation
inst type instance
References AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_ABSTRACT, AZ_FLAG_CONSTRUCT, and az_instance_finalize_recursive().
Referenced by az_instance_finalize_by_type().
az_instance_finalize_recursive()
void az_instance_finalize_recursive (const AZClass * klass, const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_TYPE, az_class_iface_self(), AZ_CLASS_TYPE, az_instance_finalize_recursive(), AZ_NUM_FUNDAMENTAL_TYPES, and AZ_TYPE_INDEX.
Referenced by az_instance_delete(), az_instance_delete_array(), az_instance_finalize(), and az_instance_finalize_recursive().
az_instance_get_function_by_key()
unsigned int az_instance_get_function_by_key (const AZImplementation * impl, void * inst, const unsigned char * key, AZFunctionSignature * sig, const AZImplementation ** dst_impl, AZValue * dst_val)
References AZ_CLASS_FROM_IMPL, az_class_lookup_function(), and az_string_new().
az_instance_get_interface()
const AZImplementation * az_instance_get_interface (const AZImplementation * impl, void * inst, unsigned int if_type, void ** if_inst)
References AZ_BOXED_INTERFACE_IMPL, AZ_CLASS_FROM_IMPL, az_class_iface_all(), AZ_IMPL_TYPE, and az_type_is_a().
Referenced by az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_function_invoke_by_type_instance(), az_function_invoke_by_value_signature_va(), az_instance_get_interface_from_type(), az_instance_invoke_function(), az_object_get_interface(), and az_type_implements().
az_instance_get_property_by_key()
unsigned int az_instance_get_property_by_key (const AZImplementation * impl, void * inst, const unsigned char * key, const AZImplementation ** dst_impl, AZValue64 * dst_val)
Get property from instance.
Parameters
impl the type implementation
inst the type instance
key property key
dst_impl the result implementation
dst_val the result value
Returns
1 if successfule, 0 if not
References AZ_CLASS_FROM_IMPL, az_class_lookup_property(), az_string_new(), and az_string_unref().
az_instance_init()
void az_instance_init (const AZImplementation * impl, void * inst)
initialize a new instance
Initializes a new type instance. The order of operations is: If AZ_FLAG_ZERO_MEMORY is set clear instance memoery. If AZ_FLAG CONSTRUCT is set, call:
the superclass constructor
constructors of all interfaces
instance_init virtual method
Parameters
impl type implementation
inst uninitialized instance
References AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_ABSTRACT, AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, and az_instance_init_recursive().
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_boxed_value_new(), az_instance_init_by_type(), and az_value_init_autobox().
az_instance_init_recursive()
void az_instance_init_recursive (const AZClass * klass, const AZImplementation * impl, void * inst, unsigned int zeroed)
References AZ_CLASS_FROM_TYPE, az_class_iface_self(), AZ_CLASS_TYPE, AZ_FLAG_ZERO_MEMORY, az_instance_init_recursive(), AZ_NUM_FUNDAMENTAL_TYPES, and AZ_TYPE_INDEX.
Referenced by az_instance_init(), az_instance_init_recursive(), az_instance_new(), and az_instance_new_array().
az_instance_new()
void * az_instance_new (unsigned int type)
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, AZ_FLAG_ZERO_MEMORY, az_instance_init_recursive(), az_num_types, AZ_TYPE_INDEX, AZ_TYPE_INTERFACE, and az_type_is_a().
Referenced by az_array_list_new(), az_object_new(), az_packed_value_array_new(), az_reference_of_new(), az_reference_of_new_value(), and az_value_array_ref_new().
az_instance_new_array()
void * az_instance_new_array (unsigned int type, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, AZ_FLAG_ZERO_MEMORY, az_instance_init_recursive(), az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, and az_type_is_a().
Referenced by az_packed_value_array_new().
az_instance_serialize()
unsigned int az_instance_serialize (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx)
References AZ_CLASS_FROM_IMPL.
Referenced by array_serialize(), serialize_boxed_interface(), and serialize_boxed_value().
az_instance_set_property_by_key()
unsigned int az_instance_set_property_by_key (const AZImplementation * impl, void * inst, const unsigned char * key, const AZImplementation * prop_impl, void * prop_inst, AZContext * ctx)
References AZ_CLASS_FROM_IMPL, az_class_lookup_property(), az_string_new(), and az_string_unref().
az_instance_to_string()
unsigned int az_instance_to_string (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen)
writes a string representation of instance to the buffer
Returns the number of content bytes (excluding the terminating 0) Unless len == 0, terminating 0 is always written
Parameters
impl type implementation
inst type instance
d destination buffer
dlen destination buffer size
Returns
the content length (can be > dlen, not counting terminating 0)
References AZ_CLASS_FROM_IMPL.
Referenced by boxed_value_to_string(), and reference_of_to_string().