az: interface.c File Reference
interface.c File Reference
#include <stdlib.h>
#include <arikkei/arikkei-utils.h>
#include <az/base.h>
#include <az/interface.h>
#include <az/private.h>
#include <az/extend.h>
Macros
#define __AZ_INTERFACE_C__
Functions
AZInterfaceClass * az_register_interface_type (unsigned int *type, const unsigned char *name, unsigned int parent, unsigned int class_size, unsigned int impl_size, unsigned int inst_size, unsigned int flags, void(*class_init)(AZClass *), void(*implementation_init)(AZImplementation *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
void az_init_interface_class (void)
static void implementation_init_recursive (AZInterfaceClass *ifclass, AZImplementation *impl)
void az_implementation_init_by_type (AZImplementation *impl, unsigned int type)
Variables
AZInterfaceClass AZInterfaceKlass
Macro Definition Documentation
__AZ_INTERFACE_C__
#define __AZ_INTERFACE_C__
Function Documentation
az_implementation_init_by_type()
void az_implementation_init_by_type (AZImplementation * impl, unsigned int type)
References AZ_CLASS_FROM_TYPE, az_num_types, AZ_TYPE_IS_INTERFACE, and implementation_init_recursive().
Referenced by array_object_instance_init(), attrib_dict_impl_init(), az_array_impl_init(), and az_class_declare_interface().
az_init_interface_class()
void az_init_interface_class (void)
References az_class_new_with_value(), and AZInterfaceKlass.
Referenced by az_init().
az_register_interface_type()
AZInterfaceClass * az_register_interface_type (unsigned int * type, const unsigned char * name, unsigned int parent, unsigned int class_size, unsigned int impl_size, unsigned int inst_size, unsigned int flags, void(*)(AZClass *) class_init, void(*)(AZImplementation *) implementation_init, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize)
References AZ_CLASS_FROM_TYPE, az_register_type(), AZ_TYPE_INTERFACE, and az_type_is_a().
Referenced by az_array_get_type(), az_attrib_dict_get_type(), az_collection_get_type(), az_list_get_type(), and az_map_get_type().
implementation_init_recursive()
static void implementation_init_recursive (AZInterfaceClass * ifclass, AZImplementation * impl) static
References AZ_CLASS_FROM_TYPE, az_class_ifaces_self(), AZ_CLASS_IS_INTERFACE, and implementation_init_recursive().
Referenced by az_implementation_init_by_type(), and implementation_init_recursive().
Variable Documentation
AZInterfaceKlass
AZInterfaceClass AZInterfaceKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_INTERFACE | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_INTERFACE},
    &AZBlockKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "interface",
    3, sizeof(AZInterfaceClass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL},
    sizeof(AZImplementation), NULL
}
Referenced by az_init_interface_class().