az: interface-list.c File Reference
interface-list.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <az/value.h>
#include <az/extend.h>
#include "interface-list.h"
Macros
#define __AZ_INTERFACE_LIST_C__
Functions
static void interface_list_class_init (AZInterfaceListClass *klass)
static void interface_list_init (AZInterfaceListClass *klass, AZInterfaceList *ifl)
static void interface_list_finalize (AZInterfaceListClass *klass, AZInterfaceList *ifl)
static unsigned int interface_list_get_element_type (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int interface_list_get_size (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int interface_list_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * interface_list_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
static unsigned int interface_list_call_lookUp (AZPackedValue *thisval, AZPackedValue *retval, AZPackedValue *args)
unsigned int az_interface_list_get_type (void)
void az_interface_list_setup (AZInterfaceList *ifl, unsigned int iface_type)
void az_interface_list_release (AZInterfaceList *ifl)
AZInterfaceList * az_interface_list_new (unsigned int iface_type)
void az_interface_list_delete (AZInterfaceList *ifl)
void az_interface_list_append (AZInterfaceList *ifl, AZImplementation *impl, void *inst)
void az_interface_list_remove (AZInterfaceList *ifl, void *inst)
void az_interface_list_remove_by_index (AZInterfaceList *ifl, unsigned int idx)
void az_interface_list_clear (AZInterfaceList *ifl)
unsigned int az_interface_list_contains (AZInterfaceList *ifl, void *inst)
Variables
static unsigned int interface_list_type = 0
Macro Definition Documentation
__AZ_INTERFACE_LIST_C__
#define __AZ_INTERFACE_LIST_C__
Function Documentation
az_interface_list_append()
void az_interface_list_append (AZInterfaceList * ifl, AZImplementation * impl, void * inst)
References AZ_IMPL_TYPE, and az_type_is_a().
az_interface_list_clear()
void az_interface_list_clear (AZInterfaceList * ifl)
az_interface_list_contains()
unsigned int az_interface_list_contains (AZInterfaceList * ifl, void * inst)
az_interface_list_delete()
void az_interface_list_delete (AZInterfaceList * ifl)
References az_interface_list_release().
az_interface_list_get_type()
unsigned int az_interface_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_STRUCT, interface_list_class_init(), interface_list_finalize(), interface_list_init(), and interface_list_type.
az_interface_list_new()
AZInterfaceList * az_interface_list_new (unsigned int iface_type)
References az_interface_list_setup(), AZ_TYPE_INTERFACE, and az_type_is_a().
az_interface_list_release()
void az_interface_list_release (AZInterfaceList * ifl)
References az_instance_finalize_by_type(), and AZ_TYPE_INTERFACE_LIST.
Referenced by az_interface_list_delete().
az_interface_list_remove()
void az_interface_list_remove (AZInterfaceList * ifl, void * inst)
References az_interface_list_remove_by_index().
az_interface_list_remove_by_index()
void az_interface_list_remove_by_index (AZInterfaceList * ifl, unsigned int idx)
Referenced by az_interface_list_remove().
az_interface_list_setup()
void az_interface_list_setup (AZInterfaceList * ifl, unsigned int iface_type)
References az_instance_init_by_type(), AZ_TYPE_INTERFACE, AZ_TYPE_INTERFACE_LIST, and az_type_is_a().
Referenced by az_interface_list_new().
interface_list_call_lookUp()
static unsigned int interface_list_call_lookUp (AZPackedValue * thisval, AZPackedValue * retval, AZPackedValue * args) static
interface_list_class_init()
static void interface_list_class_init (AZInterfaceListClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_TYPE_LIST, interface_list_contains(), interface_list_get_element(), interface_list_get_element_type(), and interface_list_get_size().
Referenced by az_interface_list_get_type().
interface_list_contains()
static unsigned int interface_list_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
Referenced by interface_list_class_init().
interface_list_finalize()
static void interface_list_finalize (AZInterfaceListClass * klass, AZInterfaceList * ifl) static
Referenced by az_interface_list_get_type().
interface_list_get_element()
static const AZImplementation * interface_list_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
Referenced by interface_list_class_init().
interface_list_get_element_type()
static unsigned int interface_list_get_element_type (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by interface_list_class_init().
interface_list_get_size()
static unsigned int interface_list_get_size (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by interface_list_class_init().
interface_list_init()
static void interface_list_init (AZInterfaceListClass * klass, AZInterfaceList * ifl) static
Referenced by az_interface_list_get_type().
Variable Documentation
interface_list_type
unsigned int interface_list_type = 0 static
Referenced by az_interface_list_get_type().