az: interface.h File Reference
interface.h File Reference
#include <az/class.h>
Data Structures
struct AZInterfaceValue
struct AZInterfaceClass
An abstract base class of all interface types.
Functions
AZInterfaceClass * az_register_interface_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int implementation_size, unsigned int instance_size, unsigned int flags, void(*class_init)(AZClass *), void(*implementation_init)(AZImplementation *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
Get new typecode, allocate and initialize a class structure.
void az_implementation_init_by_type (AZImplementation *impl, unsigned int type)
Variables
AZInterfaceClass AZInterfaceKlass
Function Documentation
az_implementation_init_by_type()
void az_implementation_init_by_type (AZImplementation * impl, unsigned int type)
References AZ_CLASS_FROM_TYPE, az_num_types, AZ_TYPE_IS_INTERFACE, and implementation_init_recursive().
Referenced by attrib_dict_impl_init(), and az_class_declare_interface().
az_register_interface_type()
AZInterfaceClass * az_register_interface_type (unsigned int * type, const unsigned char * name, unsigned int parent_type, unsigned int class_size, unsigned int implementation_size, unsigned int instance_size, unsigned int flags, void(*)(AZClass *) class_init, void(*)(AZImplementation *) implementation_init, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize)
Get new typecode, allocate and initialize a class structure.
Gets a new typecode, initializes its class to the minimal functional state and then calls class_init, where a more specialized setup (e.g. registering interfaces and fields) should be done. The final setup is performed only after class_init returns (and thus the sub-interfaces and fields are known).
Parameters
type pointer where the typecode will be written
name the name of the new type
parent_type the parent typecode
class_size the size of the class
implementation_size the size of the implementation
instance_size the size of the instance
flags type flags
class_init the class constructor
implementation_init the implementation constructor
instance_init the instance constructor
instance_finalize the instance destructor
Returns
allocated and initialized class
References AZ_CLASS_FROM_TYPE, az_register_type(), AZ_TYPE_INTERFACE, and az_type_is_a().
Referenced by az_attrib_dict_get_type(), az_collection_get_type(), az_list_get_type(), and az_map_get_type().
Variable Documentation
AZInterfaceKlass
AZInterfaceClass AZInterfaceKlass extern
Referenced by az_init_interface_class().