az: interface-list.h File Reference
interface-list.h File Reference
#include <az/collections/list.h>
Data Structures
struct AZInterfaceList
struct AZInterfaceListClass
Macros
#define AZ_TYPE_INTERFACE_LIST (az_interface_list_get_type ())
Functions
unsigned int az_interface_list_get_type (void)
void az_interface_list_setup (AZInterfaceList *ifl, unsigned int iface_type)
void az_interface_list_release (AZInterfaceList *ifl)
AZInterfaceList * az_interface_list_new (unsigned int iface_type)
void az_interface_list_delete (AZInterfaceList *ifl)
void az_interface_list_append (AZInterfaceList *ifl, AZImplementation *impl, void *inst)
void az_interface_list_remove (AZInterfaceList *ifl, void *inst)
void az_interface_list_remove_by_index (AZInterfaceList *ifl, unsigned int idx)
void az_interface_list_clear (AZInterfaceList *ifl)
unsigned int az_interface_list_contains (AZInterfaceList *ifl, void *inst)
Macro Definition Documentation
AZ_TYPE_INTERFACE_LIST
#define AZ_TYPE_INTERFACE_LIST (az_interface_list_get_type ())
Function Documentation
az_interface_list_append()
void az_interface_list_append (AZInterfaceList * ifl, AZImplementation * impl, void * inst)
References AZ_IMPL_TYPE, and az_type_is_a().
az_interface_list_clear()
void az_interface_list_clear (AZInterfaceList * ifl)
az_interface_list_contains()
unsigned int az_interface_list_contains (AZInterfaceList * ifl, void * inst)
az_interface_list_delete()
void az_interface_list_delete (AZInterfaceList * ifl)
References az_interface_list_release().
az_interface_list_get_type()
unsigned int az_interface_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_STRUCT, interface_list_class_init(), interface_list_finalize(), interface_list_init(), and interface_list_type.
az_interface_list_new()
AZInterfaceList * az_interface_list_new (unsigned int iface_type)
References az_interface_list_setup(), AZ_TYPE_INTERFACE, and az_type_is_a().
az_interface_list_release()
void az_interface_list_release (AZInterfaceList * ifl)
References az_instance_finalize_by_type(), and AZ_TYPE_INTERFACE_LIST.
Referenced by az_interface_list_delete().
az_interface_list_remove()
void az_interface_list_remove (AZInterfaceList * ifl, void * inst)
References az_interface_list_remove_by_index().
az_interface_list_remove_by_index()
void az_interface_list_remove_by_index (AZInterfaceList * ifl, unsigned int idx)
Referenced by az_interface_list_remove().
az_interface_list_setup()
void az_interface_list_setup (AZInterfaceList * ifl, unsigned int iface_type)
References az_instance_init_by_type(), AZ_TYPE_INTERFACE, AZ_TYPE_INTERFACE_LIST, and az_type_is_a().
Referenced by az_interface_list_new().