az: list.h File Reference
list.h File Reference
#include <az/collections/collection.h>
Data Structures
struct AZListImplementation
struct AZListClass
Macros
#define AZ_TYPE_LIST (az_list_get_type ())
Functions
unsigned int az_list_get_type (void)
static const AZImplementation * az_list_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
Macro Definition Documentation
AZ_TYPE_LIST
#define AZ_TYPE_LIST (az_list_get_type ())
Function Documentation
az_list_get_element()
static const AZImplementation * az_list_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) inline static
Referenced by attrd_get_element(), attrd_get_key(), az_array_list_get_element(), list_get_element(), and value_array_ref_get_element().
az_list_get_type()
unsigned int az_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_COLLECTION, list_class, list_class_init(), list_implementation_init(), and list_type.