az: list.c File Reference
list.c File Reference
#include <stdlib.h>
#include <az/interface.h>
#include <az/packed-value.h>
#include <az/extend.h>
#include "list.h"
Macros
#define __AZ_LIST_C__
Enumerations
enum { PROP_LENGTH , NUM_PROPERTIES }
Functions
static void list_class_init (AZListClass *klass)
static void list_implementation_init (AZListImplementation *impl)
static unsigned int list_get_iterator (const AZCollectionImplementation *collection_impl, void *collection_inst, AZPackedValue *iterator)
static unsigned int list_iterator_next (const AZCollectionImplementation *collection_impl, void *collection_inst, AZPackedValue *iterator)
static const AZImplementation * list_get_element (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZPackedValue *iterator, AZValue *val, unsigned int size)
static unsigned int list_get_property (const AZImplementation *impl, void *inst, unsigned int idx, const AZImplementation **prop_impl, AZValue *prop_val, AZContext *ctx)
unsigned int az_list_get_type (void)
Variables
static unsigned int list_type = 0
static AZListClass * list_class
Macro Definition Documentation
__AZ_LIST_C__
#define __AZ_LIST_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_LENGTH
NUM_PROPERTIES
Function Documentation
az_list_get_type()
unsigned int az_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_COLLECTION, list_class, list_class_init(), list_implementation_init(), and list_type.
list_class_init()
static void list_class_init (AZListClass * klass) static
References AZ_FIELD_INSTANCE, AZ_FIELD_READ_METHOD, AZ_TYPE_UINT32, list_get_property(), NUM_PROPERTIES, and PROP_LENGTH.
Referenced by az_list_get_type().
list_get_element()
static const AZImplementation * list_get_element (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZPackedValue * iterator, AZValue * val, unsigned int size) static
References az_list_get_element().
Referenced by list_implementation_init().
list_get_iterator()
static unsigned int list_get_iterator (const AZCollectionImplementation * collection_impl, void * collection_inst, AZPackedValue * iterator) static
References az_packed_value_set_unsigned_int(), and AZ_TYPE_UINT32.
Referenced by list_implementation_init().
list_get_property()
static unsigned int list_get_property (const AZImplementation * impl, void * inst, unsigned int idx, const AZImplementation ** prop_impl, AZValue * prop_val, AZContext * ctx) static
References az_collection_get_size(), az_type_get_class, and AZ_TYPE_UINT32.
Referenced by list_class_init().
list_implementation_init()
static void list_implementation_init (AZListImplementation * impl) static
References list_get_element(), list_get_iterator(), and list_iterator_next().
Referenced by az_list_get_type().
list_iterator_next()
static unsigned int list_iterator_next (const AZCollectionImplementation * collection_impl, void * collection_inst, AZPackedValue * iterator) static
References az_collection_get_size().
Referenced by list_implementation_init().
Variable Documentation
list_class
AZListClass* list_class static
Referenced by az_list_get_type().
list_type
unsigned int list_type = 0 static
Referenced by az_list_get_type().