az: map.h File Reference
map.h File Reference
#include <az/collections/set.h>
Data Structures
struct AZMap
struct AZMapImplementation
struct AZMapClass
Macros
#define AZ_TYPE_MAP (az_map_get_type ())
Functions
unsigned int az_map_get_type (void)
static const AZSetImplementation * az_map_get_keys (const AZMapImplementation *map_impl, AZMap *map_inst, AZSet **inst)
static unsigned int az_map_get_key_type (const AZMapImplementation *map_impl, AZMap *map_inst)
static const AZImplementation * az_map_get_key (const AZMapImplementation *map_impl, AZMap *map_inst, const AZValue *iter, AZValue *val, unsigned int size)
static unsigned int az_map_contains_key (const AZMapImplementation *map_impl, AZMap *map_inst, const AZImplementation *key_impl, const void *key_inst)
static const AZImplementation * az_map_lookup (const AZMapImplementation *map_impl, AZMap *map_inst, const AZImplementation *key_impl, void *key_inst, AZValue *val, unsigned int size)
Macro Definition Documentation
AZ_TYPE_MAP
#define AZ_TYPE_MAP (az_map_get_type ())
Function Documentation
az_map_contains_key()
static unsigned int az_map_contains_key (const AZMapImplementation * map_impl, AZMap * map_inst, const AZImplementation * key_impl, const void * key_inst) inline static
References key_inst().
az_map_get_key()
static const AZImplementation * az_map_get_key (const AZMapImplementation * map_impl, AZMap * map_inst, const AZValue * iter, AZValue * val, unsigned int size) inline static
az_map_get_key_type()
static unsigned int az_map_get_key_type (const AZMapImplementation * map_impl, AZMap * map_inst) inline static
az_map_get_keys()
static const AZSetImplementation * az_map_get_keys (const AZMapImplementation * map_impl, AZMap * map_inst, AZSet ** inst) inline static
az_map_get_type()
unsigned int az_map_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_COLLECTION, map_class, map_implementation_init(), and map_type.
az_map_lookup()
static const AZImplementation * az_map_lookup (const AZMapImplementation * map_impl, AZMap * map_inst, const AZImplementation * key_impl, void * key_inst, AZValue * val, unsigned int size) inline static
References key_inst().