az: map.c File Reference
map.c File Reference
#include <stdlib.h>
#include <az/field.h>
#include <az/interface.h>
#include <az/packed-value.h>
#include "map.h"
Macros
#define __AZ_MAP_C__
Functions
static void map_implementation_init (AZMapImplementation *impl)
unsigned int keyset_get_element_type (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst)
unsigned int keyset_contains (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZImplementation *val_impl, const void *val_inst)
const AZImplementation * keyset_get_iterator (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
const AZImplementation * keyset_iterator_next (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, AZValue *iter)
const AZImplementation * keyset_get_element (const AZCollectionImplementation *coll_impl, AZCollection *coll_inst, const AZValue *iter, AZValue *val, unsigned int size)
unsigned int az_map_get_type (void)
Variables
static unsigned int map_type = 0
static AZMapClass * map_class
Macro Definition Documentation
__AZ_MAP_C__
#define __AZ_MAP_C__
Function Documentation
az_map_get_type()
unsigned int az_map_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_interface_type(), AZ_TYPE_COLLECTION, map_class, map_implementation_init(), and map_type.
keyset_contains()
unsigned int keyset_contains (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZImplementation * val_impl, const void * val_inst)
References val_inst().
Referenced by map_implementation_init().
keyset_get_element()
const AZImplementation * keyset_get_element (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, const AZValue * iter, AZValue * val, unsigned int size)
Referenced by map_implementation_init().
keyset_get_element_type()
unsigned int keyset_get_element_type (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst)
Referenced by map_implementation_init().
keyset_get_iterator()
const AZImplementation * keyset_get_iterator (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter)
Referenced by map_implementation_init().
keyset_iterator_next()
const AZImplementation * keyset_iterator_next (const AZCollectionImplementation * coll_impl, AZCollection * coll_inst, AZValue * iter)
Referenced by map_implementation_init().
map_implementation_init()
static void map_implementation_init (AZMapImplementation * impl) static
References az_implementation_init_by_type(), AZ_TYPE_SET, keyset_contains(), keyset_get_element(), keyset_get_element_type(), keyset_get_iterator(), and keyset_iterator_next().
Referenced by az_map_get_type().
Variable Documentation
map_class
AZMapClass* map_class static
Referenced by az_map_get_type().
map_type
unsigned int map_type = 0 static
Referenced by az_map_get_type().