az: memory-output-stream.c File Reference
memory-output-stream.c File Reference
#include <stdlib.h>
#include <string.h>
#include <az/extend.h>
#include <az/types.h>
#include <az/io/memory-output-stream.h>
Macros
#define __AZ_MEMORY_OUTPUT_STREAM_C__
#define MIN_ALLOC 256
Functions
static void mostream_class_init (AZMemoryOutputStreamClass *klass)
static int64_t mostream_write (const AZOutputStreamImplementation *impl, AZOutputStream *inst, const void *data, uint64_t size)
static int64_t mostream_close (const AZOutputStreamImplementation *impl, AZOutputStream *inst)
unsigned int az_memory_output_stream_get_type (void)
Variables
unsigned int mostream_type = 0
AZMemoryOutputStreamClass * mostream_class = NULL
Macro Definition Documentation
__AZ_MEMORY_OUTPUT_STREAM_C__
#define __AZ_MEMORY_OUTPUT_STREAM_C__
MIN_ALLOC
#define MIN_ALLOC 256
Function Documentation
az_memory_output_stream_get_type()
unsigned int az_memory_output_stream_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_STRUCT, mostream_class, mostream_class_init(), and mostream_type.
mostream_class_init()
static void mostream_class_init (AZMemoryOutputStreamClass * klass) static
References az_class_declare_interface(), AZ_TYPE_OUTPUT_STREAM, mostream_close(), and mostream_write().
Referenced by az_memory_output_stream_get_type().
mostream_close()
static int64_t mostream_close (const AZOutputStreamImplementation * impl, AZOutputStream * inst) static
References AZ_OK, and AZ_OUT_OF_MEMORY.
Referenced by mostream_class_init().
mostream_write()
static int64_t mostream_write (const AZOutputStreamImplementation * impl, AZOutputStream * inst, const void * data, uint64_t size) static
References AZ_OUT_OF_MEMORY, and MIN_ALLOC.
Referenced by mostream_class_init().
Variable Documentation
mostream_class
AZMemoryOutputStreamClass* mostream_class = NULL
Referenced by az_memory_output_stream_get_type().
mostream_type
unsigned int mostream_type = 0
Referenced by az_memory_output_stream_get_type().