az: object-interface-list.c File Reference
object-interface-list.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <az/extend.h>
#include "object-interface-list.h"
Macros
#define __AZ_OBJECT_INTERFACE_LIST_CPP__
Functions
static void object_interface_list_class_init (AZObjectInterfaceListClass *klass)
static void object_interface_list_init (AZObjectInterfaceListClass *klass, AZObjectInterfaceList *objifl)
static void object_interface_list_finalize (AZObjectInterfaceListClass *klass, AZObjectInterfaceList *objifl)
static unsigned int object_interface_list_get_element_type (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int object_interface_list_get_size (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int object_interface_list_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * object_interface_list_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
static unsigned int object_interface_list_call_lookUp (AZPackedValue *thisval, AZPackedValue *retval, AZPackedValue *args)
unsigned int az_object_interface_list_get_type (void)
void az_object_interface_list_setup (AZObjectInterfaceList *objifl, unsigned int object_type, unsigned int interface_type)
void az_object_interface_list_release (AZObjectInterfaceList *objifl)
AZObjectInterfaceList * az_object_interface_list_new (unsigned int object_type, unsigned int interface_type)
void az_object_interface_list_delete (AZObjectInterfaceList *objifl)
void az_object_interface_list_append_object (AZObjectInterfaceList *objifl, AZObject *obj)
void az_object_interface_list_remove_object (AZObjectInterfaceList *objifl, AZObject *obj)
void az_object_interface_list_remove_object_by_index (AZObjectInterfaceList *objifl, unsigned int idx)
void az_object_interface_list_clear (AZObjectInterfaceList *objifl)
unsigned int az_object_interface_list_contains (AZObjectInterfaceList *objifl, AZObject *obj)
Variables
static unsigned int object_interface_list_type = 0
Macro Definition Documentation
__AZ_OBJECT_INTERFACE_LIST_CPP__
#define __AZ_OBJECT_INTERFACE_LIST_CPP__
Function Documentation
az_object_interface_list_append_object()
void az_object_interface_list_append_object (AZObjectInterfaceList * objifl, AZObject * obj)
References az_object_get_interface(), az_object_implements(), az_object_is_a, and az_object_ref().
az_object_interface_list_clear()
void az_object_interface_list_clear (AZObjectInterfaceList * objifl)
References az_object_unref().
az_object_interface_list_contains()
unsigned int az_object_interface_list_contains (AZObjectInterfaceList * objifl, AZObject * obj)
References az_object_implements(), and az_object_is_a.
az_object_interface_list_delete()
void az_object_interface_list_delete (AZObjectInterfaceList * objifl)
References az_object_interface_list_release().
az_object_interface_list_get_type()
unsigned int az_object_interface_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_STRUCT, object_interface_list_class_init(), object_interface_list_finalize(), object_interface_list_init(), and object_interface_list_type.
az_object_interface_list_new()
AZObjectInterfaceList * az_object_interface_list_new (unsigned int object_type, unsigned int interface_type)
References az_object_interface_list_setup(), AZ_TYPE_INTERFACE, az_type_is_a(), and AZ_TYPE_OBJECT.
az_object_interface_list_release()
void az_object_interface_list_release (AZObjectInterfaceList * objifl)
References az_instance_finalize_by_type(), and AZ_TYPE_OBJECT_INTERFACE_LIST.
Referenced by az_object_interface_list_delete().
az_object_interface_list_remove_object()
void az_object_interface_list_remove_object (AZObjectInterfaceList * objifl, AZObject * obj)
References az_object_implements(), az_object_interface_list_remove_object_by_index(), and az_object_is_a.
az_object_interface_list_remove_object_by_index()
void az_object_interface_list_remove_object_by_index (AZObjectInterfaceList * objifl, unsigned int idx)
References az_object_unref().
Referenced by az_object_interface_list_remove_object().
az_object_interface_list_setup()
void az_object_interface_list_setup (AZObjectInterfaceList * objifl, unsigned int object_type, unsigned int interface_type)
References az_instance_init_by_type(), AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_OBJECT, and AZ_TYPE_OBJECT_INTERFACE_LIST.
Referenced by az_object_interface_list_new().
object_interface_list_call_lookUp()
static unsigned int object_interface_list_call_lookUp (AZPackedValue * thisval, AZPackedValue * retval, AZPackedValue * args) static
object_interface_list_class_init()
static void object_interface_list_class_init (AZObjectInterfaceListClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_TYPE_LIST, object_interface_list_contains(), object_interface_list_get_element(), object_interface_list_get_element_type(), and object_interface_list_get_size().
Referenced by az_object_interface_list_get_type().
object_interface_list_contains()
static unsigned int object_interface_list_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
Referenced by object_interface_list_class_init().
object_interface_list_finalize()
static void object_interface_list_finalize (AZObjectInterfaceListClass * klass, AZObjectInterfaceList * objifl) static
References az_object_unref().
Referenced by az_object_interface_list_get_type().
object_interface_list_get_element()
static const AZImplementation * object_interface_list_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
Referenced by object_interface_list_class_init().
object_interface_list_get_element_type()
static unsigned int object_interface_list_get_element_type (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by object_interface_list_class_init().
object_interface_list_get_size()
static unsigned int object_interface_list_get_size (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by object_interface_list_class_init().
object_interface_list_init()
static void object_interface_list_init (AZObjectInterfaceListClass * klass, AZObjectInterfaceList * objifl) static
Referenced by az_object_interface_list_get_type().
Variable Documentation
object_interface_list_type
unsigned int object_interface_list_type = 0 static
Referenced by az_object_interface_list_get_type().