az: object.h File Reference
object.h File Reference
#include <stdlib.h>
#include <az/reference.h>
Data Structures
struct AZObject
struct AZObjectClass
Macros
#define AZ_OBJECT(o) (AZ_CHECK_INSTANCE_CAST ((o), AZ_TYPE_OBJECT, AZObject))
#define AZ_IS_OBJECT(o) (AZ_CHECK_INSTANCE_TYPE ((o), AZ_TYPE_OBJECT))
#define AZ_OBJECT_TYPE(o) AZ_CLASS_TYPE((AZClass *) ((AZObject *) o)->klass)
#define AZ_OBJECT_ALIVE 1
#define AZ_OBJECT_NUM_FLAGS 1
#define AZ_CLASS_FROM_OBJ(o) ((const AZClass *) (((AZObject *) o)->klass))
#define AZ_IMPL_FROM_OBJ(o) ((const AZImplementation *) (((AZObject *) o)->klass))
#define AZ_CHECK_INSTANCE_CAST(ip, tc, ct) ((ct *) az_object_check_instance_cast (ip, tc))
#define AZ_CHECK_INSTANCE_TYPE(ip, tc) az_object_check_instance_type (ip, tc)
#define az_object_is_a(obj, type) az_object_check_instance_type (obj, type)
Functions
static void az_object_ref (AZObject *obj)
static void az_object_unref (AZObject *obj)
void az_object_shutdown (AZObject *obj)
AZObject * az_object_new (unsigned int type)
void * az_object_check_instance_cast (void *inst, unsigned int type)
unsigned int az_object_check_instance_type (void *inst, unsigned int type)
unsigned int az_object_implements (AZObject *obj, unsigned int type)
const AZImplementation * az_object_get_interface (AZObject *obj, unsigned int type, void **inst)
ARIKKEI_INLINE void az_object_set_flags (AZObject *obj, unsigned int flags)
ARIKKEI_INLINE void az_object_clear_flags (AZObject *obj, unsigned int flags)
ARIKKEI_INLINE unsigned int az_object_flags (AZObject *obj, unsigned int flags)
ARIKKEI_INLINE unsigned int az_object_is_alive (AZObject *obj)
Variables
AZObjectClass AZObjectKlass
Macro Definition Documentation
AZ_CHECK_INSTANCE_CAST
#define AZ_CHECK_INSTANCE_CAST (ip, tc, ct) ((ct *) az_object_check_instance_cast (ip, tc))
AZ_CHECK_INSTANCE_TYPE
#define AZ_CHECK_INSTANCE_TYPE (ip, tc) az_object_check_instance_type (ip, tc)
AZ_CLASS_FROM_OBJ
#define AZ_CLASS_FROM_OBJ (o) ((const AZClass *) (((AZObject *) o)->klass))
AZ_IMPL_FROM_OBJ
#define AZ_IMPL_FROM_OBJ (o) ((const AZImplementation *) (((AZObject *) o)->klass))
AZ_IS_OBJECT
#define AZ_IS_OBJECT (o) (AZ_CHECK_INSTANCE_TYPE ((o), AZ_TYPE_OBJECT))
AZ_OBJECT
#define AZ_OBJECT (o) (AZ_CHECK_INSTANCE_CAST ((o), AZ_TYPE_OBJECT, AZObject))
AZ_OBJECT_ALIVE
#define AZ_OBJECT_ALIVE 1
az_object_is_a
#define az_object_is_a (obj, type) az_object_check_instance_type (obj, type)
AZ_OBJECT_NUM_FLAGS
#define AZ_OBJECT_NUM_FLAGS 1
AZ_OBJECT_TYPE
#define AZ_OBJECT_TYPE (o) AZ_CLASS_TYPE((AZClass *) ((AZObject *) o)->klass)
Function Documentation
az_object_check_instance_cast()
void * az_object_check_instance_cast (void * inst, unsigned int type)
References AZ_OBJECT_TYPE, az_type_get_class, and az_type_is_a().
az_object_check_instance_type()
unsigned int az_object_check_instance_type (void * inst, unsigned int type)
References AZ_OBJECT_TYPE, and az_type_is_a().
az_object_clear_flags()
ARIKKEI_INLINE void az_object_clear_flags (AZObject * obj, unsigned int flags)
az_object_flags()
ARIKKEI_INLINE unsigned int az_object_flags (AZObject * obj, unsigned int flags)
Referenced by array_object_instance_finalize().
az_object_get_interface()
const AZImplementation * az_object_get_interface (AZObject * obj, unsigned int type, void ** inst)
References az_instance_get_interface(), and AZ_IS_OBJECT.
Referenced by az_boxed_interface_new_from_object(), and az_object_interface_list_append_object().
az_object_implements()
unsigned int az_object_implements (AZObject * obj, unsigned int type)
References AZ_IS_OBJECT, AZ_OBJECT_TYPE, and az_type_implements().
Referenced by az_object_interface_list_append_object(), az_object_interface_list_contains(), az_object_interface_list_remove_object(), az_object_list_append_object(), az_object_list_contains(), az_object_list_insert_object(), and az_object_list_remove_object().
az_object_is_alive()
ARIKKEI_INLINE unsigned int az_object_is_alive (AZObject * obj)
References AZ_OBJECT_ALIVE.
az_object_new()
AZObject * az_object_new (unsigned int type)
References az_instance_new(), az_type_get_class, az_type_is_a(), and AZ_TYPE_OBJECT.
Referenced by az_array_object_new(), and az_array_object_new_static().
az_object_ref()
static void az_object_ref (AZObject * obj) inline static
References az_reference_ref().
Referenced by az_object_interface_list_append_object(), az_object_list_append_object(), and az_object_list_insert_object().
az_object_set_flags()
ARIKKEI_INLINE void az_object_set_flags (AZObject * obj, unsigned int flags)
Referenced by az_array_object_new().
az_object_shutdown()
void az_object_shutdown (AZObject * obj)
References AZ_IS_OBJECT, AZ_OBJECT_ALIVE, and az_reference_unref().
az_object_unref()
static void az_object_unref (AZObject * obj) inline static
References az_reference_unref().
Referenced by az_object_interface_list_clear(), az_object_interface_list_remove_object_by_index(), az_object_list_clear(), az_object_list_remove_object(), az_object_list_remove_object_by_index(), object_interface_list_finalize(), and object_list_finalize().
Variable Documentation
AZObjectKlass
AZObjectClass AZObjectKlass extern
Referenced by az_init_object_class().