az: object.c File Reference
object.c File Reference
#include <stdio.h>
#include <az/base.h>
#include <az/instance.h>
#include <az/object.h>
#include <az/packed-value.h>
#include <az/private.h>
#include <az/extend.h>
Macros
#define __AZ_OBJECT_C__
Enumerations
enum { NUM_FUNCTIONS , PROP_CLASS = NUM_FUNCTIONS , NUM_PROPERTIES }
Functions
static void object_init (AZObjectClass *klass, AZObject *object)
void object_dispose (AZReferenceClass *klass, AZReference *ref)
void az_init_object_class (void)
AZObject * az_object_new (unsigned int type)
void az_object_shutdown (AZObject *obj)
void * az_object_check_instance_cast (void *inst, unsigned int type)
unsigned int az_object_check_instance_type (void *inst, unsigned int type)
unsigned int az_object_implements (AZObject *obj, unsigned int type)
const AZImplementation * az_object_get_interface (AZObject *obj, unsigned int type, void **inst)
Variables
AZObjectClass AZObjectKlass
Macro Definition Documentation
__AZ_OBJECT_C__
#define __AZ_OBJECT_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NUM_FUNCTIONS
PROP_CLASS
NUM_PROPERTIES
Function Documentation
az_init_object_class()
void az_init_object_class (void)
References az_class_new_with_value(), AZ_FIELD_INSTANCE, AZ_FIELD_WRITE_NONE, AZ_TYPE_CLASS, AZObjectKlass, NUM_PROPERTIES, and PROP_CLASS.
Referenced by az_init().
az_object_check_instance_cast()
void * az_object_check_instance_cast (void * inst, unsigned int type)
References AZ_OBJECT_TYPE, az_type_get_class, and az_type_is_a().
az_object_check_instance_type()
unsigned int az_object_check_instance_type (void * inst, unsigned int type)
References AZ_OBJECT_TYPE, and az_type_is_a().
az_object_get_interface()
const AZImplementation * az_object_get_interface (AZObject * obj, unsigned int type, void ** inst)
References az_instance_get_interface(), and AZ_IS_OBJECT.
Referenced by az_boxed_interface_new_from_object(), and az_object_interface_list_append_object().
az_object_implements()
unsigned int az_object_implements (AZObject * obj, unsigned int type)
References AZ_IS_OBJECT, AZ_OBJECT_TYPE, and az_type_implements().
Referenced by az_object_interface_list_append_object(), az_object_interface_list_contains(), az_object_interface_list_remove_object(), az_object_list_append_object(), az_object_list_contains(), az_object_list_insert_object(), and az_object_list_remove_object().
az_object_new()
AZObject * az_object_new (unsigned int type)
References az_instance_new(), az_type_get_class, az_type_is_a(), and AZ_TYPE_OBJECT.
Referenced by az_array_object_new(), and az_array_object_new_static().
az_object_shutdown()
void az_object_shutdown (AZObject * obj)
References AZ_IS_OBJECT, AZ_OBJECT_ALIVE, and az_reference_unref().
object_dispose()
void object_dispose (AZReferenceClass * klass, AZReference * ref)
References AZ_OBJECT, and AZ_OBJECT_ALIVE.
object_init()
static void object_init (AZObjectClass * klass, AZObject * object) static
References AZ_OBJECT_ALIVE.
Variable Documentation
AZObjectKlass
AZObjectClass AZObjectKlass
Initial value:
= {
    {{{AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_CONSTRUCT | AZ_FLAG_REFERENCE | AZ_FLAG_OBJECT | AZ_FLAG_ZERO_MEMORY | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_OBJECT},
            &AZReferenceKlass.klass,
            0, 0, 0, 0,
            {0},
            NULL,
            (const uint8_t *) "object",
            7, sizeof(AZObjectClass), 0,
            NULL,
            (void (*) (const AZImplementation *, void *)) object_init, NULL,
            NULL, NULL, az_any_to_string,
            NULL, NULL},
        NULL, object_dispose},
    NULL
}
Referenced by az_init_object_class().