az: object-list.c File Reference
object-list.c File Reference
#include <stdlib.h>
#include <string.h>
#include <az/classes/active-object.h>
#include <az/extend.h>
#include "object-list.h"
Macros
#define __AZ_OBJECT_LIST_CPP__
Enumerations
enum { FUNC_APPEND , NUM_FUNCTIONS , PROP_LENGTH = NUM_FUNCTIONS , NUM_PROPERTIES }
Functions
static void object_list_class_init (AZObjectListClass *klass)
static void object_list_init (AZObjectListClass *klass, AZObjectList *objl)
static void object_list_finalize (AZObjectListClass *klass, AZObjectList *objl)
static unsigned int object_list_get_element_type (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int object_list_get_size (const AZCollectionImplementation *impl, void *collection_instance)
static unsigned int object_list_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * object_list_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
static unsigned int object_list_call_Append (const AZImplementation *arg_impls[], const AZValue *arg_vals[], const AZImplementation **ret_impl, AZValue64 *ret_val, AZContext *ctx)
unsigned int az_object_list_get_type (void)
void az_object_list_setup (AZObjectList *objl, unsigned int type, unsigned int weak)
void az_object_list_release (AZObjectList *objl)
AZObjectList * az_object_list_new (unsigned int type, unsigned int weak)
void az_object_list_delete (AZObjectList *objl)
static void object_list_object_dispose (AZActiveObject *object, void *data)
static unsigned int object_list_remove_object_internal (AZObjectList *objl, AZObject *object)
void az_object_list_append_object (AZObjectList *objl, AZObject *obj)
void az_object_list_insert_object (AZObjectList *objl, AZObject *obj, unsigned int pos)
void az_object_list_remove_object (AZObjectList *objl, AZObject *obj)
void az_object_list_remove_object_by_index (AZObjectList *objl, unsigned int idx)
void az_object_list_clear (AZObjectList *objl)
unsigned int az_object_list_contains (AZObjectList *objl, AZObject *obj)
Variables
static unsigned int object_list_type = 0
AZObjectEventVector object_list_event_vector
Macro Definition Documentation
__AZ_OBJECT_LIST_CPP__
#define __AZ_OBJECT_LIST_CPP__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FUNC_APPEND
NUM_FUNCTIONS
PROP_LENGTH
NUM_PROPERTIES
Function Documentation
az_object_list_append_object()
void az_object_list_append_object (AZObjectList * objl, AZObject * obj)
References AZ_ACTIVE_OBJECT, az_active_object_add_listener(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_ref(), and object_list_event_vector.
Referenced by object_list_call_Append().
az_object_list_clear()
void az_object_list_clear (AZObjectList * objl)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), and az_object_unref().
az_object_list_contains()
unsigned int az_object_list_contains (AZObjectList * objl, AZObject * obj)
References AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), and az_object_is_a.
az_object_list_delete()
void az_object_list_delete (AZObjectList * objl)
References az_object_list_release().
az_object_list_get_type()
unsigned int az_object_list_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_BLOCK, object_list_class_init(), object_list_finalize(), object_list_init(), and object_list_type.
az_object_list_insert_object()
void az_object_list_insert_object (AZObjectList * objl, AZObject * obj, unsigned int pos)
References AZ_ACTIVE_OBJECT, az_active_object_add_listener(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_ref(), and object_list_event_vector.
az_object_list_new()
AZObjectList * az_object_list_new (unsigned int type, unsigned int weak)
References az_object_list_setup(), AZ_TYPE_ACTIVE_OBJECT, AZ_TYPE_INTERFACE, az_type_is_a(), and AZ_TYPE_OBJECT.
az_object_list_release()
void az_object_list_release (AZObjectList * objl)
References az_instance_finalize_by_type(), and AZ_TYPE_OBJECT_LIST.
Referenced by az_object_list_delete().
az_object_list_remove_object()
void az_object_list_remove_object (AZObjectList * objl, AZObject * obj)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_unref(), and object_list_remove_object_internal().
az_object_list_remove_object_by_index()
void az_object_list_remove_object_by_index (AZObjectList * objl, unsigned int idx)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), az_object_unref(), and object_list_remove_object_internal().
az_object_list_setup()
void az_object_list_setup (AZObjectList * objl, unsigned int type, unsigned int weak)
References az_instance_init_by_type(), AZ_TYPE_ACTIVE_OBJECT, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_OBJECT, and AZ_TYPE_OBJECT_LIST.
Referenced by az_object_list_new().
object_list_call_Append()
static unsigned int object_list_call_Append (const AZImplementation * arg_impls[], const AZValue * arg_vals[], const AZImplementation ** ret_impl, AZValue64 * ret_val, AZContext * ctx) static
References az_object_list_append_object().
Referenced by object_list_class_init().
object_list_class_init()
static void object_list_class_init (AZObjectListClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_FIELD_INSTANCE, AZ_FIELD_READ_VALUE, AZ_TYPE_LIST, AZ_TYPE_NONE, AZ_TYPE_OBJECT, AZ_TYPE_UINT32, FUNC_APPEND, NUM_PROPERTIES, object_list_call_Append(), object_list_contains(), object_list_get_element(), object_list_get_element_type(), object_list_get_size(), and PROP_LENGTH.
Referenced by az_object_list_get_type().
object_list_contains()
static unsigned int object_list_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
Referenced by object_list_class_init().
object_list_finalize()
static void object_list_finalize (AZObjectListClass * klass, AZObjectList * objl) static
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), and az_object_unref().
Referenced by az_object_list_get_type().
object_list_get_element()
static const AZImplementation * object_list_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
Referenced by object_list_class_init().
object_list_get_element_type()
static unsigned int object_list_get_element_type (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by object_list_class_init().
object_list_get_size()
static unsigned int object_list_get_size (const AZCollectionImplementation * impl, void * collection_instance) static
Referenced by object_list_class_init().
object_list_init()
static void object_list_init (AZObjectListClass * klass, AZObjectList * objl) static
Referenced by az_object_list_get_type().
object_list_object_dispose()
static void object_list_object_dispose (AZActiveObject * object, void * data) static
References object_list_remove_object_internal().
object_list_remove_object_internal()
static unsigned int object_list_remove_object_internal (AZObjectList * objl, AZObject * object) static
Referenced by az_object_list_remove_object(), az_object_list_remove_object_by_index(), and object_list_object_dispose().
Variable Documentation
object_list_event_vector
AZObjectEventVector object_list_event_vector
Initial value:
= {
    object_list_object_dispose
}
Referenced by az_object_list_append_object(), and az_object_list_insert_object().
object_list_type
unsigned int object_list_type = 0 static
Referenced by az_object_list_get_type().