az: object-interface-list.h File Reference
object-interface-list.h File Reference
#include <az/collections/list.h>
#include <az/object.h>
Data Structures
struct AZObjectInterfaceListElement
struct AZObjectInterfaceList
struct AZObjectInterfaceListClass
Macros
#define AZ_TYPE_OBJECT_INTERFACE_LIST (az_object_interface_list_get_type ())
Functions
unsigned int az_object_interface_list_get_type (void)
void az_object_interface_list_setup (AZObjectInterfaceList *objifl, unsigned int object_type, unsigned int interface_type)
void az_object_interface_list_release (AZObjectInterfaceList *objifl)
AZObjectInterfaceList * az_object_interface_list_new (unsigned int object_type, unsigned int interface_type)
void az_object_interface_list_delete (AZObjectInterfaceList *objifl)
void az_object_interface_list_append_object (AZObjectInterfaceList *objifl, AZObject *object)
void az_object_interface_list_remove_object (AZObjectInterfaceList *objifl, AZObject *object)
void az_object_interface_list_remove_object_by_index (AZObjectInterfaceList *objifl, unsigned int idx)
void az_object_interface_list_clear (AZObjectInterfaceList *objifl)
unsigned int az_object_interface_list_contains (AZObjectInterfaceList *objifl, AZObject *object)
Macro Definition Documentation
AZ_TYPE_OBJECT_INTERFACE_LIST
#define AZ_TYPE_OBJECT_INTERFACE_LIST (az_object_interface_list_get_type ())
Function Documentation
az_object_interface_list_append_object()
void az_object_interface_list_append_object (AZObjectInterfaceList * objifl, AZObject * object)
References az_object_get_interface(), az_object_implements(), az_object_is_a, and az_object_ref().
az_object_interface_list_clear()
void az_object_interface_list_clear (AZObjectInterfaceList * objifl)
References az_object_unref().
az_object_interface_list_contains()
unsigned int az_object_interface_list_contains (AZObjectInterfaceList * objifl, AZObject * object)
References az_object_implements(), and az_object_is_a.
az_object_interface_list_delete()
void az_object_interface_list_delete (AZObjectInterfaceList * objifl)
References az_object_interface_list_release().
az_object_interface_list_get_type()
unsigned int az_object_interface_list_get_type (void)
References AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_STRUCT, object_interface_list_class_init(), object_interface_list_finalize(), object_interface_list_init(), and object_interface_list_type.
az_object_interface_list_new()
AZObjectInterfaceList * az_object_interface_list_new (unsigned int object_type, unsigned int interface_type)
References az_object_interface_list_setup(), AZ_TYPE_INTERFACE, az_type_is_a(), and AZ_TYPE_OBJECT.
az_object_interface_list_release()
void az_object_interface_list_release (AZObjectInterfaceList * objifl)
References az_instance_finalize_by_type(), and AZ_TYPE_OBJECT_INTERFACE_LIST.
Referenced by az_object_interface_list_delete().
az_object_interface_list_remove_object()
void az_object_interface_list_remove_object (AZObjectInterfaceList * objifl, AZObject * object)
References az_object_implements(), az_object_interface_list_remove_object_by_index(), and az_object_is_a.
az_object_interface_list_remove_object_by_index()
void az_object_interface_list_remove_object_by_index (AZObjectInterfaceList * objifl, unsigned int idx)
References az_object_unref().
Referenced by az_object_interface_list_remove_object().
az_object_interface_list_setup()
void az_object_interface_list_setup (AZObjectInterfaceList * objifl, unsigned int object_type, unsigned int interface_type)
References az_instance_init_by_type(), AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_OBJECT, and AZ_TYPE_OBJECT_INTERFACE_LIST.
Referenced by az_object_interface_list_new().