az: object-list.h File Reference
object-list.h File Reference
#include <az/collections/list.h>
#include <az/object.h>
Data Structures
struct AZObjectList
struct AZObjectListClass
Macros
#define AZ_TYPE_OBJECT_LIST (az_object_list_get_type ())
Functions
unsigned int az_object_list_get_type (void)
void az_object_list_setup (AZObjectList *objl, unsigned int type, unsigned int weak)
void az_object_list_release (AZObjectList *objl)
AZObjectList * az_object_list_new (unsigned int type, unsigned int weak)
void az_object_list_delete (AZObjectList *objl)
void az_object_list_append_object (AZObjectList *objl, AZObject *object)
void az_object_list_insert_object (AZObjectList *objl, AZObject *object, unsigned int pos)
void az_object_list_remove_object (AZObjectList *objl, AZObject *object)
void az_object_list_remove_object_by_index (AZObjectList *objl, unsigned int idx)
void az_object_list_clear (AZObjectList *objl)
unsigned int az_object_list_contains (AZObjectList *objl, AZObject *object)
Macro Definition Documentation
AZ_TYPE_OBJECT_LIST
#define AZ_TYPE_OBJECT_LIST (az_object_list_get_type ())
Function Documentation
az_object_list_append_object()
void az_object_list_append_object (AZObjectList * objl, AZObject * object)
References AZ_ACTIVE_OBJECT, az_active_object_add_listener(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_ref(), and object_list_event_vector.
Referenced by object_list_call_Append().
az_object_list_clear()
void az_object_list_clear (AZObjectList * objl)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), and az_object_unref().
az_object_list_contains()
unsigned int az_object_list_contains (AZObjectList * objl, AZObject * object)
References AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), and az_object_is_a.
az_object_list_delete()
void az_object_list_delete (AZObjectList * objl)
References az_object_list_release().
az_object_list_get_type()
unsigned int az_object_list_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_BLOCK, object_list_class_init(), object_list_finalize(), object_list_init(), and object_list_type.
az_object_list_insert_object()
void az_object_list_insert_object (AZObjectList * objl, AZObject * object, unsigned int pos)
References AZ_ACTIVE_OBJECT, az_active_object_add_listener(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_ref(), and object_list_event_vector.
az_object_list_new()
AZObjectList * az_object_list_new (unsigned int type, unsigned int weak)
References az_object_list_setup(), AZ_TYPE_ACTIVE_OBJECT, AZ_TYPE_INTERFACE, az_type_is_a(), and AZ_TYPE_OBJECT.
az_object_list_release()
void az_object_list_release (AZObjectList * objl)
References az_instance_finalize_by_type(), and AZ_TYPE_OBJECT_LIST.
Referenced by az_object_list_delete().
az_object_list_remove_object()
void az_object_list_remove_object (AZObjectList * objl, AZObject * object)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), AZ_IS_ACTIVE_OBJECT, AZ_IS_OBJECT, az_object_implements(), az_object_is_a, az_object_unref(), and object_list_remove_object_internal().
az_object_list_remove_object_by_index()
void az_object_list_remove_object_by_index (AZObjectList * objl, unsigned int idx)
References AZ_ACTIVE_OBJECT, az_active_object_remove_listener_by_data(), az_object_unref(), and object_list_remove_object_internal().
az_object_list_setup()
void az_object_list_setup (AZObjectList * objl, unsigned int type, unsigned int weak)
References az_instance_init_by_type(), AZ_TYPE_ACTIVE_OBJECT, AZ_TYPE_INTERFACE, az_type_is_a(), AZ_TYPE_OBJECT, and AZ_TYPE_OBJECT_LIST.
Referenced by az_object_list_new().