az: packed-value.h File Reference
packed-value.h File Reference
#include <stdio.h>
#include <az/types.h>
#include <az/value.h>
Data Structures
struct AZPackedValue
A convenience structure that holds both an _AZImplementation and the value.
struct AZPackedValue64
An extension of _AZPackedValue for value size up to 64 bytes.
Macros
#define AZ_PACKED_VALUE_MAX_SIZE 16
#define AZ_PACKED_VALUE_TYPE(v) AZ_IMPL_TYPE((v)->impl)
#define az_packed_value_set_string(v, s) az_packed_value_set_reference (v, AZ_TYPE_STRING, (AZReference *) (s))
#define az_packed_value_set_from_impl_value az_packed_value_set_from_val
#define az_packed_value_set_from_impl_instance az_packed_value_set
Functions
static void az_packed_value_init (AZPackedValue *dst, const AZImplementation *impl)
static void az_packed_value_init_autobox (AZPackedValue *dst, const AZImplementation *impl)
static void az_packed_value_64_init_autobox (AZPackedValue *dst, const AZImplementation *impl)
static void * az_packed_value_get_inst (AZPackedValue *val)
static const AZImplementation * az_packed_value_get_inst_autobox (AZPackedValue *val, void **inst)
static const AZImplementation * az_value_set_from_packed_value (AZValue *dst_val, const AZPackedValue *src)
static const AZImplementation * az_value_set_from_packed_value_autobox (AZValue *dst_val, const AZPackedValue *src, unsigned int size)
static void az_packed_value_clear (AZPackedValue *val)
void az_packed_value_set (AZPackedValue *dst, const AZImplementation *impl, void *inst)
static void az_packed_value_set_from_val (AZPackedValue *dst, const AZImplementation *impl, const AZValue *val)
static void az_packed_value_set_from_type (AZPackedValue *dst, unsigned int type, void *inst)
void az_packed_value_set_autobox (AZPackedValue *dst, const AZImplementation *impl, void *inst)
static void az_packed_value_set_from_val_autobox (AZPackedValue *dst, const AZImplementation *impl, const AZValue *val)
static void az_packed_value_set_from_type_autobox (AZPackedValue *dst, unsigned int type, void *inst)
void az_packed_value_64_set_autobox (AZPackedValue64 *dst, const AZImplementation *impl, void *inst)
static void az_packed_value_64_set_from_val_autobox (AZPackedValue64 *dst, const AZImplementation *impl, const AZValue *val)
static void az_packed_value_64_set_from_type_autobox (AZPackedValue64 *dst, unsigned int type, void *inst)
static void az_packed_value_copy (AZPackedValue *dst, const AZPackedValue *src)
ARIKKEI_INLINE void az_packed_value_set_boolean (AZPackedValue *val, unsigned int boolean_v)
ARIKKEI_INLINE void az_packed_value_set_int (AZPackedValue *value, unsigned int type, int val)
ARIKKEI_INLINE void az_packed_value_set_unsigned_int (AZPackedValue *value, unsigned int type, unsigned int val)
ARIKKEI_INLINE void az_packed_value_set_i64 (AZPackedValue *value, int64_t val)
ARIKKEI_INLINE void az_packed_value_set_u64 (AZPackedValue *value, uint64_t val)
ARIKKEI_INLINE void az_packed_value_set_float (AZPackedValue *value, float val)
ARIKKEI_INLINE void az_packed_value_set_double (AZPackedValue *value, double val)
ARIKKEI_INLINE void az_packed_value_set_pointer (AZPackedValue *value, const void *val)
ARIKKEI_INLINE void az_packed_value_set_implementation (AZPackedValue *value, AZImplementation *val)
ARIKKEI_INLINE void az_packed_value_set_class (AZPackedValue *value, AZClass *val)
void az_packed_value_set_reference (AZPackedValue *value, unsigned int type, AZReference *ref)
ARIKKEI_INLINE void az_packed_value_transfer_reference (AZPackedValue *value, unsigned int type, AZReference *ref)
ARIKKEI_INLINE void az_packed_value_transfer_string (AZPackedValue *value, AZString *str)
unsigned int az_packed_value_can_convert (unsigned int to, const AZPackedValue *from)
unsigned int az_packed_value_convert (AZPackedValue *dst, unsigned int type, const AZPackedValue *from)
static void az_packed_value_set_from_type_value (AZPackedValue *dst, unsigned int type, const AZValue *val)
Variables
struct _AZPackedValue ARIKKEI_ALIGN_16
Macro Definition Documentation
AZ_PACKED_VALUE_MAX_SIZE
#define AZ_PACKED_VALUE_MAX_SIZE 16
az_packed_value_set_from_impl_instance
#define az_packed_value_set_from_impl_instance az_packed_value_set
az_packed_value_set_from_impl_value
#define az_packed_value_set_from_impl_value az_packed_value_set_from_val
az_packed_value_set_string
#define az_packed_value_set_string (v, s) az_packed_value_set_reference (v, AZ_TYPE_STRING, (AZReference *) (s))
AZ_PACKED_VALUE_TYPE
#define AZ_PACKED_VALUE_TYPE (v) AZ_IMPL_TYPE((v)->impl)
Function Documentation
az_packed_value_64_init_autobox()
static void az_packed_value_64_init_autobox (AZPackedValue * dst, const AZImplementation * impl) inline static
References az_value_init_autobox().
az_packed_value_64_set_autobox()
void az_packed_value_64_set_autobox (AZPackedValue64 * dst, const AZImplementation * impl, void * inst)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), and az_value_set_from_inst_autobox().
Referenced by az_packed_value_64_set_from_type_autobox(), and az_packed_value_64_set_from_val_autobox().
az_packed_value_64_set_from_type_autobox()
static void az_packed_value_64_set_from_type_autobox (AZPackedValue64 * dst, unsigned int type, void * inst) inline static
References AZ_IMPL_FROM_TYPE, and az_packed_value_64_set_autobox().
az_packed_value_64_set_from_val_autobox()
static void az_packed_value_64_set_from_val_autobox (AZPackedValue64 * dst, const AZImplementation * impl, const AZValue * val) inline static
References az_packed_value_64_set_autobox(), and az_value_get_inst().
az_packed_value_can_convert()
unsigned int az_packed_value_can_convert (unsigned int to, const AZPackedValue * from)
References AZ_CLASS_FLAGS, AZ_CONVERT_CONDITIONAL, AZ_FLAG_REFERENCE, AZ_PACKED_VALUE_TYPE, az_primitive_can_convert(), az_type_get_class, az_type_is_a(), AZ_TYPE_POINTER, and AZ_VALUE_IS_NULL.
az_packed_value_clear()
static void az_packed_value_clear (AZPackedValue * val) inline static
References AZ_IMPL_IS_REFERENCE, and az_reference_unref().
Referenced by az_active_object_clear_attribute(), az_active_object_shutdown(), az_function_invoke_packed(), az_packed_value_convert(), and packed_value_array_finalize().
az_packed_value_convert()
unsigned int az_packed_value_convert (AZPackedValue * dst, unsigned int type, const AZPackedValue * from)
References AZ_CLASS_FLAGS, az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_REFERENCE, AZ_IMPL_FROM_TYPE, az_packed_value_clear(), az_packed_value_copy(), AZ_PACKED_VALUE_TYPE, az_primitive_can_convert(), AZ_TYPE_BOOLEAN, az_type_get_class, az_type_is_a(), AZ_TYPE_IS_ARITHMETIC, and AZ_VALUE_IS_NULL.
az_packed_value_copy()
static void az_packed_value_copy (AZPackedValue * dst, const AZPackedValue * src) inline static
References AZ_IMPL_IS_REFERENCE, az_reference_ref(), and az_reference_unref().
Referenced by az_packed_value_array_set_element(), and az_packed_value_convert().
az_packed_value_get_inst()
static void * az_packed_value_get_inst (AZPackedValue * val) inline static
References az_value_get_inst().
az_packed_value_get_inst_autobox()
static const AZImplementation * az_packed_value_get_inst_autobox (AZPackedValue * val, void ** inst) inline static
References az_value_get_inst_autobox().
az_packed_value_init()
static void az_packed_value_init (AZPackedValue * dst, const AZImplementation * impl) inline static
References az_value_init(), and AZPackedValue::impl.
az_packed_value_init_autobox()
static void az_packed_value_init_autobox (AZPackedValue * dst, const AZImplementation * impl) inline static
References AZ_PACKED_VALUE_MAX_SIZE, and az_value_init_autobox().
az_packed_value_set()
void az_packed_value_set (AZPackedValue * dst, const AZImplementation * impl, void * inst)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), and az_value_set_from_inst().
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_packed_value_set_from_type(), and az_packed_value_set_from_val().
az_packed_value_set_autobox()
void az_packed_value_set_autobox (AZPackedValue * dst, const AZImplementation * impl, void * inst)
References AZ_IMPL_IS_REFERENCE, AZ_PACKED_VALUE_MAX_SIZE, az_reference_unref(), and az_value_set_from_inst_autobox().
Referenced by az_packed_value_set_from_type_autobox(), and az_packed_value_set_from_val_autobox().
az_packed_value_set_boolean()
ARIKKEI_INLINE void az_packed_value_set_boolean (AZPackedValue * val, unsigned int boolean_v)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), AZ_TYPE_BOOLEAN, and az_type_get_class.
az_packed_value_set_class()
ARIKKEI_INLINE void az_packed_value_set_class (AZPackedValue * value, AZClass * val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), AZ_TYPE_CLASS, and az_type_get_class.
az_packed_value_set_double()
ARIKKEI_INLINE void az_packed_value_set_double (AZPackedValue * value, double val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), AZ_TYPE_DOUBLE, and az_type_get_class.
az_packed_value_set_float()
ARIKKEI_INLINE void az_packed_value_set_float (AZPackedValue * value, float val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), AZ_TYPE_FLOAT, and az_type_get_class.
az_packed_value_set_from_type()
static void az_packed_value_set_from_type (AZPackedValue * dst, unsigned int type, void * inst) inline static
References AZ_IMPL_FROM_TYPE, and az_packed_value_set().
az_packed_value_set_from_type_autobox()
static void az_packed_value_set_from_type_autobox (AZPackedValue * dst, unsigned int type, void * inst) inline static
References AZ_IMPL_FROM_TYPE, and az_packed_value_set_autobox().
az_packed_value_set_from_type_value()
static void az_packed_value_set_from_type_value (AZPackedValue * dst, unsigned int type, const AZValue * val) inline static
References AZ_IMPL_FROM_TYPE, and az_packed_value_set_from_val().
az_packed_value_set_from_val()
static void az_packed_value_set_from_val (AZPackedValue * dst, const AZImplementation * impl, const AZValue * val) inline static
References az_packed_value_set(), and az_value_get_inst().
Referenced by az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), and az_packed_value_set_from_type_value().
az_packed_value_set_from_val_autobox()
static void az_packed_value_set_from_val_autobox (AZPackedValue * dst, const AZImplementation * impl, const AZValue * val) inline static
References az_packed_value_set_autobox(), and az_value_get_inst().
az_packed_value_set_i64()
ARIKKEI_INLINE void az_packed_value_set_i64 (AZPackedValue * value, int64_t val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), az_type_get_class, and AZ_TYPE_INT64.
az_packed_value_set_implementation()
ARIKKEI_INLINE void az_packed_value_set_implementation (AZPackedValue * value, AZImplementation * val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), az_type_get_class, and AZ_TYPE_IMPLEMENTATION.
az_packed_value_set_int()
ARIKKEI_INLINE void az_packed_value_set_int (AZPackedValue * value, unsigned int type, int val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), and az_type_get_class.
az_packed_value_set_pointer()
ARIKKEI_INLINE void az_packed_value_set_pointer (AZPackedValue * value, const void * val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), az_type_get_class, and AZ_TYPE_POINTER.
az_packed_value_set_reference()
void az_packed_value_set_reference (AZPackedValue * value, unsigned int type, AZReference * ref)
References AZ_IMPL_FROM_TYPE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
az_packed_value_set_u64()
ARIKKEI_INLINE void az_packed_value_set_u64 (AZPackedValue * value, uint64_t val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), az_type_get_class, and AZ_TYPE_UINT64.
az_packed_value_set_unsigned_int()
ARIKKEI_INLINE void az_packed_value_set_unsigned_int (AZPackedValue * value, unsigned int type, unsigned int val)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), and az_type_get_class.
Referenced by attrd_get_iterator(), and list_get_iterator().
az_packed_value_transfer_reference()
ARIKKEI_INLINE void az_packed_value_transfer_reference (AZPackedValue * value, unsigned int type, AZReference * ref)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), and az_type_get_class.
az_packed_value_transfer_string()
ARIKKEI_INLINE void az_packed_value_transfer_string (AZPackedValue * value, AZString * str)
References AZ_IMPL_IS_REFERENCE, az_reference_unref(), az_type_get_class, and AZ_TYPE_STRING.
az_value_set_from_packed_value()
static const AZImplementation * az_value_set_from_packed_value (AZValue * dst_val, const AZPackedValue * src) inline static
References az_value_copy().
az_value_set_from_packed_value_autobox()
static const AZImplementation * az_value_set_from_packed_value_autobox (AZValue * dst_val, const AZPackedValue * src, unsigned int size) inline static
References az_value_copy_autobox().
Variable Documentation
ARIKKEI_ALIGN_16
struct _AZPackedValue64 ARIKKEI_ALIGN_16