az: packed-value.c File Reference
packed-value.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <arikkei/arikkei-strlib.h>
#include <az/base.h>
#include <az/class.h>
#include <az/primitives.h>
#include <az/private.h>
#include <az/reference.h>
#include <az/packed-value.h>
Macros
#define __AZ_PACKED_VALUE_C__
#define AZ_VALUE_IS_NULL(val) ((AZ_IMPL_TYPE((val)->impl) == AZ_TYPE_STRUCT) && ((val)->v.block == NULL))
Functions
static unsigned int packed_value_to_string (const AZImplementation *impl, void *inst, unsigned char *buf, unsigned int len)
void az_init_packed_value_class (void)
void az_packed_value_set_reference (AZPackedValue *val, unsigned int type, AZReference *ref)
void az_packed_value_copy_indirect (AZPackedValue *dst, const AZPackedValue *src)
unsigned int az_packed_value_can_convert (unsigned int to_type, const AZPackedValue *from)
unsigned int az_packed_value_convert (AZPackedValue *dst, unsigned int to_type, const AZPackedValue *from)
void * az_packed_value_get_instance (AZPackedValue *value)
void az_packed_value_set_from_type_value (AZPackedValue *dst, unsigned int type, const void *src)
void az_packed_value_set_from_impl_value (AZPackedValue *dst, const AZImplementation *impl, const void *src)
void az_packed_value_set_from_type_instance (AZPackedValue *dst, unsigned int type, void *inst)
void az_packed_value_set_from_impl_instance (AZPackedValue *dst, const AZImplementation *impl, void *inst)
Variables
AZClass AZPackedValueKlass
Macro Definition Documentation
__AZ_PACKED_VALUE_C__
#define __AZ_PACKED_VALUE_C__
AZ_VALUE_IS_NULL
#define AZ_VALUE_IS_NULL (val) ((AZ_IMPL_TYPE((val)->impl) == AZ_TYPE_STRUCT) && ((val)->v.block == NULL))
Function Documentation
az_init_packed_value_class()
void az_init_packed_value_class (void)
References az_class_new_with_value(), and AZPackedValueKlass.
Referenced by az_init().
az_packed_value_can_convert()
unsigned int az_packed_value_can_convert (unsigned int to_type, const AZPackedValue * from)
References AZ_CLASS_FLAGS, AZ_CONVERT_CONDITIONAL, AZ_FLAG_REFERENCE, AZ_PACKED_VALUE_TYPE, az_primitive_can_convert(), az_type_get_class, az_type_is_a(), AZ_TYPE_POINTER, and AZ_VALUE_IS_NULL.
az_packed_value_convert()
unsigned int az_packed_value_convert (AZPackedValue * dst, unsigned int to_type, const AZPackedValue * from)
References AZ_CLASS_FLAGS, az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_REFERENCE, AZ_IMPL_FROM_TYPE, az_packed_value_clear(), az_packed_value_copy(), AZ_PACKED_VALUE_TYPE, az_primitive_can_convert(), AZ_TYPE_BOOLEAN, az_type_get_class, az_type_is_a(), AZ_TYPE_IS_ARITHMETIC, and AZ_VALUE_IS_NULL.
az_packed_value_copy_indirect()
void az_packed_value_copy_indirect (AZPackedValue * dst, const AZPackedValue * src)
References AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
Referenced by az_packed_value_copy().
az_packed_value_get_instance()
void * az_packed_value_get_instance (AZPackedValue * value)
References AZ_PACKED_VALUE_TYPE, AZ_TYPE_BLOCK, and az_type_is_a().
az_packed_value_set_from_impl_instance()
void az_packed_value_set_from_impl_instance (AZPackedValue * dst, const AZImplementation * impl, void * inst)
References AZ_CLASS_FLAGS, AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_class_value_size(), AZ_FLAG_REFERENCE, az_packed_value_clear(), AZ_PACKED_VALUE_MAX_SIZE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), AZ_TYPE_IS_REFERENCE, and AZ_TYPE_REFERENCE.
Referenced by aobj_attrd_set(), az_boxed_interface_new(), and az_boxed_interface_new_from_impl_instance().
az_packed_value_set_from_impl_value()
void az_packed_value_set_from_impl_value (AZPackedValue * dst, const AZImplementation * impl, const void * src)
References AZ_CLASS_FLAGS, AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_FLAG_REFERENCE, AZ_PACKED_VALUE_MAX_SIZE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
Referenced by az_boxed_interface_new_from_impl_value().
az_packed_value_set_from_type_instance()
void az_packed_value_set_from_type_instance (AZPackedValue * dst, unsigned int type, void * inst)
References AZ_CLASS_FLAGS, AZ_CLASS_FROM_TYPE, AZ_CLASS_IS_VALUE, az_class_value_size(), AZ_FLAG_REFERENCE, az_packed_value_clear(), AZ_PACKED_VALUE_MAX_SIZE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), AZ_TYPE_IS_REFERENCE, and AZ_TYPE_REFERENCE.
az_packed_value_set_from_type_value()
void az_packed_value_set_from_type_value (AZPackedValue * dst, unsigned int type, const void * src)
References AZ_CLASS_FLAGS, AZ_CLASS_FROM_TYPE, az_class_value_size(), AZ_FLAG_REFERENCE, AZ_PACKED_VALUE_MAX_SIZE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
az_packed_value_set_reference()
void az_packed_value_set_reference (AZPackedValue * val, unsigned int type, AZReference * ref)
References AZ_IMPL_FROM_TYPE, AZ_PACKED_VALUE_TYPE, az_reference_ref(), az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
packed_value_to_string()
static unsigned int packed_value_to_string (const AZImplementation * impl, void * inst, unsigned char * buf, unsigned int len) static
References AZ_CLASS_FROM_IMPL.
Variable Documentation
AZPackedValueKlass
AZClass AZPackedValueKlass
Initial value:
= {
    {AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_ZERO_MEMORY | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_PACKED_VALUE},
    &AZBlockKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "packed value",
    15, sizeof(AZPackedValue), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, packed_value_to_string,
    NULL, NULL
}
Referenced by az_init_packed_value_class().