az: packed-value-array.h File Reference
packed-value-array.h File Reference
#include <az/collections/list.h>
#include <az/reference.h>
Data Structures
struct AZPackedValueArray
struct AZPackedValueArrayClass
Macros
#define AZ_TYPE_PACKED_VALUE_ARRAY az_packed_value_array_get_type ()
Functions
unsigned int az_packed_value_array_get_type (void)
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
void az_packed_value_array_set_element (AZPackedValueArray *varray, unsigned int idx, const AZPackedValue *value)
Macro Definition Documentation
AZ_TYPE_PACKED_VALUE_ARRAY
#define AZ_TYPE_PACKED_VALUE_ARRAY az_packed_value_array_get_type ()
Function Documentation
az_packed_value_array_get_type()
unsigned int az_packed_value_array_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_REFERENCE, NUM_PROPERTIES, packed_value_array_class_init(), and packed_value_array_finalize().
az_packed_value_array_new()
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
References az_instance_new(), az_instance_new_array(), AZ_TYPE_PACKED_VALUE, and AZ_TYPE_PACKED_VALUE_ARRAY.
az_packed_value_array_set_element()
void az_packed_value_array_set_element (AZPackedValueArray * varray, unsigned int idx, const AZPackedValue * value)
References az_packed_value_copy().