az: packed-value-array.c File Reference
packed-value-array.c File Reference
#include <stdlib.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/packed-value.h>
#include <az/private.h>
#include <az/extend.h>
#include "packed-value-array.h"
Macros
#define __AZ_PACKED_VALUE_ARRAY_C__
Enumerations
enum { PROP_LENGTH , NUM_PROPERTIES }
Functions
static void packed_value_array_class_init (AZPackedValueArrayClass *klass)
static void packed_value_array_finalize (AZPackedValueArrayClass *klass, AZPackedValueArray *varray)
static unsigned int packed_value_array_get_property (const AZImplementation *impl, void *instance, unsigned int idx, const AZImplementation **prop_impl, AZValue *prop_val, AZContext *ctx)
static unsigned int packed_value_array_get_element_type (const AZCollectionImplementation *collection_impl, AZCollection *collection_inst)
static const AZImplementation * packed_value_array_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_packed_value_array_get_type (void)
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
void az_packed_value_array_set_element (AZPackedValueArray *varray, unsigned int idx, const AZPackedValue *value)
Macro Definition Documentation
__AZ_PACKED_VALUE_ARRAY_C__
#define __AZ_PACKED_VALUE_ARRAY_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_LENGTH
NUM_PROPERTIES
Function Documentation
az_packed_value_array_get_type()
unsigned int az_packed_value_array_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_REFERENCE, NUM_PROPERTIES, packed_value_array_class_init(), and packed_value_array_finalize().
az_packed_value_array_new()
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
References az_instance_new(), az_instance_new_array(), AZ_TYPE_PACKED_VALUE, and AZ_TYPE_PACKED_VALUE_ARRAY.
az_packed_value_array_set_element()
void az_packed_value_array_set_element (AZPackedValueArray * varray, unsigned int idx, const AZPackedValue * value)
References az_packed_value_copy().
packed_value_array_class_init()
static void packed_value_array_class_init (AZPackedValueArrayClass * klass) static
References az_class_declare_interface(), az_class_define_property(), AZ_FIELD_INSTANCE, AZ_FIELD_READ_VALUE, AZ_FIELD_WRITE_NONE, AZ_TYPE_LIST, AZ_TYPE_UINT32, packed_value_array_get_element(), packed_value_array_get_element_type(), packed_value_array_get_property(), and PROP_LENGTH.
Referenced by az_packed_value_array_get_type().
packed_value_array_finalize()
static void packed_value_array_finalize (AZPackedValueArrayClass * klass, AZPackedValueArray * varray) static
References az_packed_value_clear().
Referenced by az_packed_value_array_get_type().
packed_value_array_get_element()
static const AZImplementation * packed_value_array_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_value_copy_autobox().
Referenced by packed_value_array_class_init().
packed_value_array_get_element_type()
static unsigned int packed_value_array_get_element_type (const AZCollectionImplementation * collection_impl, AZCollection * collection_inst) static
References AZ_TYPE_ANY.
Referenced by packed_value_array_class_init().
packed_value_array_get_property()
static unsigned int packed_value_array_get_property (const AZImplementation * impl, void * instance, unsigned int idx, const AZImplementation ** prop_impl, AZValue * prop_val, AZContext * ctx) static
References AZ_TYPE_UINT32, and PROP_LENGTH.
Referenced by packed_value_array_class_init().