az: primitives.c File Reference
primitives.c File Reference
#include <assert.h>
#include <float.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <arikkei/arikkei-strlib.h>
#include <arikkei/arikkei-utils.h>
#include <az/base.h>
#include <az/private.h>
#include <az/serialization.h>
#include <az/value.h>
#include <az/extend.h>
#include <az/primitives.h>
Macros
#define __AZ_PRIMITIVES_C__
#define AZ_NUM_PRIMITIVE_CLASSES (sizeof(primitive_classes) / sizeof(primitive_classes[0]))
#define A 0
#define C 1
#define E 2
#define N 3
Enumerations
enum {
ANY_PROP_TYPE , ANY_PROP_CLASS , ANY_PROP_ARITHMETIC , ANY_PROP_INTEGRAL ,
ANY_PROP_SIGNED , ANY_NUM_PROPS
}
Functions
unsigned int az_any_to_string (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int d_len)
static unsigned int serialize_boolean (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int deserialize_boolean (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static unsigned int boolean_to_string (const AZImplementation *impl, void *instance, unsigned char *d, unsigned int dlen)
static unsigned int serialize_int (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int deserialize_int (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static unsigned int copy_int_to_buffer (unsigned char *d, unsigned int dlen, unsigned long long value, unsigned int sign)
static unsigned int int_to_string_any (const AZImplementation *impl, void *instance, unsigned char *d, unsigned int dlen)
static unsigned int float_to_string (const AZImplementation *impl, void *instance, unsigned char *d, unsigned int dlen)
static unsigned int double_to_string (const AZImplementation *impl, void *instance, unsigned char *d, unsigned int dlen)
static unsigned int complex_float_to_string (const AZImplementation *impl, void *inst, unsigned char *buf, unsigned int len)
static unsigned int serialize_complex_float (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int deserialize_complex_float (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static unsigned int complex_double_to_string (const AZImplementation *impl, void *inst, unsigned char *buf, unsigned int len)
static unsigned int serialize_complex_double (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int deserialize_complex_double (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static unsigned int pointer_to_string (const AZImplementation *impl, void *instance, unsigned char *buf, unsigned int len)
static unsigned int any_get_property (const AZImplementation *impl, void *inst, unsigned int idx, const AZImplementation **prop_impl, AZValue *prop_val, AZContext *ctx)
void az_init_primitive_classes (void)
void az_post_init_primitive_classes (void)
static unsigned int convert_int8 (unsigned int to_type, AZValue *to_val, int8_t val)
static unsigned int convert_uint8 (unsigned int to_type, void *to_val, uint8_t val)
static unsigned int convert_int16 (unsigned int to_type, void *to_val, int16_t val)
static unsigned int convert_uint16 (unsigned int to_type, void *to_val, uint16_t val)
static unsigned int convert_int32 (unsigned int to_type, void *to_val, int32_t val)
static unsigned int convert_uint32 (unsigned int to_type, void *to_val, uint32_t val)
static unsigned int convert_int64 (unsigned int to_type, void *to_val, int64_t val)
static unsigned int convert_uint64 (unsigned int to_type, void *to_val, uint64_t val)
static unsigned int convert_float (unsigned int to_type, void *to_val, float val)
static unsigned int convert_double (unsigned int to_type, void *to_val, double val)
unsigned int az_convert_arithmetic_type (unsigned int to_type, AZValue *to_val, unsigned int from_type, const AZValue *from_val)
Variables
static unsigned char zero_val [16] = { 0 }
AZClass AZAnyKlass
AZClass AZBooleanKlass
AZClass AZInt8Klass
AZClass AZUint8Klass
AZClass AZInt16Klass
AZClass AZUint16Klass
AZClass AZInt32Klass
AZClass AZUint32Klass
AZClass AZInt64Klass
AZClass AZUint64Klass
AZClass AZFloatKlass
AZClass AZDoubleKlass
AZClass AZComplexFloatKlass
AZClass AZComplexDoubleKlass
AZClass AZPointerKlass
static AZClass * primitive_classes []
const unsigned char az_primitive_conversion_table []
Macro Definition Documentation
__AZ_PRIMITIVES_C__
#define __AZ_PRIMITIVES_C__
A
#define A 0
AZ_NUM_PRIMITIVE_CLASSES
#define AZ_NUM_PRIMITIVE_CLASSES (sizeof(primitive_classes) / sizeof(primitive_classes[0]))
C
#define C 1
E
#define E 2
N
#define N 3
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ANY_PROP_TYPE
ANY_PROP_CLASS
ANY_PROP_ARITHMETIC
ANY_PROP_INTEGRAL
ANY_PROP_SIGNED
ANY_NUM_PROPS
Function Documentation
any_get_property()
static unsigned int any_get_property (const AZImplementation * impl, void * inst, unsigned int idx, const AZImplementation ** prop_impl, AZValue * prop_val, AZContext * ctx) static
References ANY_PROP_ARITHMETIC, ANY_PROP_CLASS, ANY_PROP_TYPE, AZ_CLASS_FROM_IMPL, AZ_FLAG_ARITHMETIC, AZ_IMPL_TYPE, AZBooleanKlass, AZClassKlass, and AZUint32Klass.
az_any_to_string()
unsigned int az_any_to_string (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int d_len)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_TYPE, and AZ_TYPE_ANY.
az_convert_arithmetic_type()
unsigned int az_convert_arithmetic_type (unsigned int to_type, AZValue * to_val, unsigned int from_type, const AZValue * from_val)
References AZ_CONVERSION_CLAMPED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, az_type_get_class, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_IS_ARITHMETIC, AZ_TYPE_IS_PRIMITIVE, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, AZ_TYPE_UINT8, convert_double(), convert_float(), convert_int16(), convert_int32(), convert_int64(), convert_int8(), convert_uint16(), convert_uint32(), convert_uint64(), and convert_uint8().
Referenced by az_packed_value_convert(), az_value_convert_auto(), and az_value_convert_in_place().
az_init_primitive_classes()
void az_init_primitive_classes (void)
References az_class_new_with_value(), AZ_NUM_PRIMITIVE_CLASSES, AZAnyKlass, and primitive_classes.
Referenced by az_init().
az_post_init_primitive_classes()
void az_post_init_primitive_classes (void)
References ANY_NUM_PROPS, ANY_PROP_ARITHMETIC, ANY_PROP_CLASS, ANY_PROP_INTEGRAL, ANY_PROP_SIGNED, ANY_PROP_TYPE, AZ_CLASS_FROM_TYPE, az_class_post_init(), AZ_FIELD_CLASS, AZ_FIELD_IMPLEMENTATION, AZ_FIELD_READ_METHOD, AZ_FIELD_WRITE_NONE, AZ_FLAG_ARITHMETIC, AZ_FLAG_INTEGRAL, AZ_FLAG_SIGNED, AZ_TYPE_ANY, AZ_TYPE_BOOLEAN, AZ_TYPE_CLASS, AZ_TYPE_POINTER, and AZ_TYPE_UINT32.
Referenced by az_init().
boolean_to_string()
static unsigned int boolean_to_string (const AZImplementation * impl, void * instance, unsigned char * d, unsigned int dlen) static
complex_double_to_string()
static unsigned int complex_double_to_string (const AZImplementation * impl, void * inst, unsigned char * buf, unsigned int len) static
complex_float_to_string()
static unsigned int complex_float_to_string (const AZImplementation * impl, void * inst, unsigned char * buf, unsigned int len) static
convert_double()
static unsigned int convert_double (unsigned int to_type, void * to_val, double val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_float()
static unsigned int convert_float (unsigned int to_type, void * to_val, float val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_int16()
static unsigned int convert_int16 (unsigned int to_type, void * to_val, int16_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_int32()
static unsigned int convert_int32 (unsigned int to_type, void * to_val, int32_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_int64()
static unsigned int convert_int64 (unsigned int to_type, void * to_val, int64_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_int8()
static unsigned int convert_int8 (unsigned int to_type, AZValue * to_val, int8_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_uint16()
static unsigned int convert_uint16 (unsigned int to_type, void * to_val, uint16_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT32, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_uint32()
static unsigned int convert_uint32 (unsigned int to_type, void * to_val, uint32_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT64, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_uint64()
static unsigned int convert_uint64 (unsigned int to_type, void * to_val, uint64_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_ROUNDED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, and AZ_TYPE_UINT8.
Referenced by az_convert_arithmetic_type().
convert_uint8()
static unsigned int convert_uint8 (unsigned int to_type, void * to_val, uint8_t val) static
References AZ_CONVERSION_CLAMPED, AZ_CONVERSION_EXACT, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_UINT16, AZ_TYPE_UINT32, and AZ_TYPE_UINT64.
Referenced by az_convert_arithmetic_type().
copy_int_to_buffer()
static unsigned int copy_int_to_buffer (unsigned char * d, unsigned int dlen, unsigned long long value, unsigned int sign) static
Referenced by int_to_string_any().
deserialize_boolean()
static unsigned int deserialize_boolean (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
deserialize_complex_double()
static unsigned int deserialize_complex_double (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
References az_deserialize_int().
deserialize_complex_float()
static unsigned int deserialize_complex_float (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
References az_deserialize_int().
deserialize_int()
static unsigned int deserialize_int (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
References AZ_CLASS_FROM_IMPL, and az_deserialize_int().
double_to_string()
static unsigned int double_to_string (const AZImplementation * impl, void * instance, unsigned char * d, unsigned int dlen) static
float_to_string()
static unsigned int float_to_string (const AZImplementation * impl, void * instance, unsigned char * d, unsigned int dlen) static
int_to_string_any()
static unsigned int int_to_string_any (const AZImplementation * impl, void * instance, unsigned char * d, unsigned int dlen) static
References AZ_CLASS_FROM_IMPL, and copy_int_to_buffer().
pointer_to_string()
static unsigned int pointer_to_string (const AZImplementation * impl, void * instance, unsigned char * buf, unsigned int len) static
serialize_boolean()
static unsigned int serialize_boolean (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_serialize_int().
serialize_complex_double()
static unsigned int serialize_complex_double (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_serialize_int().
serialize_complex_float()
static unsigned int serialize_complex_float (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_serialize_int().
serialize_int()
static unsigned int serialize_int (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References AZ_CLASS_FROM_IMPL, and az_serialize_int().
Variable Documentation
az_primitive_conversion_table
const unsigned char az_primitive_conversion_table[]
Referenced by az_primitive_can_convert().
AZAnyKlass
AZClass AZAnyKlass
Initial value:
= {
    {AZ_FLAG_ABSTRACT | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_ANY},
    NULL,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "any",
    0, sizeof(AZClass), 0,
    NULL,
    NULL, NULL,
    NULL, NULL, az_any_to_string,
    any_get_property, NULL
}
Referenced by az_init_primitive_classes().
AZBooleanKlass
AZClass AZBooleanKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_BOOLEAN},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "boolean",
    3, sizeof(AZClass), 4,
    NULL,
    NULL, NULL,
    serialize_boolean, deserialize_boolean, boolean_to_string,
    NULL, NULL
}
Referenced by any_get_property().
AZComplexDoubleKlass
AZClass AZComplexDoubleKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_COMPLEX_DOUBLE},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "complex double",
    7, sizeof(AZClass), 16,
    NULL,
    NULL, NULL,
    serialize_complex_double, deserialize_complex_double, complex_double_to_string,
    NULL, NULL
}
AZComplexFloatKlass
AZClass AZComplexFloatKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_COMPLEX_FLOAT},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "complex float",
    7, sizeof(AZClass), 8,
    NULL,
    NULL, NULL,
    serialize_complex_float, deserialize_complex_float, complex_float_to_string,
    NULL, NULL
}
AZDoubleKlass
AZClass AZDoubleKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_DOUBLE},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "double",
    7, sizeof(AZClass), 8,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, double_to_string,
    NULL, NULL
}
AZFloatKlass
AZClass AZFloatKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_FLOAT},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "float",
    3, sizeof(AZClass), 4,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, float_to_string,
    NULL, NULL
}
AZInt16Klass
AZClass AZInt16Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_INT16},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "int16",
    1, sizeof(AZClass), 2,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZInt32Klass
AZClass AZInt32Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_INT32},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "int32",
    3, sizeof(AZClass), 4,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZInt64Klass
AZClass AZInt64Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_INT64},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "int64",
    7, sizeof(AZClass), 8,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZInt8Klass
AZClass AZInt8Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_SIGNED | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_INT8},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "int8",
    0, sizeof(AZClass), 1,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZPointerKlass
AZClass AZPointerKlass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_POINTER},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "pointer",
    7, sizeof(AZClass), 8,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, pointer_to_string,
    NULL, NULL
}
AZUint16Klass
AZClass AZUint16Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_UINT16},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "uint16",
    1, sizeof(AZClass), 2,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZUint32Klass
AZClass AZUint32Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_UINT32},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "uint32",
    3, sizeof(AZClass), 4,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
Referenced by any_get_property(), array_deserialize(), and array_serialize().
AZUint64Klass
AZClass AZUint64Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_UINT64},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "uint64",
    7, sizeof(AZClass), 8,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
AZUint8Klass
AZClass AZUint8Klass
Initial value:
= {
    {AZ_FLAG_FINAL | AZ_FLAG_ARITHMETIC | AZ_FLAG_INTEGRAL | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_UINT8},
    &AZAnyKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "uint8",
    0, sizeof(AZClass), 1,
    NULL,
    NULL, NULL,
    serialize_int, deserialize_int, int_to_string_any,
    NULL, NULL
}
primitive_classes
AZClass* primitive_classes[] static
Initial value:
= {
    &AZBooleanKlass,
    &AZInt8Klass,
    &AZUint8Klass,
    &AZInt16Klass,
    &AZUint16Klass,
    &AZInt32Klass,
    &AZUint32Klass,
    &AZInt64Klass,
    &AZUint64Klass,
    &AZFloatKlass,
    &AZDoubleKlass,
    &AZComplexFloatKlass,
    &AZComplexDoubleKlass,
    &AZPointerKlass
}
Referenced by az_init_primitive_classes().
zero_val
unsigned char zero_val[16] = { 0 } static