az: primitives.h File Reference
primitives.h File Reference
#include <az/types.h>
Macros
#define AZ_CONVERT_AUTO 0
#define AZ_CONVERT_CONDITIONAL 1
#define AZ_CONVERT_EXPLICIT 2
#define AZ_CANNOT_CONVERT 3
#define AZ_CONVERSION_EXACT 0
#define AZ_CONVERSION_ROUNDED 1
#define AZ_CONVERSION_CLAMPED 2
#define AZ_CONVERSION_FAILED 3
Functions
ARIKKEI_INLINE unsigned int az_primitive_can_convert (unsigned int to, unsigned int from)
unsigned int az_convert_arithmetic_type (unsigned int to_type, AZValue *to_val, unsigned int from_type, const AZValue *from_val)
Variables
const unsigned char az_primitive_conversion_table []
Macro Definition Documentation
AZ_CANNOT_CONVERT
#define AZ_CANNOT_CONVERT 3
AZ_CONVERSION_CLAMPED
#define AZ_CONVERSION_CLAMPED 2
AZ_CONVERSION_EXACT
#define AZ_CONVERSION_EXACT 0
AZ_CONVERSION_FAILED
#define AZ_CONVERSION_FAILED 3
AZ_CONVERSION_ROUNDED
#define AZ_CONVERSION_ROUNDED 1
AZ_CONVERT_AUTO
#define AZ_CONVERT_AUTO 0
AZ_CONVERT_CONDITIONAL
#define AZ_CONVERT_CONDITIONAL 1
AZ_CONVERT_EXPLICIT
#define AZ_CONVERT_EXPLICIT 2
Function Documentation
az_convert_arithmetic_type()
unsigned int az_convert_arithmetic_type (unsigned int to_type, AZValue * to_val, unsigned int from_type, const AZValue * from_val)
References AZ_CONVERSION_CLAMPED, AZ_TYPE_COMPLEX_DOUBLE, AZ_TYPE_COMPLEX_FLOAT, AZ_TYPE_DOUBLE, AZ_TYPE_FLOAT, az_type_get_class, AZ_TYPE_INT16, AZ_TYPE_INT32, AZ_TYPE_INT64, AZ_TYPE_INT8, AZ_TYPE_IS_ARITHMETIC, AZ_TYPE_IS_PRIMITIVE, AZ_TYPE_UINT16, AZ_TYPE_UINT32, AZ_TYPE_UINT64, AZ_TYPE_UINT8, convert_double(), convert_float(), convert_int16(), convert_int32(), convert_int64(), convert_int8(), convert_uint16(), convert_uint32(), convert_uint64(), and convert_uint8().
Referenced by az_packed_value_convert(), az_value_convert_auto(), and az_value_convert_in_place().
az_primitive_can_convert()
ARIKKEI_INLINE unsigned int az_primitive_can_convert (unsigned int to, unsigned int from)
References az_primitive_conversion_table, and AZ_TYPE_POINTER.
Referenced by az_packed_value_can_convert(), az_packed_value_convert(), az_type_is_convertible_to(), az_value_convert_auto(), and az_value_convert_in_place().
Variable Documentation
az_primitive_conversion_table
const unsigned char az_primitive_conversion_table[] extern
Referenced by az_primitive_can_convert().