az: private.h File Reference
private.h File Reference
#include <az/types.h>
#include <az/class.h>
Data Structures
struct AZTypeConstraint
Macros
#define AZ_INTERNAL
#define AZ_TYPE_VALUE_SIZE(t) az_class_value_size(az_type_get_class(t))
#define ARIKKEI_CHECK_INTEGRITY()
Functions
ARIKKEI_INLINE unsigned int az_type_is_valid (uint32_t type)
void az_globals_init (void)
unsigned int az_reserve_type ()
void az_init_primitive_classes (void)
void az_post_init_primitive_classes (void)
void az_init_base_classes (void)
void az_post_init_base_classes (void)
void az_impl_class_post_init (void)
void az_class_class_post_init (void)
void az_init_interface_class (void)
void az_init_field_class (void)
void az_init_function_classes (void)
void az_init_reference_class (void)
void az_init_string_class (void)
void az_init_boxed_value_class (void)
void az_init_boxed_interface_class (void)
void az_init_packed_value_class (void)
void az_init_object_class (void)
AZClass * az_class_new (uint32_t *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
AZClass * az_class_new_with_type (unsigned int type, unsigned int parent, unsigned int class_size, unsigned int instance_size, unsigned int flags, const uint8_t *name)
void az_class_new_with_value (AZClass *klass)
void az_class_post_init (AZClass *klass)
Macro Definition Documentation
ARIKKEI_CHECK_INTEGRITY
#define ARIKKEI_CHECK_INTEGRITY ()
AZ_INTERNAL
#define AZ_INTERNAL
AZ_TYPE_VALUE_SIZE
#define AZ_TYPE_VALUE_SIZE (t) az_class_value_size(az_type_get_class(t))
Function Documentation
az_class_class_post_init()
void az_class_class_post_init (void)
References AZ_FIELD_INSTANCE, AZ_FIELD_READ_VALUE, AZ_TYPE_CLASS, and AZClassKlass.
az_class_new()
AZClass * az_class_new (uint32_t * type, const unsigned char * name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*)(const AZImplementation *, void *) instance_init, void(*)(const AZImplementation *, void *) instance_finalize)
References AZ_CLASS_FROM_TYPE, az_class_new_with_type(), az_init(), az_num_types, az_reserve_type(), AZ_TYPE_IS_FINAL, and AZ_TYPE_NONE.
Referenced by az_register_composite_type(), and az_register_type().
az_class_new_with_type()
AZClass * az_class_new_with_type (unsigned int type, unsigned int parent, unsigned int class_size, unsigned int instance_size, unsigned int flags, const uint8_t * name)
References az_class_pre_init(), AZ_TYPE_INDEX, and az_types.
Referenced by az_class_new().
az_class_new_with_value()
void az_class_new_with_value (AZClass * klass)
References AZ_CLASS_TYPE, AZ_TYPE_INDEX, AZ_TYPE_NONE, and az_types.
Referenced by az_init_base_classes(), az_init_boxed_interface_class(), az_init_boxed_value_class(), az_init_field_class(), az_init_function_classes(), az_init_interface_class(), az_init_object_class(), az_init_packed_value_class(), az_init_primitive_classes(), az_init_reference_class(), and az_init_string_class().
az_class_post_init()
void az_class_post_init (AZClass * klass)
References AZ_CLASS_FROM_TYPE, az_class_iface_all(), az_class_iface_self(), AZ_CLASS_TYPE, AZ_FLAG_CONSTRUCT, AZ_TYPE_INDEX, and az_types.
Referenced by az_post_init_base_classes(), az_post_init_primitive_classes(), az_register_composite_type(), and az_register_type().
az_globals_init()
void az_globals_init (void)
References AZ_NUM_BASE_TYPES, az_num_types, AZ_TYPE_INDEX, AZ_TYPE_NONE, az_types, and classes_size.
Referenced by az_init().
az_impl_class_post_init()
void az_impl_class_post_init (void)
References AZ_TYPE_ANY, AZ_TYPE_NONE, AZ_TYPE_STRING, AZImplKlass, FUNC_GETSTATICPROPERTY, FUNC_SETSTATICPROPERTY, impl_call_getstaticProperty(), impl_call_setStaticProperty(), and NUM_PROPERTIES.
Referenced by az_post_init_base_classes().
az_init_base_classes()
void az_init_base_classes (void)
References az_class_new_with_value(), AZBlockKlass, AZClassKlass, AZImplKlass, and AZStructKlass.
Referenced by az_init().
az_init_boxed_interface_class()
void az_init_boxed_interface_class (void)
References az_class_new_with_value(), and AZBoxedInterfaceKlass.
Referenced by az_init().
az_init_boxed_value_class()
void az_init_boxed_value_class (void)
References az_class_new_with_value(), and AZBoxedValueKlass.
Referenced by az_init().
az_init_field_class()
void az_init_field_class (void)
References az_class_new_with_value(), and AZFieldKlass.
Referenced by az_init().
az_init_function_classes()
void az_init_function_classes (void)
References az_class_new_with_value(), AZFunctionKlass, and AZFunctionSignatureKlass.
Referenced by az_init().
az_init_interface_class()
void az_init_interface_class (void)
References az_class_new_with_value(), and AZInterfaceKlass.
Referenced by az_init().
az_init_object_class()
void az_init_object_class (void)
References az_class_new_with_value(), AZ_FIELD_INSTANCE, AZ_FIELD_WRITE_NONE, AZ_TYPE_CLASS, AZObjectKlass, NUM_PROPERTIES, and PROP_CLASS.
Referenced by az_init().
az_init_packed_value_class()
void az_init_packed_value_class (void)
References az_class_new_with_value(), and AZPackedValueKlass.
Referenced by az_init().
az_init_primitive_classes()
void az_init_primitive_classes (void)
References az_class_new_with_value(), AZ_NUM_PRIMITIVE_CLASSES, AZAnyKlass, and primitive_classes.
Referenced by az_init().
az_init_reference_class()
void az_init_reference_class (void)
References az_class_new_with_value(), and AZReferenceKlass.
Referenced by az_init().
az_init_string_class()
void az_init_string_class (void)
References az_class_new_with_value(), AZStringKlass, string_equal(), and string_hash().
Referenced by az_init().
az_post_init_base_classes()
void az_post_init_base_classes (void)
References az_class_post_init(), az_impl_class_post_init(), AZBlockKlass, AZClassKlass, AZImplKlass, and AZStructKlass.
az_post_init_primitive_classes()
void az_post_init_primitive_classes (void)
References ANY_NUM_PROPS, ANY_PROP_ARITHMETIC, ANY_PROP_CLASS, ANY_PROP_INTEGRAL, ANY_PROP_SIGNED, ANY_PROP_TYPE, AZ_CLASS_FROM_TYPE, az_class_post_init(), AZ_FIELD_CLASS, AZ_FIELD_IMPLEMENTATION, AZ_FIELD_READ_METHOD, AZ_FIELD_WRITE_NONE, AZ_FLAG_ARITHMETIC, AZ_FLAG_INTEGRAL, AZ_FLAG_SIGNED, AZ_TYPE_ANY, AZ_TYPE_BOOLEAN, AZ_TYPE_CLASS, AZ_TYPE_POINTER, and AZ_TYPE_UINT32.
Referenced by az_init().
az_reserve_type()
unsigned int az_reserve_type ()
References az_num_types, az_types, and classes_size.
Referenced by az_class_new().
az_type_is_valid()
ARIKKEI_INLINE unsigned int az_type_is_valid (uint32_t type)
References AZ_IMPL_FROM_TYPE, az_num_types, and AZ_TYPE_INDEX.