az: private.c File Reference
private.c File Reference
#include <string.h>
#include "private.h"
Macros
#define __AZ_PRIVATE_C__
Functions
void az_globals_init (void)
void az_register_class (AZClass *klass)
Registers class in type system.
Macro Definition Documentation
__AZ_PRIVATE_C__
#define __AZ_PRIVATE_C__
Function Documentation
az_globals_init()
void az_globals_init (void)
References AZ_NUM_BASE_TYPES.
Referenced by az_init().
az_register_class()
void az_register_class (AZClass * klass)
Registers class in type system.
If impl.type is not set a next available type will be assigned.
Parameters
klass A class to register
References AZ_TYPE_INDEX, and AZ_TYPE_NONE.
Referenced by az_class_new(), and az_class_new_with_value().