az: reference-of.h File Reference
reference-of.h File Reference
#include <arikkei/arikkei-utils.h>
#include <az/reference.h>
Data Structures
struct AZReferenceOf
struct AZReferenceOfClass
Macros
#define AZ_TYPE_ABSTRACT_REFERENCE_OF az_abstract_reference_of_get_type ()
#define AZ_TYPE_REFERENCE_OF(t) az_reference_of_get_type (t)
Functions
unsigned int az_abstract_reference_of_get_type (void)
unsigned int az_reference_of_get_type (unsigned int instance_type)
AZReferenceOf * az_reference_of_new (unsigned int inst_type)
AZReferenceOf * az_reference_of_new_value (unsigned int inst_type, const AZValue *value)
ARIKKEI_INLINE unsigned int az_type_is_a_reference_of (unsigned int type, unsigned int referenced_type)
ARIKKEI_INLINE void * az_reference_of_get_instance (AZReferenceOfClass *ref_klass, AZReferenceOf *ref)
Macro Definition Documentation
AZ_TYPE_ABSTRACT_REFERENCE_OF
#define AZ_TYPE_ABSTRACT_REFERENCE_OF az_abstract_reference_of_get_type ()
AZ_TYPE_REFERENCE_OF
#define AZ_TYPE_REFERENCE_OF (t) az_reference_of_get_type (t)
Function Documentation
az_abstract_reference_of_get_type()
unsigned int az_abstract_reference_of_get_type (void)
References abstract_reference_of_type, AZ_FLAG_ABSTRACT, az_register_type(), and AZ_TYPE_REFERENCE.
az_reference_of_get_instance()
ARIKKEI_INLINE void * az_reference_of_get_instance (AZReferenceOfClass * ref_klass, AZReferenceOf * ref)
References az_type_get_class.
Referenced by az_reference_of_new_value(), reference_of_instance_finalize(), reference_of_instance_init(), and reference_of_to_string().
az_reference_of_get_type()
unsigned int az_reference_of_get_type (unsigned int instance_type)
References AZ_CLASS_FROM_TYPE, az_register_composite_type(), AZ_TYPE_ABSTRACT_REFERENCE_OF, AZ_TYPE_INDEX, AZ_TYPE_IS_VALUE, reference_of_class_init(), reference_of_instance_finalize(), and reference_of_instance_init().
az_reference_of_new()
AZReferenceOf * az_reference_of_new (unsigned int inst_type)
References az_instance_new(), and AZ_TYPE_REFERENCE_OF.
az_reference_of_new_value()
AZReferenceOf * az_reference_of_new_value (unsigned int inst_type, const AZValue * value)
References AZ_CLASS_FROM_TYPE, az_instance_new(), az_reference_of_get_instance(), and AZ_TYPE_REFERENCE_OF.
az_type_is_a_reference_of()
ARIKKEI_INLINE unsigned int az_type_is_a_reference_of (unsigned int type, unsigned int referenced_type)
References AZ_TYPE_ABSTRACT_REFERENCE_OF, az_type_get_class, az_type_is_a(), and AZ_TYPE_IS_REFERENCE.