az: reference.c File Reference
reference.c File Reference
#include <stdlib.h>
#include <arikkei/arikkei-utils.h>
#include <az/base.h>
#include <az/class.h>
#include <az/instance.h>
#include <az/private.h>
#include <az/reference.h>
Macros
#define __AZ_REFERENCE_C__
#define AZ_REFERENCE_LOCK()
#define AZ_REFERENCE_UNLOCK()
Functions
void az_reference_drop (AZReferenceClass *klass, AZReference *ref)
void az_reference_dispose (AZReferenceClass *klass, AZReference *ref)
Shutdown instance and drop reference.
static void reference_instance_init (AZReferenceClass *klass, void *instance)
void az_init_reference_class (void)
Variables
AZReferenceClass AZReferenceKlass
Macro Definition Documentation
__AZ_REFERENCE_C__
#define __AZ_REFERENCE_C__
AZ_REFERENCE_LOCK
#define AZ_REFERENCE_LOCK ()
AZ_REFERENCE_UNLOCK
#define AZ_REFERENCE_UNLOCK ()
Function Documentation
az_init_reference_class()
void az_init_reference_class (void)
References az_class_new_with_value(), and AZReferenceKlass.
Referenced by az_init().
az_reference_dispose()
void az_reference_dispose (AZReferenceClass * klass, AZReference * ref)
Shutdown instance and drop reference.
Releases resources and references hold by this instance and drops reference unconditionally (not calling AZReferenceClass::drop for last reference)
References AZ_CLASS_TYPE, az_instance_delete(), AZ_REFERENCE_LOCK, and AZ_REFERENCE_UNLOCK.
az_reference_drop()
void az_reference_drop (AZReferenceClass * klass, AZReference * ref)
References AZ_CLASS_TYPE, az_instance_delete(), AZ_REFERENCE_LOCK, and AZ_REFERENCE_UNLOCK.
reference_instance_init()
static void reference_instance_init (AZReferenceClass * klass, void * instance) static
Variable Documentation
AZReferenceKlass
AZReferenceClass AZReferenceKlass
Initial value:
= {
    {{AZ_FLAG_BLOCK | AZ_FLAG_ABSTRACT | AZ_FLAG_CONSTRUCT | AZ_FLAG_REFERENCE | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_REFERENCE},
    &AZBlockKlass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "reference",
    7, sizeof(AZReferenceClass), 0,
    NULL,
    (void (*) (const AZImplementation *, void *)) reference_instance_init, NULL,
    NULL, NULL, az_any_to_string,
    NULL, NULL},
    NULL, NULL
}
Referenced by az_init_reference_class().