az: reference.h File Reference
reference.h File Reference
#include <az/class.h>
Data Structures
struct AZReference
struct AZReferenceClass
Macros
#define AZ_MT_REFERENCES
Functions
void az_reference_ref (AZReference *ref)
void az_reference_unref (AZReferenceClass *klass, AZReference *ref)
void az_reference_dispose (AZReferenceClass *klass, AZReference *ref)
Shutdown instance and drop reference.
Variables
AZReferenceClass AZReferenceKlass
Macro Definition Documentation
AZ_MT_REFERENCES
#define AZ_MT_REFERENCES
Use multi-threaded reference counting Single global mutex is created for all reference types
Function Documentation
az_reference_dispose()
void az_reference_dispose (AZReferenceClass * klass, AZReference * ref)
Shutdown instance and drop reference.
Releases resources and references hold by this instance and drops reference unconditionally (not calling AZReferenceClass::drop for last reference)
References AZ_CLASS_TYPE, az_instance_delete(), AZ_REFERENCE_LOCK, and AZ_REFERENCE_UNLOCK.
az_reference_ref()
void az_reference_ref (AZReference * ref)
Referenced by az_boxed_interface_ref(), az_boxed_value_ref(), az_object_ref(), az_packed_value_copy(), az_packed_value_set_reference(), az_string_ref(), az_value_copy(), az_value_set_from_inst(), and az_value_set_reference().
az_reference_unref()
void az_reference_unref (AZReferenceClass * klass, AZReference * ref)
Referenced by az_boxed_interface_unref(), az_boxed_value_unref(), az_object_shutdown(), az_object_unref(), az_packed_value_64_set_autobox(), az_packed_value_clear(), az_packed_value_copy(), az_packed_value_set(), az_packed_value_set_autobox(), az_packed_value_set_boolean(), az_packed_value_set_class(), az_packed_value_set_double(), az_packed_value_set_float(), az_packed_value_set_i64(), az_packed_value_set_implementation(), az_packed_value_set_int(), az_packed_value_set_pointer(), az_packed_value_set_reference(), az_packed_value_set_u64(), az_packed_value_set_unsigned_int(), az_packed_value_transfer_reference(), az_packed_value_transfer_string(), az_string_unref(), and az_value_clear().
Variable Documentation
AZReferenceKlass
AZReferenceClass AZReferenceKlass extern
Referenced by az_init_reference_class().