az: reference-of.c File Reference
reference-of.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arikkei/arikkei-strlib.h>
#include <az/private.h>
#include <az/extend.h>
#include <az/reference-of.h>
Macros
#define __AZ_REFERENCE_OF_C__
Functions
unsigned int az_abstract_reference_of_get_type (void)
static void reference_of_class_init (AZReferenceOfClass *klass, AZClass *inst_class)
static void reference_of_instance_init (AZReferenceOfClass *klass, AZReferenceOf *ref_of)
static void reference_of_instance_finalize (AZReferenceOfClass *klass, AZReferenceOf *ref_of)
static unsigned int reference_of_to_string (const AZImplementation *impl, void *instance, unsigned char *buf, unsigned int len)
unsigned int az_reference_of_get_type (unsigned int instance_type)
AZReferenceOf * az_reference_of_new (unsigned int inst_type)
AZReferenceOf * az_reference_of_new_value (unsigned int inst_type, const AZValue *value)
Variables
static unsigned int abstract_reference_of_type = 0
Macro Definition Documentation
__AZ_REFERENCE_OF_C__
#define __AZ_REFERENCE_OF_C__
Function Documentation
az_abstract_reference_of_get_type()
unsigned int az_abstract_reference_of_get_type (void)
References abstract_reference_of_type, AZ_FLAG_ABSTRACT, az_register_type(), and AZ_TYPE_REFERENCE.
az_reference_of_get_type()
unsigned int az_reference_of_get_type (unsigned int instance_type)
References AZ_CLASS_FROM_TYPE, az_register_composite_type(), AZ_TYPE_ABSTRACT_REFERENCE_OF, AZ_TYPE_INDEX, AZ_TYPE_IS_VALUE, reference_of_class_init(), reference_of_instance_finalize(), and reference_of_instance_init().
az_reference_of_new()
AZReferenceOf * az_reference_of_new (unsigned int inst_type)
References az_instance_new(), and AZ_TYPE_REFERENCE_OF.
az_reference_of_new_value()
AZReferenceOf * az_reference_of_new_value (unsigned int inst_type, const AZValue * value)
References AZ_CLASS_FROM_TYPE, az_instance_new(), az_reference_of_get_instance(), and AZ_TYPE_REFERENCE_OF.
reference_of_class_init()
static void reference_of_class_init (AZReferenceOfClass * klass, AZClass * inst_class) static
References AZ_CLASS_TYPE, and reference_of_to_string().
Referenced by az_reference_of_get_type().
reference_of_instance_finalize()
static void reference_of_instance_finalize (AZReferenceOfClass * klass, AZReferenceOf * ref_of) static
References az_instance_finalize_by_type(), and az_reference_of_get_instance().
Referenced by az_reference_of_get_type().
reference_of_instance_init()
static void reference_of_instance_init (AZReferenceOfClass * klass, AZReferenceOf * ref_of) static
References az_instance_init_by_type(), and az_reference_of_get_instance().
Referenced by az_reference_of_get_type().
reference_of_to_string()
static unsigned int reference_of_to_string (const AZImplementation * impl, void * instance, unsigned char * buf, unsigned int len) static
References AZ_CLASS_FROM_TYPE, az_instance_to_string(), and az_reference_of_get_instance().
Referenced by reference_of_class_init().
Variable Documentation
abstract_reference_of_type
unsigned int abstract_reference_of_type = 0 static
Referenced by az_abstract_reference_of_get_type().