az: serialization.h File Reference
serialization.h File Reference
#include <az/types.h>
Macros
#define az_serialize_float(d, dlen, inst) az_serialize_int (d, dlen, inst, 4)
#define az_serialize_double(d, dlen, inst) az_serialize_int (d, dlen, inst, 8)
#define az_deserialize_float(value, s, slen) az_deserialize_int (value, 4, s, slen)
#define az_deserialize_double(value, s, slen) az_deserialize_int (value, 8, s, slen)
#define az_serialize_floats(d, dlen, inst, n) az_serialize_ints (d, dlen, inst, 4, n)
#define az_deserialize_floats(value, s, slen, n) az_deserialize_ints (value, 4, n, s, slen)
Functions
unsigned int az_serialize_block (unsigned char *d, unsigned int dlen, const void *s, unsigned int slen)
unsigned int az_deserialize_block (void *d, unsigned int dlen, const unsigned char *s, unsigned int slen)
unsigned int az_serialize_int (unsigned char *d, unsigned int dlen, const void *inst, unsigned int size)
unsigned int az_deserialize_int (void *value, unsigned int size, const unsigned char *s, unsigned int slen)
unsigned int az_serialize_ints (unsigned char *d, unsigned int dlen, const void *inst, unsigned int size, unsigned int n_values)
unsigned int az_deserialize_ints (void *value, unsigned int size, unsigned int n_values, const unsigned char *s, unsigned int slen)
Macro Definition Documentation
az_deserialize_double
#define az_deserialize_double (value, s, slen) az_deserialize_int (value, 8, s, slen)
az_deserialize_float
#define az_deserialize_float (value, s, slen) az_deserialize_int (value, 4, s, slen)
az_deserialize_floats
#define az_deserialize_floats (value, s, slen, n) az_deserialize_ints (value, 4, n, s, slen)
az_serialize_double
#define az_serialize_double (d, dlen, inst) az_serialize_int (d, dlen, inst, 8)
az_serialize_float
#define az_serialize_float (d, dlen, inst) az_serialize_int (d, dlen, inst, 4)
az_serialize_floats
#define az_serialize_floats (d, dlen, inst, n) az_serialize_ints (d, dlen, inst, 4, n)
Function Documentation
az_deserialize_block()
unsigned int az_deserialize_block (void * d, unsigned int dlen, const unsigned char * s, unsigned int slen)
az_deserialize_int()
unsigned int az_deserialize_int (void * value, unsigned int size, const unsigned char * s, unsigned int slen)
Referenced by az_deserialize_ints(), az_string_deserialize_chars(), deserialize_complex_double(), deserialize_complex_float(), deserialize_int(), and deserialize_string().
az_deserialize_ints()
unsigned int az_deserialize_ints (void * value, unsigned int size, unsigned int n_values, const unsigned char * s, unsigned int slen)
References az_deserialize_int().
az_serialize_block()
unsigned int az_serialize_block (unsigned char * d, unsigned int dlen, const void * s, unsigned int slen)
Referenced by serialize_string().
az_serialize_int()
unsigned int az_serialize_int (unsigned char * d, unsigned int dlen, const void * inst, unsigned int size)
Referenced by az_serialize_ints(), serialize_boolean(), serialize_complex_double(), serialize_complex_float(), serialize_int(), and serialize_string().
az_serialize_ints()
unsigned int az_serialize_ints (unsigned char * d, unsigned int dlen, const void * inst, unsigned int size, unsigned int n_values)
References az_serialize_int().