az: serialization.c File Reference
serialization.c File Reference
#include <stdio.h>
#include <string.h>
#include <az/serialization.h>
Macros
#define __AZ_SERIALIZATION_C__
Functions
unsigned int az_serialize_block (unsigned char *d, unsigned int dlen, const void *s, unsigned int slen)
unsigned int az_deserialize_block (void *d, unsigned int dlen, const unsigned char *s, unsigned int slen)
unsigned int az_serialize_int (unsigned char *d, unsigned int dlen, const void *inst, unsigned int size)
unsigned int az_deserialize_int (void *value, unsigned int size, const unsigned char *s, unsigned int slen)
unsigned int az_serialize_ints (unsigned char *d, unsigned int dlen, const void *inst, unsigned int size, unsigned int n_values)
unsigned int az_deserialize_ints (void *value, unsigned int size, unsigned int n_values, const unsigned char *s, unsigned int slen)
Macro Definition Documentation
__AZ_SERIALIZATION_C__
#define __AZ_SERIALIZATION_C__
Function Documentation
az_deserialize_block()
unsigned int az_deserialize_block (void * d, unsigned int dlen, const unsigned char * s, unsigned int slen)
az_deserialize_int()
unsigned int az_deserialize_int (void * value, unsigned int size, const unsigned char * s, unsigned int slen)
Referenced by az_deserialize_ints(), az_string_deserialize_chars(), deserialize_complex_double(), deserialize_complex_float(), deserialize_int(), and deserialize_string().
az_deserialize_ints()
unsigned int az_deserialize_ints (void * value, unsigned int size, unsigned int n_values, const unsigned char * s, unsigned int slen)
References az_deserialize_int().
az_serialize_block()
unsigned int az_serialize_block (unsigned char * d, unsigned int dlen, const void * s, unsigned int slen)
Referenced by serialize_string().
az_serialize_int()
unsigned int az_serialize_int (unsigned char * d, unsigned int dlen, const void * inst, unsigned int size)
Referenced by az_serialize_ints(), serialize_boolean(), serialize_complex_double(), serialize_complex_float(), serialize_int(), and serialize_string().
az_serialize_ints()
unsigned int az_serialize_ints (unsigned char * d, unsigned int dlen, const void * inst, unsigned int size, unsigned int n_values)
References az_serialize_int().