az: stream-utils.h File Reference
stream-utils.h File Reference
#include <stdint.h>
#include <az/io/input-stream.h>
#include <az/io/output-stream.h>
Functions
int64_t az_stream_copy (const AZInputStreamImplementation *in_impl, AZInputStream *in_inst, const AZOutputStreamImplementation *out_impl, AZOutputStream *out_inst, uint64_t size)
int64_t az_stream_copy_all (const AZInputStreamImplementation *in_impl, AZInputStream *in_inst, const AZOutputStreamImplementation *out_impl, AZOutputStream *out_inst)
Function Documentation
az_stream_copy()
int64_t az_stream_copy (const AZInputStreamImplementation * in_impl, AZInputStream * in_inst, const AZOutputStreamImplementation * out_impl, AZOutputStream * out_inst, uint64_t size)
References az_input_stream_read(), az_output_stream_write(), and COPY_BUFFER_SIZE.
az_stream_copy_all()
int64_t az_stream_copy_all (const AZInputStreamImplementation * in_impl, AZInputStream * in_inst, const AZOutputStreamImplementation * out_impl, AZOutputStream * out_inst)
References az_input_stream_read(), AZ_IO_ERROR, az_output_stream_write(), and COPY_BUFFER_SIZE.