az: string.h File Reference
string.h File Reference
#include <arikkei/arikkei-dict.h>
#include <az/reference.h>
Data Structures
struct AZString
struct AZStringClass
Functions
AZString * az_string_new (const unsigned char *str)
AZString * az_string_new_length (const unsigned char *str, unsigned int length)
AZString * az_string_lookup (const unsigned char *chars)
AZString * az_string_lookup_length (const unsigned char *chars, unsigned int length)
static void az_string_ref (AZString *astr)
static void az_string_unref (AZString *astr)
static unsigned int az_string_equals (const AZString *lhs, const AZString *rhs)
AZString * az_string_concat (AZString *lhs, AZString *rhs)
const unsigned char * az_string_deserialize_chars (const unsigned char *cdata, unsigned int csize, unsigned int *cpos)
Variables
AZStringClass AZStringKlass
Function Documentation
az_string_concat()
AZString * az_string_concat (AZString * lhs, AZString * rhs)
References az_instance_init_by_type(), az_string_unref(), AZ_TYPE_STRING, and AZStringKlass.
az_string_deserialize_chars()
const unsigned char * az_string_deserialize_chars (const unsigned char * cdata, unsigned int csize, unsigned int * cpos)
References az_deserialize_int().
az_string_equals()
static unsigned int az_string_equals (const AZString * lhs, const AZString * rhs) inline static
az_string_lookup()
AZString * az_string_lookup (const unsigned char * chars)
References az_string_lookup_length().
az_string_lookup_length()
AZString * az_string_lookup_length (const unsigned char * chars, unsigned int length)
References az_string_ref(), AZStringKlass, string_data_equal(), and string_data_hash().
Referenced by az_string_lookup().
az_string_new()
AZString * az_string_new (const unsigned char * str)
References az_string_new_length().
Referenced by az_active_object_set_attribute_i32(), az_active_object_set_attribute_object(), az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), az_instance_get_function_by_key(), az_instance_get_property_by_key(), and az_instance_set_property_by_key().
az_string_new_length()
AZString * az_string_new_length (const unsigned char * str, unsigned int length)
References az_instance_init_by_type(), az_string_ref(), AZ_TYPE_STRING, AZStringKlass, string_data_equal(), and string_data_hash().
Referenced by az_string_new(), and deserialize_string().
az_string_ref()
static void az_string_ref (AZString * astr) inline static
References az_reference_ref().
Referenced by az_active_object_get_attribute_slot(), az_string_lookup_length(), and az_string_new_length().
az_string_unref()
static void az_string_unref (AZString * astr) inline static
References az_reference_unref(), and AZStringKlass.
Referenced by az_active_object_clear_attribute(), az_active_object_set_attribute_i32(), az_active_object_set_attribute_object(), az_active_object_shutdown(), az_instance_get_property_by_key(), az_instance_set_property_by_key(), and az_string_concat().
Variable Documentation
AZStringKlass
AZStringClass AZStringKlass extern
Referenced by aobj_aa_keys_get_element(), az_init_string_class(), az_string_concat(), az_string_lookup_length(), az_string_new_length(), az_string_unref(), and string_dispose().