az: string.c File Reference
string.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <az/class.h>
#include <az/private.h>
#include <az/serialization.h>
#include "value.h"
Macros
#define __AZ_STRING_C__
Functions
static unsigned int string_hash (const void *data)
static unsigned int string_equal (const void *l, const void *r)
static unsigned int string_data_hash (const void *data)
static unsigned int string_data_equal (const void *l, const void *r)
static unsigned int string_to_string (const AZImplementation *impl, void *instance, unsigned char *buf, unsigned int len)
static unsigned int serialize_string (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
static unsigned int deserialize_string (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
static void string_dispose (AZReferenceClass *klass, AZReference *ref)
void az_init_string_class (void)
AZString * az_string_new (const unsigned char *str)
AZString * az_string_new_length (const unsigned char *str, unsigned int length)
AZString * az_string_lookup (const unsigned char *chars)
AZString * az_string_lookup_length (const unsigned char *chars, unsigned int length)
AZString * az_string_concat (AZString *lhs, AZString *rhs)
const unsigned char * az_string_deserialize_chars (const unsigned char *cdata, unsigned int csize, unsigned int *cpos)
Variables
AZStringClass AZStringKlass
Macro Definition Documentation
__AZ_STRING_C__
#define __AZ_STRING_C__
Function Documentation
az_init_string_class()
void az_init_string_class (void)
References az_class_new_with_value(), AZStringKlass, string_equal(), and string_hash().
Referenced by az_init().
az_string_concat()
AZString * az_string_concat (AZString * lhs, AZString * rhs)
References az_instance_init_by_type(), az_string_unref(), AZ_TYPE_STRING, and AZStringKlass.
az_string_deserialize_chars()
const unsigned char * az_string_deserialize_chars (const unsigned char * cdata, unsigned int csize, unsigned int * cpos)
References az_deserialize_int().
az_string_lookup()
AZString * az_string_lookup (const unsigned char * chars)
References az_string_lookup_length().
az_string_lookup_length()
AZString * az_string_lookup_length (const unsigned char * chars, unsigned int length)
References az_string_ref(), AZStringKlass, string_data_equal(), and string_data_hash().
Referenced by az_string_lookup().
az_string_new()
AZString * az_string_new (const unsigned char * str)
References az_string_new_length().
Referenced by az_active_object_set_attribute_i32(), az_active_object_set_attribute_object(), az_field_setup_method(), az_field_setup_stored(), az_field_setup_value(), az_instance_get_function_by_key(), az_instance_get_property_by_key(), and az_instance_set_property_by_key().
az_string_new_length()
AZString * az_string_new_length (const unsigned char * str, unsigned int length)
References az_instance_init_by_type(), az_string_ref(), AZ_TYPE_STRING, AZStringKlass, string_data_equal(), and string_data_hash().
Referenced by az_string_new(), and deserialize_string().
deserialize_string()
static unsigned int deserialize_string (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx) static
References az_deserialize_int(), and az_string_new_length().
serialize_string()
static unsigned int serialize_string (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx) static
References az_serialize_block(), and az_serialize_int().
string_data_equal()
static unsigned int string_data_equal (const void * l, const void * r) static
Referenced by az_string_lookup_length(), and az_string_new_length().
string_data_hash()
static unsigned int string_data_hash (const void * data) static
Referenced by az_string_lookup_length(), and az_string_new_length().
string_dispose()
static void string_dispose (AZReferenceClass * klass, AZReference * ref) static
References AZStringKlass.
string_equal()
static unsigned int string_equal (const void * l, const void * r) static
Referenced by az_init_string_class().
string_hash()
static unsigned int string_hash (const void * data) static
Referenced by az_init_string_class().
string_to_string()
static unsigned int string_to_string (const AZImplementation * impl, void * instance, unsigned char * buf, unsigned int len) static
Variable Documentation
AZStringKlass
AZStringClass AZStringKlass
Initial value:
= {
    {{{AZ_FLAG_BLOCK | AZ_FLAG_FINAL | AZ_FLAG_CONSTRUCT | AZ_FLAG_REFERENCE | AZ_FLAG_IMPL_IS_CLASS, AZ_TYPE_STRING},
    &AZReferenceKlass.klass,
    0, 0, 0, 0, {0}, NULL,
    (const uint8_t *) "string",
    7, sizeof(AZStringClass), 0,
    NULL,
    NULL, NULL,
    serialize_string, deserialize_string, string_to_string,
    NULL, NULL},
    NULL, string_dispose},
    {0}
}
Referenced by aobj_aa_keys_get_element(), az_init_string_class(), az_string_concat(), az_string_lookup_length(), az_string_new_length(), az_string_unref(), and string_dispose().