az: types.h File Reference
types.h File Reference
#include <stdint.h>
#include <stdlib.h>
#include <az/az.h>
Classes
struct AZTypeInfo
struct AZIFEntry
Macros
#define AZ_TYPE_MASK 0x00ffffff
#define AZ_TYPE_INDEX(t) ((t) & AZ_TYPE_MASK)
#define AZ_CLASS_FROM_TYPE(t) az_classes[AZ_TYPE_INDEX(t)]
#define AZ_IMPL_FROM_TYPE(t) ((AZImplementation *) az_classes[AZ_TYPE_INDEX(t)])
#define AZ_TYPE_FLAGS(t) az_types[AZ_TYPE_INDEX(t)].flags
#define AZ_TYPE_IS_REFERENCE(t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_REFERENCE)
#define AZ_TYPE_IS_INTERFACE(t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_INTERFACE)
#define AZ_TYPE_IS_BLOCK(t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_BLOCK)
#define AZ_TYPE_IS_VALUE(t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_VALUE)
#define AZ_TYPE_IS_FINAL(t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_FINAL)
#define az_type_get_class AZ_CLASS_FROM_TYPE
#define az_type_get_impl AZ_IMPL_FROM_TYPE
Functions
unsigned int az_type_get_parent_primitive (unsigned int type)
Get parent primitive type.
unsigned int az_type_is_a (unsigned int type, unsigned int test)
Checks whether the given type is a subtype of another.
unsigned int az_type_implements (unsigned int type, unsigned int test)
Checks whether the given type implements an interface type.
unsigned int az_type_is_assignable_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can be assigned to a variable of given type.
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
void az_instance_initialize (void *inst, unsigned int type)
Initialize a new instance.
ARIKKEI_INLINE void az_instance_init (void *inst, unsigned int type)
void az_instance_finalize (void *inst, unsigned int type)
void az_implementation_init (AZImplementation *impl, unsigned int type)
void az_interface_init (const AZImplementation *impl, void *inst)
void az_interface_finalize (const AZImplementation *impl, void *inst)
void * az_instance_new (unsigned int type)
void * az_instance_new_array (unsigned int type, unsigned int nelements)
void az_instance_delete (unsigned int type, void *inst)
void az_instance_delete_array (unsigned int type, void *elements, unsigned int nelements)
const AZImplementation * az_get_interface (const AZImplementation *impl, void *inst, unsigned int if_type, void **if_inst)
ARIKKEI_INLINE const AZImplementation * az_get_interface_from_type (unsigned int type, void *inst, unsigned int if_type, void **if_inst)
unsigned int az_instance_serialize (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
unsigned int az_deserialize_value (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
unsigned int az_instance_to_string (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen)
AZClass * az_register_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*class_init)(AZClass *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
Get new typecode, allocate and initialize a class structure.
AZClass * az_register_composite_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*class_init)(AZClass *, void *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *), void *data)
Get new typecode, allocate and initialize a class structure.
Variables
AZClass ** az_classes
AZTypeInfo * az_types
unsigned int az_num_classes
Macro Definition Documentation
AZ_CLASS_FROM_TYPE
#define AZ_CLASS_FROM_TYPE (t) az_classes[AZ_TYPE_INDEX(t)]
AZ_IMPL_FROM_TYPE
#define AZ_IMPL_FROM_TYPE (t) ((AZImplementation *) az_classes[AZ_TYPE_INDEX(t)])
AZ_TYPE_FLAGS
#define AZ_TYPE_FLAGS (t) az_types[AZ_TYPE_INDEX(t)].flags
az_type_get_class
#define az_type_get_class AZ_CLASS_FROM_TYPE
az_type_get_impl
#define az_type_get_impl AZ_IMPL_FROM_TYPE
AZ_TYPE_INDEX
#define AZ_TYPE_INDEX (t) ((t) & AZ_TYPE_MASK)
AZ_TYPE_IS_BLOCK
#define AZ_TYPE_IS_BLOCK (t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_BLOCK)
AZ_TYPE_IS_FINAL
#define AZ_TYPE_IS_FINAL (t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_FINAL)
AZ_TYPE_IS_INTERFACE
#define AZ_TYPE_IS_INTERFACE (t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_INTERFACE)
AZ_TYPE_IS_REFERENCE
#define AZ_TYPE_IS_REFERENCE (t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_REFERENCE)
AZ_TYPE_IS_VALUE
#define AZ_TYPE_IS_VALUE (t) (AZ_TYPE_FLAGS(t) & AZ_FLAG_VALUE)
AZ_TYPE_MASK
#define AZ_TYPE_MASK 0x00ffffff
Function Documentation
az_deserialize_value()
unsigned int az_deserialize_value (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx)
References az_type_get_class.
az_get_interface()
const AZImplementation * az_get_interface (const AZImplementation * impl, void * inst, unsigned int if_type, void ** if_inst)
References AZ_CLASS_FROM_TYPE, az_class_iface_all(), AZ_TYPE_BOXED_INTERFACE, and az_type_is_a().
Referenced by az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_function_invoke_by_type_instance(), az_function_invoke_by_value_signature_va(), az_get_interface_from_type(), az_instance_invoke_function(), az_object_get_interface(), and az_type_implements().
az_get_interface_from_type()
ARIKKEI_INLINE const AZImplementation * az_get_interface_from_type (unsigned int type, void * inst, unsigned int if_type, void ** if_inst)
References az_get_interface(), and AZ_IMPL_FROM_TYPE.
az_implementation_init()
void az_implementation_init (AZImplementation * impl, unsigned int type)
References az_num_classes, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and implementation_init_recursive().
Referenced by attrib_dict_impl_init(), and az_class_declare_interface().
az_instance_delete()
void az_instance_delete (unsigned int type, void * inst)
References az_num_classes, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_finalize_recursive().
Referenced by az_function_signature_delete(), az_reference_dispose(), and az_reference_drop().
az_instance_delete_array()
void az_instance_delete_array (unsigned int type, void * elements, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, az_num_classes, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_finalize_recursive().
az_instance_finalize()
void az_instance_finalize (void * inst, unsigned int type)
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, az_num_classes, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_finalize_recursive().
Referenced by array_of_instance_finalize(), az_interface_list_release(), az_object_interface_list_release(), az_object_list_release(), reference_of_instance_finalize(), and value_array_ref_finalize().
az_instance_init()
ARIKKEI_INLINE void az_instance_init (void * inst, unsigned int type)
References AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, az_instance_initialize(), and AZ_TYPE_FLAGS.
Referenced by az_boxed_interface_new(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_value_new(), az_boxed_value_new_from_impl_instance(), az_boxed_value_new_from_impl_value(), az_function_signature_new(), az_function_signature_new_any(), az_function_signature_new_va(), az_interface_list_setup(), az_object_interface_list_setup(), az_object_list_setup(), az_string_concat(), az_string_new_length(), az_value_init(), reference_of_instance_init(), and value_array_ref_init().
az_instance_initialize()
void az_instance_initialize (void * inst, unsigned int type)
Initialize a new instance.
Initializes a new instance by calling recursively all superclass and interface constructors
Parameters
inst pointer to instance
type instance type
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, AZ_TYPE_INTERFACE, az_type_is_a(), az_type_is_valid(), and instance_init_recursive().
Referenced by az_instance_init().
az_instance_new()
void * az_instance_new (unsigned int type)
References AZ_FLAG_ABSTRACT, AZ_FLAG_ZERO_MEMORY, az_num_classes, az_type_get_class, AZ_TYPE_INDEX, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_init_recursive().
Referenced by az_object_new(), az_packed_value_array_new(), az_reference_of_new(), az_reference_of_new_value(), and az_value_array_ref_new().
az_instance_new_array()
void * az_instance_new_array (unsigned int type, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, AZ_FLAG_ZERO_MEMORY, az_num_classes, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_init_recursive().
Referenced by az_packed_value_array_new().
az_instance_serialize()
unsigned int az_instance_serialize (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx)
References az_type_get_class.
az_instance_to_string()
unsigned int az_instance_to_string (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen)
References az_type_get_class.
Referenced by reference_of_to_string().
az_interface_finalize()
void az_interface_finalize (const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_TYPE, az_num_classes, AZ_TYPE_INDEX, AZ_TYPE_IS_INTERFACE, and instance_finalize_recursive().
az_interface_init()
void az_interface_init (const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ZERO_MEMORY, az_num_classes, AZ_TYPE_INDEX, AZ_TYPE_IS_INTERFACE, and instance_init_recursive().
az_type_is_convertible_to()
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
True if: type is test both type and test are arithmetic and have automatic conversion rule
Parameters
type the query
test the type to be tested against
Returns
1 if type can be converted
References AZ_CLASS_FROM_TYPE, az_classes, AZ_CONVERT_AUTO, az_init(), az_num_classes, az_primitive_can_convert(), AZ_TYPE_INDEX, AZ_TYPE_IS_ARITHMETIC, and az_type_is_assignable_to().
Referenced by az_function_signature_is_assignable_to().
Variable Documentation
az_classes
AZClass** az_classes extern
Referenced by az_class_new(), az_class_new_with_type(), az_class_new_with_value(), az_classes_init(), az_init(), az_post_init_primitive_classes(), az_reference_of_new_value(), az_register_composite_type(), az_register_type(), az_transfer_value(), az_type_get_parent_primitive(), az_type_implements(), az_type_is_a(), az_type_is_assignable_to(), and az_type_is_convertible_to().
az_num_classes
unsigned int az_num_classes extern
Referenced by az_class_new(), az_classes_init(), az_implementation_init(), az_init(), az_instance_delete(), az_instance_delete_array(), az_instance_finalize(), az_instance_new(), az_instance_new_array(), az_interface_finalize(), az_interface_init(), az_type_get_parent_primitive(), az_type_implements(), az_type_is_a(), az_type_is_assignable_to(), az_type_is_convertible_to(), and az_type_is_valid().
az_types
AZTypeInfo* az_types extern
Referenced by az_class_new(), az_class_new_with_type(), az_class_new_with_value(), az_class_post_init(), az_classes_init(), and az_type_is_a().