az: types.c File Reference
types.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/boxed-value.h>
#include <az/class.h>
#include <az/function.h>
#include <az/interface.h>
#include <az/object.h>
#include <az/primitives.h>
#include <az/private.h>
#include <az/reference.h>
#include <az/boxed-interface.h>
#include <az/types.h>
Macros
#define __AZ_TYPES_C__
Functions
static void instance_init_recursive (const AZClass *klass, const AZImplementation *impl, void *inst, unsigned int zeroed)
static void instance_finalize_recursive (const AZClass *klass, const AZImplementation *impl, void *inst)
static void implementation_init_recursive (AZInterfaceClass *iface_class, AZImplementation *impl)
void az_init (void)
Initialize type system.
unsigned int az_type_get_parent_primitive (unsigned int type)
Get parent primitive type.
unsigned int az_type_is_a (unsigned int type, unsigned int test)
Checks whether the given type is a subtype of another.
unsigned int az_type_implements (unsigned int type, unsigned int test)
Checks whether the given type implements an interface type.
unsigned int az_type_is_assignable_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can be assigned to a variable of given type.
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
void az_instance_initialize (void *inst, unsigned int type)
Initialize a new instance.
void az_instance_finalize (void *inst, unsigned int type)
void az_implementation_init (AZImplementation *impl, unsigned int type)
void az_interface_init (const AZImplementation *impl, void *inst)
void az_interface_finalize (const AZImplementation *impl, void *inst)
void * az_instance_new (unsigned int type)
void * az_instance_new_array (unsigned int type, unsigned int nelements)
void az_instance_delete (unsigned int type, void *instance)
void az_instance_delete_array (unsigned int type, void *elements, unsigned int nelements)
const AZImplementation * az_get_interface (const AZImplementation *impl, void *inst, unsigned int if_type, void **if_inst)
unsigned int az_instance_serialize (const AZImplementation *impl, void *inst, unsigned char *d, unsigned int dlen, AZContext *ctx)
unsigned int az_deserialize_value (const AZImplementation *impl, AZValue *value, const unsigned char *s, unsigned int slen, AZContext *ctx)
unsigned int az_instance_to_string (const AZImplementation *impl, void *inst, unsigned char *buf, unsigned int len)
AZClass * az_register_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*class_init)(AZClass *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *))
Get new typecode, allocate and initialize a class structure.
AZClass * az_register_composite_type (unsigned int *type, const unsigned char *name, unsigned int parent_type, unsigned int class_size, unsigned int instance_size, unsigned int flags, void(*class_init)(AZClass *, void *), void(*instance_init)(const AZImplementation *, void *), void(*instance_finalize)(const AZImplementation *, void *), void *data)
Get new typecode, allocate and initialize a class structure.
Macro Definition Documentation
__AZ_TYPES_C__
#define __AZ_TYPES_C__
Function Documentation
az_deserialize_value()
unsigned int az_deserialize_value (const AZImplementation * impl, AZValue * value, const unsigned char * s, unsigned int slen, AZContext * ctx)
References AZ_CLASS_FROM_IMPL.
az_get_interface()
const AZImplementation * az_get_interface (const AZImplementation * impl, void * inst, unsigned int if_type, void ** if_inst)
References AZ_CLASS_FROM_IMPL, az_class_iface_all(), AZ_IMPL_TYPE, AZ_TYPE_BOXED_INTERFACE, and az_type_is_a().
Referenced by az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_function_invoke_by_type_instance(), az_function_invoke_by_value_signature_va(), az_get_interface_from_type(), az_instance_invoke_function(), az_object_get_interface(), and az_type_implements().
az_implementation_init()
void az_implementation_init (AZImplementation * impl, unsigned int type)
References AZ_CLASS_FROM_TYPE, az_num_types, AZ_TYPE_INTERFACE, az_type_is_a(), and implementation_init_recursive().
Referenced by attrib_dict_impl_init(), and az_class_post_init().
az_init()
void az_init (void)
Initialize type system.
If AZ_SAFETY_CHECKS is set during the compilation of the library, it is called automatically whenever any type is accessed
It is safe to call it more than once
References az_globals_init(), az_init_base_classes(), az_init_boxed_interface_class(), az_init_field_class(), az_init_function_classes(), az_init_interface_class(), az_init_object_class(), az_init_packed_value_class(), az_init_primitive_classes(), az_init_reference_class(), az_init_string_class(), AZ_NUM_BASE_TYPES, az_num_types, and az_post_init_primitive_classes().
Referenced by az_class_new(), az_register_composite_type(), az_register_type(), az_type_get_parent_primitive(), az_type_implements(), az_type_is_a(), az_type_is_assignable_to(), and az_type_is_convertible_to().
az_instance_delete()
void az_instance_delete (unsigned int type, void * instance)
References az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_finalize_recursive().
Referenced by az_function_signature_delete(), az_reference_dispose(), and az_reference_drop().
az_instance_delete_array()
void az_instance_delete_array (unsigned int type, void * elements, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_finalize_recursive().
az_instance_finalize()
void az_instance_finalize (void * inst, unsigned int type)
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, AZ_TYPE_INTERFACE, az_type_is_a(), az_type_is_valid(), and instance_finalize_recursive().
Referenced by array_of_instance_finalize(), az_interface_list_release(), az_object_interface_list_release(), az_object_list_release(), reference_of_instance_finalize(), and value_array_ref_finalize().
az_instance_initialize()
void az_instance_initialize (void * inst, unsigned int type)
Initialize a new instance.
Initializes a new instance by calling recursively all superclass and interface constructors
Parameters
inst pointer to instance
type instance type
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, AZ_FLAG_CONSTRUCT, AZ_FLAG_ZERO_MEMORY, AZ_TYPE_INTERFACE, az_type_is_a(), az_type_is_valid(), and instance_init_recursive().
Referenced by az_instance_init().
az_instance_new()
void * az_instance_new (unsigned int type)
References AZ_CLASS_FROM_TYPE, AZ_FLAG_ABSTRACT, AZ_FLAG_ZERO_MEMORY, az_num_types, AZ_TYPE_INDEX, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_init_recursive().
Referenced by az_object_new(), az_packed_value_array_new(), az_reference_of_new(), az_reference_of_new_value(), and az_value_array_ref_new().
az_instance_new_array()
void * az_instance_new_array (unsigned int type, unsigned int nelements)
References AZ_CLASS_ELEMENT_SIZE, AZ_FLAG_ZERO_MEMORY, az_num_types, az_type_get_class, AZ_TYPE_INTERFACE, az_type_is_a(), and instance_init_recursive().
Referenced by az_packed_value_array_new().
az_instance_serialize()
unsigned int az_instance_serialize (const AZImplementation * impl, void * inst, unsigned char * d, unsigned int dlen, AZContext * ctx)
References AZ_CLASS_FROM_IMPL.
Referenced by serialize_boxed_interface(), and serialize_boxed_value().
az_instance_to_string()
unsigned int az_instance_to_string (const AZImplementation * impl, void * inst, unsigned char * buf, unsigned int len)
References AZ_CLASS_FROM_IMPL.
Referenced by reference_of_to_string().
az_interface_finalize()
void az_interface_finalize (const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_CLASS, AZ_IMPL_TYPE, az_num_types, AZ_TYPE_INDEX, and instance_finalize_recursive().
az_interface_init()
void az_interface_init (const AZImplementation * impl, void * inst)
References AZ_CLASS_FROM_IMPL, AZ_FLAG_ZERO_MEMORY, AZ_IMPL_IS_CLASS, AZ_IMPL_TYPE, az_num_types, AZ_TYPE_INDEX, and instance_init_recursive().
az_type_is_convertible_to()
unsigned int az_type_is_convertible_to (unsigned int type, unsigned int test)
Checks whether a value of certain type can automatically be converted.
True if: type is test both type and test are arithmetic and have automatic conversion rule
Parameters
type the query
test the type to be tested against
Returns
1 if type can be converted
References AZ_CLASS_FROM_TYPE, AZ_CONVERT_AUTO, az_init(), az_num_types, az_primitive_can_convert(), AZ_TYPE_INDEX, AZ_TYPE_IS_ARITHMETIC, and az_type_is_assignable_to().
Referenced by az_function_signature_is_assignable_to().
implementation_init_recursive()
static void implementation_init_recursive (AZInterfaceClass * iface_class, AZImplementation * impl) static
References AZ_CLASS_FROM_TYPE, az_class_iface_self(), AZ_CLASS_TYPE, AZ_TYPE_INTERFACE, and implementation_init_recursive().
Referenced by az_implementation_init(), and implementation_init_recursive().
instance_finalize_recursive()
static void instance_finalize_recursive (const AZClass * klass, const AZImplementation * impl, void * inst) static
References AZ_CLASS_FROM_TYPE, az_class_iface_self(), AZ_CLASS_TYPE, AZ_NUM_FUNDAMENTAL_TYPES, AZ_TYPE_INDEX, and instance_finalize_recursive().
Referenced by az_instance_delete(), az_instance_delete_array(), az_instance_finalize(), az_interface_finalize(), and instance_finalize_recursive().
instance_init_recursive()
static void instance_init_recursive (const AZClass * klass, const AZImplementation * impl, void * inst, unsigned int zeroed) static
References AZ_CLASS_FROM_TYPE, az_class_iface_self(), AZ_CLASS_TYPE, AZ_FLAG_ZERO_MEMORY, AZ_NUM_FUNDAMENTAL_TYPES, AZ_TYPE_INDEX, and instance_init_recursive().
Referenced by az_instance_initialize(), az_instance_new(), az_instance_new_array(), az_interface_init(), and instance_init_recursive().