az: value-array-ref.c File Reference
value-array-ref.c File Reference
#include <az/extend.h>
#include "value-array-ref.h"
Macros
#define __AZ_VALUE_ARRAY_REF_C__
Enumerations
enum { PROP_LENGTH , NUM_PROPERTIES }
Functions
static void value_array_ref_class_init (AZValueArrayRefClass *klass)
static void value_array_ref_init (AZValueArrayRefClass *klass, AZValueArrayRef *varef)
static void value_array_ref_finalize (AZValueArrayRefClass *klass, AZValueArrayRef *varef)
static unsigned int value_array_ref_get_element_type (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int value_array_ref_get_size (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int value_array_ref_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * value_array_ref_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_value_array_ref_get_type (void)
AZValueArrayRef * az_value_array_ref_new (unsigned int length)
void az_value_array_ref_set_element (AZValueArrayRef *varef, unsigned int idx, const AZImplementation *impl, AZValue *value)
Variables
static AZValueArrayRefClass * varef_class = NULL
Macro Definition Documentation
__AZ_VALUE_ARRAY_REF_C__
#define __AZ_VALUE_ARRAY_REF_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_LENGTH
NUM_PROPERTIES
Function Documentation
az_value_array_ref_get_type()
unsigned int az_value_array_ref_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_REFERENCE, value_array_ref_class_init(), value_array_ref_finalize(), and value_array_ref_init().
az_value_array_ref_new()
AZValueArrayRef * az_value_array_ref_new (unsigned int length)
References az_instance_new(), AZ_TYPE_VALUE_ARRAY_REF, and az_value_array_set_length().
az_value_array_ref_set_element()
void az_value_array_ref_set_element (AZValueArrayRef * varef, unsigned int idx, const AZImplementation * impl, AZValue * value)
References az_value_array_set_element().
value_array_ref_class_init()
static void value_array_ref_class_init (AZValueArrayRefClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_FIELD_INSTANCE, AZ_FIELD_READ_VALUE, AZ_TYPE_LIST, AZ_TYPE_UINT32, NUM_PROPERTIES, PROP_LENGTH, value_array_ref_contains(), value_array_ref_get_element(), value_array_ref_get_element_type(), value_array_ref_get_size(), and varef_class.
Referenced by az_value_array_ref_get_type().
value_array_ref_contains()
static unsigned int value_array_ref_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
References az_collection_contains(), and az_value_array_class.
Referenced by value_array_ref_class_init().
value_array_ref_finalize()
static void value_array_ref_finalize (AZValueArrayRefClass * klass, AZValueArrayRef * varef) static
References az_instance_finalize_by_type(), and AZ_TYPE_VALUE_ARRAY.
Referenced by az_value_array_ref_get_type().
value_array_ref_get_element()
static const AZImplementation * value_array_ref_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_list_get_element(), and az_value_array_class.
Referenced by value_array_ref_class_init().
value_array_ref_get_element_type()
static unsigned int value_array_ref_get_element_type (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by value_array_ref_class_init().
value_array_ref_get_size()
static unsigned int value_array_ref_get_size (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by value_array_ref_class_init().
value_array_ref_init()
static void value_array_ref_init (AZValueArrayRefClass * klass, AZValueArrayRef * varef) static
References az_instance_init_by_type(), and AZ_TYPE_VALUE_ARRAY.
Referenced by az_value_array_ref_get_type().
Variable Documentation
varef_class
AZValueArrayRefClass* varef_class = NULL static
Referenced by value_array_ref_class_init().