az: value-array.c File Reference
value-array.c File Reference
#include <stdlib.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/boxed-value.h>
#include <az/packed-value.h>
#include <az/private.h>
#include <az/extend.h>
#include "value-array.h"
Macros
#define __AZ_VALUE_ARRAY_C__
Enumerations
enum { PROP_LENGTH , NUM_PROPERTIES }
Functions
static void value_array_class_init (AZValueArrayClass *klass)
static void value_array_init (AZValueArrayClass *klass, AZValueArray *varray)
static void value_array_finalize (AZValueArrayClass *klass, AZValueArray *varray)
static unsigned int value_array_get_element_type (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int value_array_get_size (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int value_array_contains (const AZCollectionImplementation *collection_impl, void *collection_inst, const AZImplementation *impl, const void *inst)
static const AZImplementation * value_array_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_value_array_get_type (void)
static unsigned int value_array_element_size8 (AZValueArray *varray, unsigned int idx)
static AZValue * value_array_element_value (AZValueArray *varray, unsigned int idx)
void az_value_array_set_length (AZValueArray *varray, unsigned int length)
static unsigned int value_array_ensure_room16 (AZValueArray *varray, unsigned int idx, unsigned int req16)
void az_value_array_set_element (AZValueArray *varray, unsigned int idx, const AZImplementation *impl, const AZValue *val)
void az_value_array_transfer_element (AZValueArray *varray, unsigned int idx, const AZImplementation *impl, const AZValue *val)
static void packed_value_array_class_init (AZPackedValueArrayClass *klass)
static void packed_value_array_finalize (AZPackedValueArrayClass *klass, AZPackedValueArray *varray)
static unsigned int packed_value_array_get_property (const AZImplementation *impl, void *instance, unsigned int idx, const AZImplementation **prop_impl, AZValue *prop_val, AZContext *ctx)
static unsigned int packed_value_array_get_element_type (const AZCollectionImplementation *collection_impl, void *collection_inst)
static unsigned int packed_value_array_get_size (const AZCollectionImplementation *collection_impl, void *collection_inst)
static const AZImplementation * packed_value_array_get_element (const AZListImplementation *list_impl, void *list_inst, unsigned int idx, AZValue *val, unsigned int size)
unsigned int az_packed_value_array_get_type (void)
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
void az_packed_value_array_set_element (AZPackedValueArray *varray, unsigned int idx, const AZPackedValue *value)
Variables
AZValueArrayClass * az_value_array_class = NULL
Macro Definition Documentation
__AZ_VALUE_ARRAY_C__
#define __AZ_VALUE_ARRAY_C__
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_LENGTH
NUM_PROPERTIES
Function Documentation
az_packed_value_array_get_type()
unsigned int az_packed_value_array_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_REFERENCE, packed_value_array_class_init(), and packed_value_array_finalize().
az_packed_value_array_new()
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
References az_instance_new(), az_instance_new_array(), and AZ_TYPE_PACKED_VALUE_ARRAY.
az_packed_value_array_set_element()
void az_packed_value_array_set_element (AZPackedValueArray * varray, unsigned int idx, const AZPackedValue * value)
References az_packed_value_copy().
az_value_array_get_type()
unsigned int az_value_array_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_BLOCK, value_array_class_init(), value_array_finalize(), and value_array_init().
az_value_array_set_element()
void az_value_array_set_element (AZValueArray * varray, unsigned int idx, const AZImplementation * impl, const AZValue * val)
References AZ_IMPL_TYPE, AZ_TYPE_VALUE_SIZE, az_value_clear(), az_value_copy(), value_array_element_value(), and value_array_ensure_room16().
Referenced by az_value_array_ref_set_element().
az_value_array_set_length()
void az_value_array_set_length (AZValueArray * varray, unsigned int length)
References az_value_clear(), and value_array_element_value().
Referenced by az_value_array_ref_new().
az_value_array_transfer_element()
void az_value_array_transfer_element (AZValueArray * varray, unsigned int idx, const AZImplementation * impl, const AZValue * val)
References AZ_CLASS_FROM_IMPL, AZ_CLASS_VALUE_SIZE, az_value_clear(), az_value_transfer(), value_array_element_value(), and value_array_ensure_room16().
packed_value_array_class_init()
static void packed_value_array_class_init (AZPackedValueArrayClass * klass) static
References az_class_declare_interface(), az_class_set_num_interfaces(), AZ_FIELD_INSTANCE, AZ_FIELD_READ_METHOD, AZ_FIELD_WRITE_NONE, AZ_TYPE_LIST, AZ_TYPE_UINT32, NUM_PROPERTIES, packed_value_array_get_element(), packed_value_array_get_element_type(), packed_value_array_get_property(), packed_value_array_get_size(), and PROP_LENGTH.
Referenced by az_packed_value_array_get_type().
packed_value_array_finalize()
static void packed_value_array_finalize (AZPackedValueArrayClass * klass, AZPackedValueArray * varray) static
References az_packed_value_clear().
Referenced by az_packed_value_array_get_type().
packed_value_array_get_element()
static const AZImplementation * packed_value_array_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_value_copy_autobox().
Referenced by packed_value_array_class_init().
packed_value_array_get_element_type()
static unsigned int packed_value_array_get_element_type (const AZCollectionImplementation * collection_impl, void * collection_inst) static
References AZ_TYPE_ANY.
Referenced by packed_value_array_class_init().
packed_value_array_get_property()
static unsigned int packed_value_array_get_property (const AZImplementation * impl, void * instance, unsigned int idx, const AZImplementation ** prop_impl, AZValue * prop_val, AZContext * ctx) static
References AZ_IMPL_FROM_TYPE, AZ_TYPE_UINT32, and PROP_LENGTH.
Referenced by packed_value_array_class_init().
packed_value_array_get_size()
static unsigned int packed_value_array_get_size (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by packed_value_array_class_init().
value_array_class_init()
static void value_array_class_init (AZValueArrayClass * klass) static
References az_value_array_class, value_array_contains(), value_array_get_element(), value_array_get_element_type(), and value_array_get_size().
Referenced by az_value_array_get_type().
value_array_contains()
static unsigned int value_array_contains (const AZCollectionImplementation * collection_impl, void * collection_inst, const AZImplementation * impl, const void * inst) static
References AZ_IMPL_TYPE, AZ_TYPE_IS_VALUE, AZ_TYPE_VALUE_SIZE, and value_array_element_value().
Referenced by value_array_class_init().
value_array_element_size8()
static unsigned int value_array_element_size8 (AZValueArray * varray, unsigned int idx) static
References AZ_IMPL_TYPE, and AZ_TYPE_VALUE_SIZE.
Referenced by value_array_element_value(), and value_array_ensure_room16().
value_array_element_value()
static AZValue * value_array_element_value (AZValueArray * varray, unsigned int idx) static
References value_array_element_size8().
Referenced by az_value_array_set_element(), az_value_array_set_length(), az_value_array_transfer_element(), value_array_contains(), value_array_finalize(), and value_array_get_element().
value_array_ensure_room16()
static unsigned int value_array_ensure_room16 (AZValueArray * varray, unsigned int idx, unsigned int req16) static
References value_array_element_size8().
Referenced by az_value_array_set_element(), and az_value_array_transfer_element().
value_array_finalize()
static void value_array_finalize (AZValueArrayClass * klass, AZValueArray * varray) static
References az_value_clear(), and value_array_element_value().
Referenced by az_value_array_get_type().
value_array_get_element()
static const AZImplementation * value_array_get_element (const AZListImplementation * list_impl, void * list_inst, unsigned int idx, AZValue * val, unsigned int size) static
References az_value_copy_autobox(), and value_array_element_value().
Referenced by value_array_class_init().
value_array_get_element_type()
static unsigned int value_array_get_element_type (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by value_array_class_init().
value_array_get_size()
static unsigned int value_array_get_size (const AZCollectionImplementation * collection_impl, void * collection_inst) static
Referenced by value_array_class_init().
value_array_init()
static void value_array_init (AZValueArrayClass * klass, AZValueArray * varray) static
References AZ_TYPE_ANY.
Referenced by az_value_array_get_type().
Variable Documentation
az_value_array_class
AZValueArrayClass* az_value_array_class = NULL
Referenced by value_array_class_init(), value_array_ref_contains(), and value_array_ref_get_element().