az: value.h File Reference
value.h File Reference
#include <stdint.h>
#include <string.h>
#include <arikkei/arikkei-utils.h>
#include <az/class.h>
#include <az/complex.h>
#include <az/interface.h>
#include <az/instance.h>
#include <az/reference.h>
Data Structures
struct AZValue
A convenience union of most common values.
struct AZValue64
A convenience union for value sizes up to 64 bytes.
Macros
#define AZ_PACKED_VALUE_MAX_SIZE 16
Functions
static void az_value_init (const AZImplementation *impl, AZValue *val)
initialize a value location
const AZImplementation * az_value_init_autobox (const AZImplementation *impl, AZValue *dst, unsigned int size)
static void az_value_clear (const AZImplementation *impl, AZValue *val)
clear an value location
static void az_value_transfer (const AZImplementation *impl, AZValue *dst, const AZValue *src)
transfer a value to a new location
const AZImplementation * az_value_transfer_autobox (const AZImplementation *impl, AZValue *dst, AZValue *src, unsigned int size)
tranfer a value to a new location, boxing/unboxing if needed
static void az_value_copy (const AZImplementation *impl, AZValue *dst, const AZValue *src)
copy a value to a new location
const AZImplementation * az_value_copy_autobox (const AZImplementation *impl, AZValue *dst, const AZValue *src, unsigned int size)
copy a value from one handle to another, boxing/unboxing if needed
void az_value_set_from_inst (const AZImplementation *impl, AZValue *dst, void *inst)
set value from instance
const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation *impl, AZValue *dst, void *inst, unsigned int size)
set value from instance, boxing if needed
static void * az_value_get_inst (const AZImplementation *impl, const AZValue *val)
dereference instance from value
const AZImplementation * az_value_get_inst_autobox (const AZImplementation *impl, const AZValue *val, void **inst)
ereference instance from value, unboxing if needed
unsigned int az_value_deserialize (const AZImplementation *impl, AZValue *val, const unsigned char *s, unsigned int slen, AZContext *ctx)
creates a value from serialized data
unsigned int az_value_equals (const AZImplementation *impl, const AZValue *lhs, const AZValue *rhs)
compares two values for equality
unsigned int az_value_equals_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const AZValue *rhs)
unsigned int az_value_equals_instance (const AZImplementation *impl, const AZValue *lhs, const void *rhs)
unsigned int az_value_equals_instance_autobox (const AZImplementation *lhs_impl, const AZValue *lhs, const AZImplementation *rhs_impl, const void *rhs)
ARIKKEI_INLINE void az_value_transfer_reference (AZValue *dst_val, AZReference *inst)
ARIKKEI_INLINE void az_value_set_reference (AZValue *dst_val, AZReference *inst)
void * az_value_new_array (const AZImplementation *impl, unsigned int length)
void az_value_delete_array (const AZImplementation *impl, void *data, unsigned int length)
unsigned int az_value_convert_auto (const AZImplementation **dst_impl, AZValue *dst_val, const AZImplementation **src_impl, const AZValue *src_val, unsigned int to_type)
unsigned int az_value_convert_in_place (const AZImplementation **impl, AZValue *val, unsigned int to_type)
Macro Definition Documentation
AZ_PACKED_VALUE_MAX_SIZE
#define AZ_PACKED_VALUE_MAX_SIZE 16
Function Documentation
az_value_clear()
static void az_value_clear (const AZImplementation * impl, AZValue * val) inline static
clear an value location
Remove reference hold by the value for reference types. After the operation the val is in uninitialized state.
Parameters
impl the value implementation
val the value to be cleared
References az_reference_unref(), and AZ_TYPE_IS_REFERENCE.
Referenced by array_list_finalize(), az_array_list_clear(), az_array_list_remove(), az_array_list_set_element(), az_value_array_set_element(), az_value_array_set_length(), az_value_array_transfer_element(), az_value_delete_array(), az_value_transfer_autobox(), and value_array_finalize().
az_value_convert_auto()
unsigned int az_value_convert_auto (const AZImplementation ** dst_impl, AZValue * dst_val, const AZImplementation ** src_impl, const AZValue * src_val, unsigned int to_type)
References az_boxed_interface_new_from_impl_value(), az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_BLOCK, AZ_FLAG_INTERFACE, AZ_IMPL_FROM_TYPE, AZ_IMPL_TYPE, az_primitive_can_convert(), AZ_TYPE_ANY, AZ_TYPE_BOXED_INTERFACE, az_type_get_class, az_type_implements(), az_type_is_a(), AZ_TYPE_IS_ARITHMETIC, and az_value_copy().
az_value_convert_in_place()
unsigned int az_value_convert_in_place (const AZImplementation ** impl, AZValue * val, unsigned int to_type)
References az_boxed_interface_new_from_impl_value(), az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_BLOCK, AZ_FLAG_INTERFACE, AZ_IMPL_FROM_TYPE, AZ_IMPL_TYPE, az_primitive_can_convert(), AZ_TYPE_ANY, AZ_TYPE_BOXED_INTERFACE, az_type_get_class, az_type_implements(), az_type_is_a(), and AZ_TYPE_IS_ARITHMETIC.
Referenced by az_function_convert_args_in_place().
az_value_copy()
static void az_value_copy (const AZImplementation * impl, AZValue * dst, const AZValue * src) inline static
copy a value to a new location
Copy data from initialized src to uninitialized dst. After the operation src will reamin intact.
Parameters
impl the src implemntation
dst the destination (uninitialized)
src the source value
References AZ_CLASS_FROM_IMPL, az_class_value_size(), AZ_IMPL_IS_REFERENCE, and az_reference_ref().
Referenced by az_boxed_value_new_from_val(), az_boxed_value_unbox(), az_value_array_set_element(), az_value_convert_auto(), az_value_copy_autobox(), az_value_set_from_packed_value(), and az_value_transfer_autobox().
az_value_copy_autobox()
const AZImplementation * az_value_copy_autobox (const AZImplementation * impl, AZValue * dst, const AZValue * src, unsigned int size)
copy a value from one handle to another, boxing/unboxing if needed
Copy data from initialized src to uninitialized dst. After the operation src will reamin intact. If the source does not fit into size bytes AZBoxedValue is created in dst. If src is AZBoxedValue but the value fits into dst the actual value is copied.
Parameters
impl the src implemntation
dst the destination (uninitialized)
src the source value
size the size of the destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_copy(), and AZBoxedValueKlass.
Referenced by aobj_aa_get_element(), aobj_aa_map_lookup(), aobj_attrd_lookup(), array_get_element(), array_list_get_element(), array_object_get_element(), az_value_set_from_packed_value_autobox(), packed_value_array_get_element(), and value_array_get_element().
az_value_delete_array()
void az_value_delete_array (const AZImplementation * impl, void * data, unsigned int length)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), and az_value_clear().
Referenced by array_object_instance_finalize().
az_value_deserialize()
unsigned int az_value_deserialize (const AZImplementation * impl, AZValue * val, const unsigned char * s, unsigned int slen, AZContext * ctx)
creates a value from serialized data
Parameters
impl the type implementation
val pointer to uninitialized target value
s source buffer
slen source buffer length
ctx the execution context
Returns
the number of bytes consumed (0 on error)
References AZ_CLASS_FROM_IMPL.
Referenced by array_deserialize().
az_value_equals()
unsigned int az_value_equals (const AZImplementation * impl, const AZValue * lhs, const AZValue * rhs)
compares two values for equality
Value equality is defined as bitwise equality of value data - i.e. equality of structs or block pointers
Parameters
impl the type implementation
lhs left hand value
rhs right hand value
Returns
1 if equal, 0 if not
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, and AZ_IMPL_IS_VALUE.
az_value_equals_autobox()
unsigned int az_value_equals_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const AZValue * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
az_value_equals_instance()
unsigned int az_value_equals_instance (const AZImplementation * impl, const AZValue * lhs, const void * rhs)
References AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and AZ_FLAG_BLOCK.
Referenced by aobj_aa_contains().
az_value_equals_instance_autobox()
unsigned int az_value_equals_instance_autobox (const AZImplementation * lhs_impl, const AZValue * lhs, const AZImplementation * rhs_impl, const void * rhs)
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, and AZBoxedValueKlass.
Referenced by array_contains(), array_list_contains(), and array_object_contains().
az_value_get_inst()
static void * az_value_get_inst (const AZImplementation * impl, const AZValue * val) inline static
dereference instance from value
Does not unbox automatically.
Parameters
impl the type implementation
val the source value
Returns
pointer to the instance
References AZ_IMPL_IS_BLOCK.
Referenced by az_active_object_set_attribute(), az_boxed_interface_new_from_impl_instance(), az_boxed_interface_new_from_impl_value(), az_boxed_interface_new_from_impl_value_autobox(), az_function_invoke_by_value_signature_va(), az_packed_value_64_set_from_val_autobox(), az_packed_value_get_inst(), az_packed_value_set_from_val(), az_packed_value_set_from_val_autobox(), collection_call_contains(), and impl_call_setStaticProperty().
az_value_get_inst_autobox()
const AZImplementation * az_value_get_inst_autobox (const AZImplementation * impl, const AZValue * val, void ** inst)
ereference instance from value, unboxing if needed
If the value is AZBoxedValue, return the actual implementation and instance inside it.
Parameters
impl the type implementation
val the source value
inst the result instance
Returns
the actual implementation (may be changed by unboxing)
References AZ_IMPL_IS_BLOCK, and AZBoxedValueKlass.
Referenced by az_packed_value_get_inst_autobox().
az_value_init()
static void az_value_init (const AZImplementation * impl, AZValue * val) inline static
initialize a value location
For value types it calls the constructor, for block types sets pointer to null.
Parameters
impl the type implementation
val the value (uninitialized)
References AZ_IMPL_IS_BLOCK, AZ_IMPL_IS_VALUE, AZ_IMPL_TYPE, and az_instance_init_by_type().
Referenced by az_packed_value_init(), and az_value_new_array().
az_value_init_autobox()
const AZImplementation * az_value_init_autobox (const AZImplementation * impl, AZValue * dst, unsigned int size)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and az_instance_init().
Referenced by az_packed_value_64_init_autobox(), and az_packed_value_init_autobox().
az_value_new_array()
void * az_value_new_array (const AZImplementation * impl, unsigned int length)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), and az_value_init().
Referenced by array_deserialize(), and az_array_object_new().
az_value_set_from_inst()
void az_value_set_from_inst (const AZImplementation * impl, AZValue * dst, void * inst)
set value from instance
Parameters
impl the type implementation
dst the destination (uninitialized)
inst the source instance
References AZ_CLASS_FROM_IMPL, AZ_FLAG_BLOCK, AZ_FLAG_REFERENCE, and az_reference_ref().
Referenced by az_boxed_value_new_from_inst(), az_field_setup_stored(), az_packed_value_set(), and az_value_set_from_inst_autobox().
az_value_set_from_inst_autobox()
const AZImplementation * az_value_set_from_inst_autobox (const AZImplementation * impl, AZValue * dst, void * inst, unsigned int size)
set value from instance, boxing if needed
If the value does not fit into size bytes, AZBoxedValue is created at dst. It does not unbox automatically.
Parameters
impl the type implemntation
dst the destination (uninitialized)
inst the source instance
size the size of the destination value
Returns
the dst implementation (may be changed by boxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_inst(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and az_value_set_from_inst().
Referenced by az_array_list_append(), az_array_list_insert(), az_array_list_set_element(), az_packed_value_64_set_autobox(), and az_packed_value_set_autobox().
az_value_set_reference()
ARIKKEI_INLINE void az_value_set_reference (AZValue * dst_val, AZReference * inst)
References az_reference_ref().
Referenced by aobj_aa_keys_get_element().
az_value_transfer()
static void az_value_transfer (const AZImplementation * impl, AZValue * dst, const AZValue * src) inline static
transfer a value to a new location
Move data from initialized src to uninitialized dst. After the operation src will be uninitialized.
Parameters
impl the src implementation
dst the destination (uninitialized)
src the source value
References AZ_CLASS_FROM_IMPL, and az_class_value_size().
Referenced by az_value_array_transfer_element(), and az_value_transfer_autobox().
az_value_transfer_autobox()
const AZImplementation * az_value_transfer_autobox (const AZImplementation * impl, AZValue * dst, AZValue * src, unsigned int size)
tranfer a value to a new location, boxing/unboxing if needed
If the src value does not fit into size bytes, AZBoxedValue is created at dst. If the src is an AZBoxedValue but the value fits into dst, the actual value is unboxed to dst. After the transfer src will be in uninitialized state.
Parameters
impl the src implemntation
dst the destination (uninitialized)
src the source value
size the size of the destination value
Returns
the dst implementation (may be changed by boxing/unboxing)
References AZ_BOXED_VALUE_IMPL, az_boxed_value_new_from_val(), AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, az_value_clear(), az_value_copy(), az_value_transfer(), and AZBoxedValueKlass.
az_value_transfer_reference()
ARIKKEI_INLINE void az_value_transfer_reference (AZValue * dst_val, AZReference * inst)
Referenced by az_value_set_interface_autobox().