az: value-array.h File Reference
value-array.h File Reference
#include <az/collections/list.h>
#include <az/reference.h>
Data Structures
struct AZValueArrayEntry
struct AZValueArray
struct AZValueArrayClass
struct AZPackedValueArray
struct AZPackedValueArrayClass
Macros
#define AZ_TYPE_VALUE_ARRAY az_value_array_get_type ()
#define AZ_TYPE_PACKED_VALUE_ARRAY az_packed_value_array_get_type ()
Functions
unsigned int az_value_array_get_type (void)
void az_value_array_set_length (AZValueArray *varray, unsigned int length)
void az_value_array_set_element (AZValueArray *varray, unsigned int idx, const AZImplementation *impl, const AZValue *val)
void az_value_array_transfer_element (AZValueArray *varray, unsigned int idx, const AZImplementation *impl, const AZValue *val)
unsigned int az_packed_value_array_get_type (void)
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
void az_packed_value_array_set_element (AZPackedValueArray *varray, unsigned int idx, const AZPackedValue *value)
Variables
AZValueArrayClass * az_value_array_class
Macro Definition Documentation
AZ_TYPE_PACKED_VALUE_ARRAY
#define AZ_TYPE_PACKED_VALUE_ARRAY az_packed_value_array_get_type ()
AZ_TYPE_VALUE_ARRAY
#define AZ_TYPE_VALUE_ARRAY az_value_array_get_type ()
Function Documentation
az_packed_value_array_get_type()
unsigned int az_packed_value_array_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_REFERENCE, packed_value_array_class_init(), and packed_value_array_finalize().
az_packed_value_array_new()
AZPackedValueArray * az_packed_value_array_new (unsigned int length)
References az_instance_new(), az_instance_new_array(), and AZ_TYPE_PACKED_VALUE_ARRAY.
az_packed_value_array_set_element()
void az_packed_value_array_set_element (AZPackedValueArray * varray, unsigned int idx, const AZPackedValue * value)
References az_packed_value_copy().
az_value_array_get_type()
unsigned int az_value_array_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_BLOCK, value_array_class_init(), value_array_finalize(), and value_array_init().
az_value_array_set_element()
void az_value_array_set_element (AZValueArray * varray, unsigned int idx, const AZImplementation * impl, const AZValue * val)
References AZ_IMPL_TYPE, AZ_TYPE_VALUE_SIZE, az_value_clear(), az_value_copy(), value_array_element_value(), and value_array_ensure_room16().
Referenced by az_value_array_ref_set_element().
az_value_array_set_length()
void az_value_array_set_length (AZValueArray * varray, unsigned int length)
References az_value_clear(), and value_array_element_value().
Referenced by az_value_array_ref_new().
az_value_array_transfer_element()
void az_value_array_transfer_element (AZValueArray * varray, unsigned int idx, const AZImplementation * impl, const AZValue * val)
References AZ_CLASS_FROM_IMPL, AZ_CLASS_VALUE_SIZE, az_value_clear(), az_value_transfer(), value_array_element_value(), and value_array_ensure_room16().
Variable Documentation
az_value_array_class
AZValueArrayClass* az_value_array_class extern
Referenced by value_array_class_init(), value_array_ref_contains(), and value_array_ref_get_element().