az: value-array-ref.h File Reference
value-array-ref.h File Reference
#include <az/reference.h>
#include <az/classes/value-array.h>
Data Structures
struct AZValueArrayRef
struct AZValueArrayRefClass
Macros
#define AZ_TYPE_VALUE_ARRAY_REF az_value_array_ref_get_type ()
Functions
unsigned int az_value_array_ref_get_type (void)
AZValueArrayRef * az_value_array_ref_new (unsigned int length)
void az_value_array_ref_set_element (AZValueArrayRef *varef, unsigned int idx, const AZImplementation *impl, AZValue *value)
Macro Definition Documentation
AZ_TYPE_VALUE_ARRAY_REF
#define AZ_TYPE_VALUE_ARRAY_REF az_value_array_ref_get_type ()
Function Documentation
az_value_array_ref_get_type()
unsigned int az_value_array_ref_get_type (void)
References AZ_FLAG_FINAL, az_register_type(), AZ_TYPE_REFERENCE, value_array_ref_class_init(), value_array_ref_finalize(), and value_array_ref_init().
az_value_array_ref_new()
AZValueArrayRef * az_value_array_ref_new (unsigned int length)
References az_instance_new(), AZ_TYPE_VALUE_ARRAY_REF, and az_value_array_set_length().
az_value_array_ref_set_element()
void az_value_array_ref_set_element (AZValueArrayRef * varef, unsigned int idx, const AZImplementation * impl, AZValue * value)
References az_value_array_set_element().