az: value.c File Reference
value.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <az/boxed-interface.h>
#include <az/boxed-value.h>
#include <az/class.h>
#include <az/primitives.h>
#include <az/private.h>
#include <az/reference-of.h>
#include <az/value.h>
Macros
#define __AZ_VALUE_C__
Functions
void az_value_set_from_inst (const AZImplementation *impl, AZValue *dst, void *inst)
set value from instance
unsigned int az_value_deserialize (const AZImplementation *impl, AZValue *val, const unsigned char *s, unsigned int slen, AZContext *ctx)
creates a value from serialized data
unsigned int az_value_equals (const AZImplementation *impl, const AZValue *lhs, const AZValue *rhs)
compares two values for equality
unsigned int az_value_equals_instance (const AZImplementation *impl, const AZValue *lhs, const void *rhs)
void * az_value_new_array (const AZImplementation *impl, unsigned int length)
void az_value_delete_array (const AZImplementation *impl, void *data, unsigned int length)
unsigned int az_value_convert_auto (const AZImplementation **dst_impl, AZValue *dst_val, const AZImplementation **src_impl, const AZValue *src_val, unsigned int to_type)
unsigned int az_value_convert_in_place (const AZImplementation **impl, AZValue *val, unsigned int to_type)
Macro Definition Documentation
__AZ_VALUE_C__
#define __AZ_VALUE_C__
Function Documentation
az_value_convert_auto()
unsigned int az_value_convert_auto (const AZImplementation ** dst_impl, AZValue * dst_val, const AZImplementation ** src_impl, const AZValue * src_val, unsigned int to_type)
References az_boxed_interface_new_from_impl_value(), az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_BLOCK, AZ_FLAG_INTERFACE, AZ_IMPL_FROM_TYPE, AZ_IMPL_TYPE, az_primitive_can_convert(), AZ_TYPE_ANY, AZ_TYPE_BOXED_INTERFACE, az_type_get_class, az_type_implements(), az_type_is_a(), AZ_TYPE_IS_ARITHMETIC, and az_value_copy().
az_value_convert_in_place()
unsigned int az_value_convert_in_place (const AZImplementation ** impl, AZValue * val, unsigned int to_type)
References az_boxed_interface_new_from_impl_value(), az_convert_arithmetic_type(), AZ_CONVERT_CONDITIONAL, AZ_FLAG_BLOCK, AZ_FLAG_INTERFACE, AZ_IMPL_FROM_TYPE, AZ_IMPL_TYPE, az_primitive_can_convert(), AZ_TYPE_ANY, AZ_TYPE_BOXED_INTERFACE, az_type_get_class, az_type_implements(), az_type_is_a(), and AZ_TYPE_IS_ARITHMETIC.
Referenced by az_function_convert_args_in_place().
az_value_delete_array()
void az_value_delete_array (const AZImplementation * impl, void * data, unsigned int length)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), and az_value_clear().
Referenced by array_object_instance_finalize().
az_value_deserialize()
unsigned int az_value_deserialize (const AZImplementation * impl, AZValue * val, const unsigned char * s, unsigned int slen, AZContext * ctx)
creates a value from serialized data
Parameters
impl the type implementation
val pointer to uninitialized target value
s source buffer
slen source buffer length
ctx the execution context
Returns
the number of bytes consumed (0 on error)
References AZ_CLASS_FROM_IMPL.
Referenced by array_deserialize().
az_value_equals()
unsigned int az_value_equals (const AZImplementation * impl, const AZValue * lhs, const AZValue * rhs)
compares two values for equality
Value equality is defined as bitwise equality of value data - i.e. equality of structs or block pointers
Parameters
impl the type implementation
lhs left hand value
rhs right hand value
Returns
1 if equal, 0 if not
References AZ_CLASS_FROM_IMPL, AZ_IMPL_IS_BLOCK, and AZ_IMPL_IS_VALUE.
az_value_equals_instance()
unsigned int az_value_equals_instance (const AZImplementation * impl, const AZValue * lhs, const void * rhs)
References AZ_CLASS_FROM_IMPL, AZ_CLASS_IS_VALUE, and AZ_FLAG_BLOCK.
Referenced by aobj_aa_contains().
az_value_new_array()
void * az_value_new_array (const AZImplementation * impl, unsigned int length)
References AZ_CLASS_FROM_IMPL, az_class_value_size(), and az_value_init().
Referenced by array_deserialize(), and az_array_object_new().
az_value_set_from_inst()
void az_value_set_from_inst (const AZImplementation * impl, AZValue * dst, void * inst)
set value from instance
Parameters
impl the type implementation
dst the destination (uninitialized)
inst the source instance
References AZ_CLASS_FROM_IMPL, AZ_FLAG_BLOCK, AZ_FLAG_REFERENCE, and az_reference_ref().
Referenced by az_boxed_value_new_from_inst(), az_field_setup_stored(), az_packed_value_set(), and az_value_set_from_inst_autobox().