az: weak-reference.h File Reference
weak-reference.h File Reference
#include <az/classes/active-object.h>
Data Structures
struct AZWeakReference
struct AZWeakReferenceClass
Macros
#define AZ_TYPE_WEAK_REFERENCE az_weak_reference_get_type ()
Functions
unsigned int az_weak_reference_get_type (void)
void az_weak_reference_set (AZWeakReference *ref, AZActiveObject *object)
void az_weak_reference_clear (AZWeakReference *ref)
Macro Definition Documentation
AZ_TYPE_WEAK_REFERENCE
#define AZ_TYPE_WEAK_REFERENCE az_weak_reference_get_type ()
Function Documentation
az_weak_reference_clear()
void az_weak_reference_clear (AZWeakReference * ref)
References az_active_object_remove_listener_by_data().
Referenced by az_weak_reference_set().
az_weak_reference_get_type()
unsigned int az_weak_reference_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_ANY, weak_reference_finalize(), and weak_reference_type.
az_weak_reference_set()
void az_weak_reference_set (AZWeakReference * ref, AZActiveObject * object)
References az_active_object_add_listener(), az_weak_reference_clear(), and weak_reference_event_vec.