az: weak-reference.c File Reference
weak-reference.c File Reference
#include <az/extend.h>
#include "weak-reference.h"
Macros
#define __AZ_WEAK_REFERENCE_C__
Functions
static void weak_reference_finalize (AZWeakReferenceClass *klass, AZWeakReference *ref)
static void weak_reference_object_dispose (AZActiveObject *object, void *data)
unsigned int az_weak_reference_get_type (void)
void az_weak_reference_set (AZWeakReference *ref, AZActiveObject *object)
void az_weak_reference_clear (AZWeakReference *ref)
Variables
AZObjectEventVector weak_reference_event_vec
static unsigned int weak_reference_type = 0
Macro Definition Documentation
__AZ_WEAK_REFERENCE_C__
#define __AZ_WEAK_REFERENCE_C__
Function Documentation
az_weak_reference_clear()
void az_weak_reference_clear (AZWeakReference * ref)
References az_active_object_remove_listener_by_data().
Referenced by az_weak_reference_set().
az_weak_reference_get_type()
unsigned int az_weak_reference_get_type (void)
References AZ_FLAG_FINAL, AZ_FLAG_ZERO_MEMORY, az_register_type(), AZ_TYPE_ANY, weak_reference_finalize(), and weak_reference_type.
az_weak_reference_set()
void az_weak_reference_set (AZWeakReference * ref, AZActiveObject * object)
References az_active_object_add_listener(), az_weak_reference_clear(), and weak_reference_event_vec.
weak_reference_finalize()
static void weak_reference_finalize (AZWeakReferenceClass * klass, AZWeakReference * ref) static
References az_active_object_remove_listener_by_data().
Referenced by az_weak_reference_get_type().
weak_reference_object_dispose()
static void weak_reference_object_dispose (AZActiveObject * object, void * data) static
Variable Documentation
weak_reference_event_vec
AZObjectEventVector weak_reference_event_vec
Initial value:
= {
    weak_reference_object_dispose
}
Referenced by az_weak_reference_set().
weak_reference_type
unsigned int weak_reference_type = 0 static
Referenced by az_weak_reference_get_type().